# 🧪 Data Transformation & Preprocessing

This notebook documents the process for transforming and preparing the raw data from OpenStreetMap for the final database.

## Data Source

Topic: Bouldering Spots

**Main source:**

* Name: OpenStreetMap (OSM) via OSMnx library
* Source and origin: Public crowdsourced geospatial database
* Update frequency: Continuous (dynamic)
* Data type: Dynamic (API query using climbing:boulder=yes)

## Import Libraries

In [1]:
import time
import pandas as pd
import osmnx as ox
import geopandas as gpd

from geopy.geocoders import Nominatim
from sqlalchemy import create_engine, text

## Loading Bouldering Spots Data from OSM

The following command retrieves all bouldering spots from Berlin that have been tagged with `climbing:boulder=yes`.

In [2]:
tags = {"climbing:boulder": "yes"}
gdf = ox.features_from_place("Berlin, Germany", tags=tags)

gdf.head()

                                     geometry climbing:boulder        leisure  \
element id
node    1066131768  POINT (13.26476 52.41394)              yes          pitch
        1768495247  POINT (13.44855 52.49599)              yes            NaN
        3966842994  POINT (13.42867 52.49513)              yes  sports_centre
        3989801753  POINT (13.22107 52.54211)              yes  sports_centre
        4622626832   POINT (13.4516 52.47944)              yes     playground

                                     name     sport  \
element id
node    1066131768          Boulderfelsen  climbing
        1768495247                    NaN  climbing
        3966842994  Boulderklub Kreuzberg  climbing
        3989801753            Cliffhanger  climbing
        4622626832             Kinderwald       NaN

                                                             note  \
element id
node    1066131768                                            NaN
        1768495247  mixture of playground climbing and bouldering
        3966842994                                            NaN
        3989801753                                            NaN
        4622626832                                            NaN

                      playground addr:city addr:housenumber addr:postcode  \
element id
node    1066131768           NaN       NaN              NaN           NaN
        1768495247  climbingwall       NaN              NaN           NaN
        3966842994           NaN    Berlin               38         10999
        3989801753           NaN    Berlin              NaN         13599
        4622626832           NaN       NaN              NaN           NaN

                    ... outdoor area barrier addr:unit name:en name:signed  \
element id          ...
node    1066131768  ...     NaN  NaN     NaN       NaN     NaN         NaN
        1768495247  ...     NaN  NaN     NaN       NaN     NaN         NaN
        3966842994  ...     NaN  NaN     NaN       NaN     NaN         NaN
        3989801753  ...     NaN  NaN     NaN       NaN     NaN         NaN
        4622626832  ...     NaN  NaN     NaN       NaN     NaN         NaN

                   contact:email contact:instagram climbing old_name
element id
node    1066131768           NaN               NaN      NaN      NaN
        1768495247           NaN               NaN      NaN      NaN
        3966842994           NaN               NaN      NaN      NaN
        3989801753           NaN               NaN      NaN      NaN
        4622626832           NaN               NaN      NaN      NaN

[5 rows x 69 columns]

In [3]:
print(f"Number of bouldering spots fetched: {len(gdf)}")

Number of bouldering spots fetched: 36

In [4]:
gdf.info()

<class 'geopandas.geodataframe.GeoDataFrame'>
MultiIndex: 36 entries, ('node', np.int64(1066131768)) to ('way', np.int64(1022247980))
Data columns (total 69 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   geometry                  36 non-null     geometry
 1   climbing:boulder          36 non-null     object
 2   leisure                   19 non-null     object
 3   name                      19 non-null     object
 4   sport                     34 non-null     object
 5   note                      1 non-null      object
 6   playground                3 non-null      object
 7   addr:city                 12 non-null     object
 8   addr:housenumber          11 non-null     object
 9   addr:postcode             12 non-null     object
 10  addr:street               12 non-null     object
 11  climbing:sport            11 non-null     object
 12  climbing:toprope          6 non-null      object
 13  contact:phone             2 non-null      object
 14  contact:website           2 non-null      object
 15  indoor                    13 non-null     object
 16  opening_hours             10 non-null     object
 17  wheelchair                8 non-null      object
 18  addr:country              10 non-null     object
 19  addr:housename            4 non-null      object
 20  description               3 non-null      object
 21  fee                       11 non-null     object
 22  internet_access           2 non-null      object
 23  operator                  8 non-null      object
 24  phone                     6 non-null      object
 25  website                   8 non-null      object
 26  access                    7 non-null      object
 27  addr:suburb               8 non-null      object
 28  check_date                4 non-null      object
 29  climbing:length           9 non-null      object
 30  email                     2 non-null      object
 31  level                     2 non-null      object
 32  min_age                   1 non-null      object
 33  operator:type             1 non-null      object
 34  payment:cash              4 non-null      object
 35  payment:credit_cards      3 non-null      object
 36  payment:debit_cards       3 non-null      object
 37  charge                    1 non-null      object
 38  check_date:opening_hours  1 non-null      object
 39  internet_access:fee       1 non-null      object
 40  toilets:wheelchair        2 non-null      object
 41  lit                       4 non-null      object
 42  natural                   5 non-null      object
 43  building                  10 non-null     object
 44  height                    7 non-null      object
 45  climbing:bolted           6 non-null      object
 46  building:levels           2 non-null      object
 47  changing_table            1 non-null      object
 48  roof:levels               1 non-null      object
 49  roof:shape                1 non-null      object
 50  climbing:outdoor          8 non-null      object
 51  man_made                  6 non-null      object
 52  tower:type                6 non-null      object
 53  climbing:rock             3 non-null      object
 54  summit:cross              1 non-null      object
 55  alt_name                  2 non-null      object
 56  building:colour           1 non-null      object
 57  building:material         1 non-null      object
 58  start_date                2 non-null      object
 59  outdoor                   6 non-null      object
 60  area                      2 non-null      object
 61  barrier                   2 non-null      object
 62  addr:unit                 1 non-null      object
 63  name:en                   1 non-null      object
 64  name:signed               2 non-null      object
 65  contact:email             1 non-null      object
 66  contact:instagram         1 non-null      object
 67  climbing                  1 non-null      object
 68  old_name                  1 non-null      object
dtypes: geometry(1), object(68)
memory usage: 21.0+ KB

## Keep OSM ID column

The OSM ID column is required the final table schema.
Using OSM's internal ID column ensures that each row is uniquely identified.

In [5]:
gdf = gdf.reset_index(drop=False)

## Filter columns relevant to the project

In [6]:
columns = [
    'id',
    'geometry',
    'name',
    'addr:housenumber',
    'addr:postcode',
    'addr:street',
    'contact:phone',
    'contact:website',
    'indoor',
    'opening_hours',
    'wheelchair',
    'fee',
    'phone',
    'website',
    'email',
    'outdoor',
    'contact:email',
    'climbing:outdoor'
]

bouldering_spots_df = gdf[columns].copy()
bouldering_spots_df.head()

,id,geometry,name,addr:housenumber,addr:postcode,addr:street,contact:phone,contact:website,indoor,opening_hours,wheelchair,fee,phone,website,email,outdoor,contact:email,climbing:outdoor
0,1066131768,POINT (13.26476 52.41394),Boulderfelsen,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1768495247,POINT (13.44855 52.49599),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,3966842994,POINT (13.42867 52.49513),Boulderklub Kreuzberg,38,10999,Ohlauer Straße,+49 30 51302181,http://boulderklubkreuzberg.de,yes,Mo-Fr 07:00-22:00; Sa-Su 09:00-22:00,no,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,3989801753,POINT (13.22107 52.54211),Cliffhanger,NaN,13599,Zitadellenweg,NaN,NaN,yes,Mo-Fr 10:00-22:00; Sa-Su 10:00-21:00,NaN,yes,+49 30 67060160,https://cliffhanger-berlin.de/,NaN,NaN,NaN,NaN
4,4622626832,POINT (13.4516 52.47944),Kinderwald,NaN,NaN,NaN,NaN,NaN,yes,NaN,NaN,yes,NaN,NaN,NaN,NaN,NaN,NaN

### Rename columns

In [7]:
bouldering_spots_df = bouldering_spots_df.rename(columns={
    "addr:housenumber": "house_number",
    "addr:postcode": "postal_code",
    "addr:street": "street"
})

## Map fields to unified names

In this step we prepare the dataset for further processing by standardizing column names and transforming data to match the expected schema.

### Name Column: Add Default

The `name` column contains the name of the bouldering spot. The final dataset requires `unknown_bouldering` for spots without a name.

In [8]:
bouldering_spots_df['name'] = bouldering_spots_df['name'].fillna('unknown_bouldering')

### Combine phone columns

Mappers of OSM either use `phone` or `contact:phone` to store phone numbers.
We combine these columns to ensure that all phone numbers are stored consistently.

The `contact:phone` column is dropped after combining to avoid duplication.

In [9]:
# Combine phone columns, preferring contact:phone, falling back to phone
bouldering_spots_df['phone'] = bouldering_spots_df['contact:phone'].fillna(bouldering_spots_df['phone'])

bouldering_spots_df.drop(columns=['contact:phone'], inplace=True)

###  Combine website columns

Mappers of OSM either use `website` or `contact:website` to store website URLs.
We combine these columns to ensure that all website URLs are stored consistently.

The `contact:website` column is dropped after combining to avoid duplication.

In [10]:
# Combine website columns, preferring contact:website, falling back to website
bouldering_spots_df['website'] = bouldering_spots_df['contact:website'].fillna(bouldering_spots_df['website'])

bouldering_spots_df.drop(columns=['contact:website'], inplace=True)

### Combine email columns

Mappers of OSM either use `email` or `contact:email` to store email addresses.
We combine these columns to ensure that all email addresses are stored consistently.

The `contact:email` column is dropped after combining to avoid duplication.

In [11]:
# Combine email columns, preferring contact:email, falling back to email
bouldering_spots_df['email'] = bouldering_spots_df['contact:email'].fillna(bouldering_spots_df['email'])

bouldering_spots_df.drop(columns=['contact:email'], inplace=True)

### `is_indoor` and `is_outdoor` columns

The `indoor` and `outdoor` columns contain the indoor/outdoor information. Both can be `yes` or `no` independently, because a bouldering spot can be part indoor and/or outdoor.

* Combine `outdoor` and `climbing:outdoor` columns.
* Convert `indoor` and `outdoor` to boolean values (`yes -> True`, else `False`).
* Save boolean values in `is_indoor` and `is_outdoor` columns.
* Drop `indoor`, `outdoor` and `climbing:outdoor` columns.

In [12]:
# Combine outdoor and climbing:outdoor
bouldering_spots_df['outdoor'] = bouldering_spots_df['climbing:outdoor'].fillna(bouldering_spots_df['outdoor'])

# Convert to boolean
bouldering_spots_df['is_indoor'] = bouldering_spots_df['indoor'].str.lower() == 'yes'
bouldering_spots_df['is_outdoor'] = bouldering_spots_df['outdoor'].str.lower() == 'yes'

bouldering_spots_df.drop(columns=['indoor', 'outdoor', 'climbing:outdoor'], inplace=True)

### Pricing columns

The `fee` column contains the only information about pricing for each bouldering spot. It can be either `yes` or `no`.

This results in two possible pricing values:
* `Entry Fee`: The `fee` column contains the value `yes`.
* `NULL`: The `fee` column does not contain the value `yes`.

In [13]:
bouldering_spots_df['pricing'] = bouldering_spots_df['fee'].str.lower().apply(
    lambda fee: 'Entry Fee' if fee == 'yes' else None
)

bouldering_spots_df.drop(columns=['fee'], inplace=True)

### Accessibility column

The `wheelchair` column contains the only accessibility information for each bouldering spot.

This gets mapped onto a new `accessibility` column with the following mapping:
* `yes` -> `Wheelchair accessible`
* `no` -> `Not wheelchair accessible`
* `limited` -> `Limited wheelchair access`
* No value -> `NULL`

In [14]:
accessibility_mapping = {
    'yes': 'Wheelchair accessible',
    'no': 'Not wheelchair accessible',
    'limited': 'Limited wheelchair access',
    '': None
}

bouldering_spots_df['accessibility'] = (
    bouldering_spots_df['wheelchair']
        .fillna('')
        .str.lower()
        .map(accessibility_mapping)
)

bouldering_spots_df = bouldering_spots_df.drop(columns=['wheelchair'])

print("Accessibility mapping completed:")
print(bouldering_spots_df['accessibility'].value_counts())
print(f"\nMissing accessibility info: {bouldering_spots_df['accessibility'].isna().sum()}")

Accessibility mapping completed:
accessibility
Wheelchair accessible        4
Not wheelchair accessible    2
Limited wheelchair access    2
Name: count, dtype: int64

Missing accessibility info: 28

### Data Source column

This column contains the source of the data.

Because the dataset is imported from OpenStreetMap only, we set the value to `OSM` for all entries.

In [15]:
bouldering_spots_df['data_source'] = 'OSM'

## Geocoding

### Extract coordinates

The `geometry` column contains the geometries as POINT() format, using the centroid for POLYGON() and LINESTRING().

Because the geometries are in geographic CRS (EPSG:4326), calculating the centroids directly can be inaccurate.
For accurate results, the geometries should be reprojected to a projected CRS suitable for Berlin (UTM zone 33N -> EPSG:25833) before calculating the centroids.
After the calculation, we can convert the geometries back to WGS84 (EPSG:4326).

In [16]:
bouldering_spots_df.crs

<Geographic 2D CRS: EPSG:4326>
Name: WGS 84
Axis Info [ellipsoidal]:
- Lat[north]: Geodetic latitude (degree)
- Lon[east]: Geodetic longitude (degree)
Area of Use:
- name: World.
- bounds: (-180.0, -90.0, 180.0, 90.0)
Datum: World Geodetic System 1984 ensemble
- Ellipsoid: WGS 84
- Prime Meridian: Greenwich

In [17]:
original_crs = bouldering_spots_df.crs

# Reproject geometries to UTM zone 33N
bouldering_spots_df = bouldering_spots_df.to_crs(epsg=25833)

bouldering_spots_df['geometry'] = bouldering_spots_df['geometry'].centroid

# Convert back to original CRS
bouldering_spots_df = bouldering_spots_df.to_crs(epsg=4326)

**Ensure Point Format:**

In [18]:
print(f"Removing {bouldering_spots_df[bouldering_spots_df.geometry.type != 'Point'].shape[0]} bouldering spots with non-Point geometry.")

bouldering_spots_df = bouldering_spots_df[bouldering_spots_df.geometry.type == "Point"].copy()

Removing 0 bouldering spots with non-Point geometry.

**Extract coordinates:**

In [19]:
bouldering_spots_df['longitude'] = bouldering_spots_df['geometry'].x
bouldering_spots_df['latitude'] = bouldering_spots_df['geometry'].y

In [20]:
bouldering_spots_df.head()

,id,geometry,name,house_number,postal_code,street,opening_hours,phone,website,email,is_indoor,is_outdoor,pricing,accessibility,data_source,longitude,latitude
0,1066131768,POINT (13.26476 52.41394),Boulderfelsen,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,False,None,None,OSM,13.264761,52.413943
1,1768495247,POINT (13.44855 52.49599),unknown_bouldering,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,False,None,None,OSM,13.448546,52.495993
2,3966842994,POINT (13.42867 52.49513),Boulderklub Kreuzberg,38,10999,Ohlauer Straße,Mo-Fr 07:00-22:00; Sa-Su 09:00-22:00,+49 30 51302181,http://boulderklubkreuzberg.de,NaN,True,False,None,Not wheelchair accessible,OSM,13.428675,52.495130
3,3989801753,POINT (13.22107 52.54211),Cliffhanger,NaN,13599,Zitadellenweg,Mo-Fr 10:00-22:00; Sa-Su 10:00-21:00,+49 30 67060160,https://cliffhanger-berlin.de/,NaN,True,False,Entry Fee,None,OSM,13.221067,52.542111
4,4622626832,POINT (13.4516 52.47944),Kinderwald,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True,False,Entry Fee,None,OSM,13.451601,52.479437

### Reverse geocode for full address

In [21]:
geolocator = Nominatim(user_agent="bouldering_spots_address_restoration")

def safe_reverse(lat, lon):
    if pd.isna(lat) or pd.isna(lon):
        return None
    try:
        location = geolocator.reverse(f"{lat}, {lon}", timeout=10)
        time.sleep(1)
        return location.address if location else None
    except:
        return None

bouldering_spots_df['address'] = bouldering_spots_df.apply(
    lambda row: safe_reverse(row['latitude'], row['longitude']),
    axis=1
)

print("Missing full_address values:", bouldering_spots_df['address'].isna().sum())

Missing full_address values: 0

In [22]:
bouldering_spots_df[['address', 'house_number', 'postal_code', 'street']].head()

,address,house_number,postal_code,street
0,"Boulderfelsen, Werner-Sylten-Weg, Telefunkensi...",NaN,NaN,NaN
1,"Heckmannufer, Luisenstadt, Kreuzberg, Friedric...",NaN,NaN,NaN
2,"Boulderklub Kreuzberg, 38, Ohlauer Straße, Rei...",38,10999,Ohlauer Straße
3,"Cliffhanger, Zitadellenweg, Quartier Pulvermüh...",NaN,13599,Zitadellenweg
4,"Kinderwald, 1 Tor 4/2. HH, Thiemannstraße, Har...",NaN,NaN,NaN

## Spatial Join

This step imports the official district and neighborhood geometries used for spatial enrichment. These layers provide the polygon boundaries required to map each bouldering spot to the correct administrative units.

In [23]:
districts = gpd.read_file("../../districts/sources/districts_enhanced.geojson")
neighborhoods = gpd.read_file("../../districts/sources/ortsteile_berlin.geojson")

In [24]:
districts.head()

,district_id,district,geometry
0,12,Reinickendorf,"MULTIPOLYGON (((13.32074 52.6266, 13.32045 52...."
1,04,Charlottenburg-Wilmersdorf,"MULTIPOLYGON (((13.32111 52.52446, 13.32103 52..."
2,09,Treptow-Köpenick,"MULTIPOLYGON (((13.57925 52.39083, 13.57958 52..."
3,03,Pankow,"MULTIPOLYGON (((13.50481 52.6196, 13.50467 52...."
4,08,Neukölln,"MULTIPOLYGON (((13.45832 52.48569, 13.45823 52..."

In [25]:
neighborhoods.head()

,gml_id,spatial_name,spatial_alias,spatial_type,OTEIL,BEZIRK,FLAECHE_HA,geometry
0,re_ortsteil.0101,0101,Mitte,Polygon,Mitte,Mitte,1063.8748,"POLYGON ((13.41649 52.52696, 13.41635 52.52702..."
1,re_ortsteil.0102,0102,Moabit,Polygon,Moabit,Mitte,768.7909,"POLYGON ((13.33884 52.51974, 13.33884 52.51974..."
2,re_ortsteil.0103,0103,Hansaviertel,Polygon,Hansaviertel,Mitte,52.5337,"POLYGON ((13.34322 52.51557, 13.34323 52.51557..."
3,re_ortsteil.0104,0104,Tiergarten,Polygon,Tiergarten,Mitte,516.0672,"POLYGON ((13.36879 52.49878, 13.36891 52.49877..."
4,re_ortsteil.0105,0105,Wedding,Polygon,Wedding,Mitte,919.9112,"POLYGON ((13.34656 52.53879, 13.34664 52.53878..."

### Geospatial validation

This step ensures that all geometries in the dataset are valid and correctly aligned with the required coordinate reference system (CRS).
Clean and predictable geospatial data is essential before performing spatial joins or exporting to the final database.

* **CRS check:** The current coordinate reference system is printed to verify whether the dataset is already in *EPSG:4326*, which is required for mapping and database compatibility.
* **Conditional CRS conversion:** If the dataset uses another CRS, it is converted to *EPSG:4326 (WGS84)* to standardize all latitude and longitude values.
* **Geometry validity:** Geometries are tested using `is_valid` to identify any malformed shapes (e.g., self-intersections). Invalid geometries can cause failures during spatial operations.
* **Duplicate geometries:** Entries with identical geometry values are removed. This prevents duplicated store locations and ensures the final dataset contains one unique spatial point per store.
* **Outcome:** After these checks, the geospatial layer is clean, valid, and ready for any spatial join or database insertion step.

In [26]:
print("Current CRS:", bouldering_spots_df.crs)

Current CRS: EPSG:4326

In [27]:
if bouldering_spots_df.crs != "EPSG:4326":
    bouldering_spots_df = bouldering_spots_df.to_crs(epsg=4326)
    print("CRS converted to EPSG:4326 (WGS 84)")

In [28]:
invalid_geometries = bouldering_spots_df[~bouldering_spots_df.is_valid]
print(f"Invalid geometries found: {len(invalid_geometries)}")

Invalid geometries found: 0

In [29]:
bouldering_spots_df = bouldering_spots_df.drop_duplicates(subset='geometry')

### Assign district and neighborhood

This step attaches administrative context to each bouldering spot by determining which district and neighborhood polygon it falls within.
The result enables consistent linking to the Berlin administrative hierarchy.

* **Neighborhood layer load:** The enhanced neighborhood GeoJSON is loaded, and its columns are printed to verify available attributes for the spatial join.
* **Cleaning join artifacts:** If leftover join-index columns such as `index_right` exist, they are removed to prevent column conflicts in further steps.
* **Spatial join (within):** Each bouldering spot is matched to the neighborhood polygon it lies inside using `gpd.sjoin(..., predicate="within")`. This attaches the corresponding *district* and *neighborhood* names to each store.
* **Column renaming:** Spatial joins create suffixes (`_left` and `_right`). The columns `district_right` and `neighborhood_right` are renamed to clean, final names.
* **Dropping redundant fields:** Any remaining `district_left` or `neighborhood_left` columns are removed to avoid duplication.
* **District ID mapping:** A dictionary maps each district name to its official *district_id* (Berlin’s administrative codes). This ensures compatibility with the existing district table in *test_berlin_data*.
* **Final output:** Each bouldering spot now includes standardized *district*, *neighborhood*, and corresponding *district_id*, enabling relational integrity in the database.

In [30]:
bouldering_spots_df = gpd.sjoin(
    bouldering_spots_df,
    neighborhoods[["BEZIRK", "OTEIL", "gml_id", "geometry"]],
    how="left",
    predicate="within"
)


bouldering_spots_df = bouldering_spots_df.rename(columns={
    "BEZIRK": "district",
    "OTEIL": "neighborhood",
    "gml_id": "neighborhood_id"
})

if "index_right" in bouldering_spots_df.columns:
    bouldering_spots_df = bouldering_spots_df.drop(columns=["index_right"])

In [31]:
bouldering_spots_df["neighborhood_id"] = (
    bouldering_spots_df["neighborhood_id"]
        .astype(str)
        .str.extract(r"(\d{4})")[0]
)

print("neighborhood_id successfully formatted to 4 digits.")

neighborhood_id successfully formatted to 4 digits.

In [32]:
district_mapping = {
    'Mitte': '11001001',
    'Friedrichshain-Kreuzberg': '11002002',
    'Pankow': '11003003',
    'Charlottenburg-Wilmersdorf': '11004004',
    'Spandau': '11005005',
    'Steglitz-Zehlendorf': '11006006',
    'Tempelhof-Schöneberg': '11007007',
    'Neukölln': '11008008',
    'Treptow-Köpenick': '11009009',
    'Marzahn-Hellersdorf': '11010010',
    'Lichtenberg': '11011011',
    'Reinickendorf': '11012012'
}

bouldering_spots_df["district_id"] = bouldering_spots_df["district"].map(district_mapping)

print("District_id mapping completed.")

District_id mapping completed.

In [33]:
bouldering_spots_df.head()

,id,geometry,name,house_number,postal_code,street,opening_hours,phone,website,email,...,pricing,accessibility,data_source,longitude,latitude,address,district,neighborhood,neighborhood_id,district_id
0,1066131768,POINT (13.26476 52.41394),Boulderfelsen,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,None,None,OSM,13.264761,52.413943,"Boulderfelsen, Werner-Sylten-Weg, Telefunkensi...",Steglitz-Zehlendorf,Zehlendorf,0604,11006006
1,1768495247,POINT (13.44855 52.49599),unknown_bouldering,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,None,None,OSM,13.448546,52.495993,"Heckmannufer, Luisenstadt, Kreuzberg, Friedric...",Friedrichshain-Kreuzberg,Kreuzberg,0202,11002002
2,3966842994,POINT (13.42867 52.49513),Boulderklub Kreuzberg,38,10999,Ohlauer Straße,Mo-Fr 07:00-22:00; Sa-Su 09:00-22:00,+49 30 51302181,http://boulderklubkreuzberg.de,NaN,...,None,Not wheelchair accessible,OSM,13.428675,52.495130,"Boulderklub Kreuzberg, 38, Ohlauer Straße, Rei...",Friedrichshain-Kreuzberg,Kreuzberg,0202,11002002
3,3989801753,POINT (13.22107 52.54211),Cliffhanger,NaN,13599,Zitadellenweg,Mo-Fr 10:00-22:00; Sa-Su 10:00-21:00,+49 30 67060160,https://cliffhanger-berlin.de/,NaN,...,Entry Fee,None,OSM,13.221067,52.542111,"Cliffhanger, Zitadellenweg, Quartier Pulvermüh...",Spandau,Haselhorst,0502,11005005
4,4622626832,POINT (13.4516 52.47944),Kinderwald,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,Entry Fee,None,OSM,13.451601,52.479437,"Kinderwald, 1 Tor 4/2. HH, Thiemannstraße, Har...",Neukölln,Neukölln,0801,11008008

## Convert Geometry Column

The `geometry` column contains the geometries as Points. This step converts it to a string in the `POINT()` format for database insertion.

In [ ]:
bouldering_spots_df["geometry"] = bouldering_spots_df.geometry.to_wkt()

## Final Dataset Preparation

In [35]:
bouldering_spots_final = bouldering_spots_df.copy()

cols_in_order = [
    'id',
    'district_id',
    'neighborhood_id',
    'name',
    'latitude',
    'longitude',
    'geometry',
    'neighborhood',
    'district',
    'is_indoor',
    'is_outdoor',
    'address',
    'street',
    'house_number',
    'postal_code',
    'pricing',
    'accessibility',
    'opening_hours',
    'phone',
    'email',
    'website',
    'data_source'
]

bouldering_spots_final = bouldering_spots_final[cols_in_order]

print("Final df shape:", bouldering_spots_final.shape)

Final df shape: (36, 22)

In [36]:
bouldering_spots_final.head()

,id,district_id,neighborhood_id,name,latitude,longitude,geometry,neighborhood,district,is_indoor,...,street,house_number,postal_code,pricing,accessibility,opening_hours,phone,email,website,data_source
0,1066131768,11006006,0604,Boulderfelsen,52.413943,13.264761,POINT (13.264761 52.413943),Zehlendorf,Steglitz-Zehlendorf,False,...,NaN,NaN,NaN,None,None,NaN,NaN,NaN,NaN,OSM
1,1768495247,11002002,0202,unknown_bouldering,52.495993,13.448546,POINT (13.448546 52.495993),Kreuzberg,Friedrichshain-Kreuzberg,False,...,NaN,NaN,NaN,None,None,NaN,NaN,NaN,NaN,OSM
2,3966842994,11002002,0202,Boulderklub Kreuzberg,52.495130,13.428675,POINT (13.428675 52.49513),Kreuzberg,Friedrichshain-Kreuzberg,True,...,Ohlauer Straße,38,10999,None,Not wheelchair accessible,Mo-Fr 07:00-22:00; Sa-Su 09:00-22:00,+49 30 51302181,NaN,http://boulderklubkreuzberg.de,OSM
3,3989801753,11005005,0502,Cliffhanger,52.542111,13.221067,POINT (13.221067 52.542111),Haselhorst,Spandau,True,...,Zitadellenweg,NaN,13599,Entry Fee,None,Mo-Fr 10:00-22:00; Sa-Su 10:00-21:00,+49 30 67060160,NaN,https://cliffhanger-berlin.de/,OSM
4,4622626832,11008008,0801,Kinderwald,52.479437,13.451601,POINT (13.451601 52.479437),Neukölln,Neukölln,True,...,NaN,NaN,NaN,Entry Fee,None,NaN,NaN,NaN,NaN,OSM

## Quality Checks

This step performs the last steps on the enriched dataset to ensure that all data is valid and ready for insertion into the final database.

### Missing values

The number of missing values in *district_id* and *neighborhood* is printed. Any non-zero count indicates that certain stores could not be mapped to an administrative area during spatial joins.

In [37]:
print("Missing values in district_id & neighborhood:")
print(bouldering_spots_final[['district_id', 'neighborhood']].isna().sum())

Missing values in district_id & neighborhood:
district_id     0
neighborhood    0
dtype: int64

### Remove duplicate columns

The command `loc[:, ~columns.duplicated()]` ensures that no duplicate column names remain in the final dataframe.
This is crucial because spatial joins sometimes generate repeated column labels that would break table insertion or violate schema rules.

In [38]:
bouldering_spots_final = bouldering_spots_final.loc[:, ~bouldering_spots_final.columns.duplicated()]

### Final Structure Inspection

The shape (rows × columns) of the final dataframe is printed along with the full list of columns.
This allows a last verification that all necessary fields exist, the column order is correct, and the final dataset matches the expected schema.

In [39]:
print("\nFinal dataframe info:")
print("Shape:", bouldering_spots_final.shape)
print("Columns:", list(bouldering_spots_final.columns))

Final dataframe info:
Shape: (36, 22)
Columns: ['id', 'district_id', 'neighborhood_id', 'name', 'latitude', 'longitude', 'geometry', 'neighborhood', 'district', 'is_indoor', 'is_outdoor', 'address', 'street', 'house_number', 'postal_code', 'pricing', 'accessibility', 'opening_hours', 'phone', 'email', 'website', 'data_source']

The `bouldering_spots_final` dataframe is now clean, non-duplicated, fully validated, and ready for schema creation and insertion into *test_berlin_data*.

## Geospatial Boundary Validation

This check ensures that all store coordinates fall within Berlin’s expected geographic boundaries.

* **Latitude range (52.3 – 52.7):** Rows outside this interval likely represent incorrect coordinates or OSM noise. These entries are displayed for review.

* **Longitude range (13.0 – 13.8):** Although optional, validating longitude helps reveal stores placed far outside the city due to geocoding or source errors.

* **Purpose:** Detect anomalies early and avoid inserting out-of-Bound data into the database, which would break spatial logic or violate validation rules.

In [40]:
lat_range = (52.3, 52.7)
lon_range = (13.0, 13.8)

out_of_bounds_lat = bouldering_spots_final[
    (bouldering_spots_final.latitude < lat_range[0]) | (bouldering_spots_final.latitude > lat_range[1])
]

out_of_bounds_lon = bouldering_spots_final[
    (bouldering_spots_final.longitude < lon_range[0]) | (bouldering_spots_final.longitude > lon_range[1])
]

In [41]:
print("Out-of-bounds latitude rows:")
display(out_of_bounds_lat)

Out-of-bounds latitude rows:

Empty DataFrame
Columns: [id, district_id, neighborhood_id, name, latitude, longitude, geometry, neighborhood, district, is_indoor, is_outdoor, address, street, house_number, postal_code, pricing, accessibility, opening_hours, phone, email, website, data_source]
Index: []

[0 rows x 22 columns]

In [42]:
print("Out-of-bounds longitude rows:")
display(out_of_bounds_lon)

Out-of-bounds longitude rows:

Empty DataFrame
Columns: [id, district_id, neighborhood_id, name, latitude, longitude, geometry, neighborhood, district, is_indoor, is_outdoor, address, street, house_number, postal_code, pricing, accessibility, opening_hours, phone, email, website, data_source]
Index: []

[0 rows x 22 columns]

## Database Upload (test_berlin_data)

The final dataset is uploaded to the *test_berlin_data* schema for further testing and validation.

### Database Connection

In [43]:
#engine = create_engine("postgresql+psycopg2://:@localhost:5433/layereddb")
engine = create_engine("postgresql+psycopg2://neondb_owner:a9Am7Yy5r9_T7h4OF2GN@ep-falling-glitter-a5m0j5gk-pooler.us-east-2.aws.neon.tech:5432/neondb?sslmode=require")

### Reset Target Table

Before inserting the new, cleaned dataset, the existing `bouldering_spots` table in **test_berlin_data** is safely removed.  
This guarantees a clean environment and prevents issues such as duplicate records, schema mismatches, or outdated rows.

* **DROP TABLE IF EXISTS:** Removes the table only if it already exists, preventing execution errors.
* **CASCADE option:** Ensures that any dependent objects (e.g., foreign-key references) are also removed when necessary.
* **Explicit commit:** Confirms the deletion action and synchronizes the state on NeonDB.
* **Purpose:** Guarantees that the following insert operation loads the **fresh** final dataset with the correct schema.

In [44]:
with engine.connect() as conn:
    conn.execute(text("DROP TABLE IF EXISTS test_berlin_data.bouldering_spots CASCADE;"))
    conn.commit()

print("Old bouldering_spots table dropped.")

Old bouldering_spots table dropped.

### Defining the Table Schema

This block creates the `bouldering_spots` table inside the `test_berlin_data` schema.
It provides a clean, explicit structure that matches the transformed dataset and ensures consistent data loading.

* **Explicit CREATE TABLE:** Avoids automatic schema inference and guarantees full control over column types.

* **Primary Key (id):** Ensures each bouldering spot has a unique, stable identifier for analytics and joins.

* **Textual attributes:** Includes spot name, contacts, website, and opening hours.

* **Address & coordinates:** Full address (reverse-geocoded), plus validated GPS coordinates (longitude/latitude).

* **Spatial context:** Human-readable district & neighborhood names, and corresponding *district_id* + *neighborhood_id* fields used in relational joins.

* **Purpose:** Establishes a reliable target table that aligns with the Berlin Data Platform’s geospatial and relational model.

In [45]:
create_table_sql = """
DROP TABLE IF EXISTS test_berlin_data.bouldering_spots CASCADE;

CREATE TABLE test_berlin_data.bouldering_spots (
    id VARCHAR(20) PRIMARY KEY,
    district_id VARCHAR(20) NOT NULL,
    neighborhood_id VARCHAR(20),
    name VARCHAR(200) NOT NULL DEFAULT 'unknown_bouldering',
    latitude DECIMAL(9,6),
    longitude DECIMAL(9,6),
    geometry VARCHAR,
    neighborhood VARCHAR(100),
    district VARCHAR(100),
    is_indoor BOOLEAN,
    is_outdoor BOOLEAN,
    address VARCHAR(500),
    street VARCHAR(200),
    house_number VARCHAR(20),
    postal_code VARCHAR(20),
    pricing VARCHAR(20),
    accessibility VARCHAR(50),
    opening_hours VARCHAR(255),
    phone VARCHAR(100),
    email VARCHAR(255),
    website VARCHAR(255),
    data_source VARCHAR(20),
    CONSTRAINT fk_bouldering_district
        FOREIGN KEY (district_id)
        REFERENCES test_berlin_data.districts(district_id)
        ON DELETE RESTRICT
        ON UPDATE CASCADE
);
"""

### Creating the Table

This step executes the SQL schema definition and creates the final target table `bouldering_spots` inside the `test_berlin_data` schema.

In [46]:
with engine.connect() as conn:
    conn.execute(text(create_table_sql))
    conn.commit()

print("Table bouldering_spots created successfully.")

Table bouldering_spots created successfully.

### Insert into NeonDB

The final dataset is inserted into the `bouldering_spots` table using the `pandas.DataFrame.to_sql()` method.

* `index=False`: Ensures the notebook index is not inserted as a column.

In [47]:
bouldering_spots_final.to_sql(
    "bouldering_spots",
    con=engine,
    schema="test_berlin_data",
    if_exists="append",
    index=False
)

print("Data inserted successfully!")

Data inserted successfully!

### Row Count Validation

The final table must contain the same number of rows as the original dataset.
This ensures that all data was successfully transformed and loaded into the target database.

In [48]:
table_rows = pd.read_sql(f"SELECT COUNT(*) FROM test_berlin_data.bouldering_spots;", engine)

print(f"Original DataFrame: {bouldering_spots_df.shape[0]} rows")
print(f"Final Table: {table_rows.iloc[0]['count']} rows")

Original DataFrame: 36 rows
Final Table: 36 rows

## Final Export and Summary

This section generates the final deliverable of the pipeline (`bouldering_spots_final.csv`) and summarizes the entire process.

### CSV Export

* Exporting the cleaned DataFrame to a CSV file for production use.

In [49]:
bouldering_spots_final.to_csv("bouldering_spots_final.csv", index=False)

### Final Table Schema

| Column Name       | Data Type                                            | Description                                                                                                           |
|-------------------|------------------------------------------------------|-----------------------------------------------------------------------------------------------------------------------|
| `id`              | `VARCHAR(20) NOT NULL`                               | Unique identifier for each bouldering spot (inherited OSM ID)                                                         |
| `district_id`     | `VARCHAR(20) NOT NULL`                               | ID of the district, foreign key to `districts(district_id)`                                                           |
| `neighborhood_id` | `VARCHAR(20)`                                        | ID of the neighborhood                                                                                                |
| `name`            | `VARCHAR(200) NOT NULL DEFAULT 'unknown_bouldering'` | Name of the bouldering spot, `unknown_bouldering` if missing                                                          |
| `latitude`        | `NUMERIC(9, 6)`                                      | Latitude                                                                                                              |
| `longitude`       | `NUMERIC(9, 6)`                                      | Longitude                                                                                                             |
| `geometry`        | `VARCHAR`                                            | Location of the spot in WKT `POINT()` format                                                                          |
| `neighborhood`    | `VARCHAR(100)`                                       | Name of the neighborhood the spot is in                                                                               |
| `district`        | `VARCHAR(100)`                                       | Name of the district the spot is in                                                                                   |
| `is_indoor`       | `BOOLEAN`                                            | Flag where `TRUE` means the spot has an indoor area                                                                   |
| `is_outdoor`      | `BOOLEAN`                                            | Flag where `TRUE` means the spot has an outdoor area                                                                  |
| `address`         | `VARCHAR(500)`                                       | Reverse geocoded address of the spot, derived from the coordinates                                                    |
| `street`          | `VARCHAR(200)`                                       | Street the spot is in                                                                                                 |
| `house_number`    | `VARCHAR(20)`                                        | House number of the spot                                                                                              |
| `postal_code`     | `VARCHAR(20)`                                        | Postal code of the spot                                                                                               |
| `pricing`         | `VARCHAR(20)`                                        | Pricing model for the spot. Currently only `Entry Fee` or `Unknown`                                                   |
| `accessibility`   | `VARCHAR(50)`                                        | Accessibility of the spot (`Wheelchair accessible`, `Not wheelchair accessible`, `Limited wheelchair access`, `NULL`) |
| `opening_hours`   | `VARCHAR(255)`                                       | Opening hours                                                                                                         |
| `phone`           | `VARCHAR(100)`                                       | Phone number if available                                                                                             |
| `email`           | `VARCHAR(255)`                                       | Mail address if available                                                                                             |
| `website`         | `VARCHAR(255)`                                       | Website URL if available                                                                                              |
| `data_source`     | `VARCHAR(20)`                                        | Source of the data entry (currently only `OSM`)                                                                       |