In [1]:
%pip install osmnx geopandas pandas
%pip install psycopg2-binary
%pip install sqlalchemy

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: osmnx in /Users/peter/Library/Python/3.9/lib/python/site-packages (2.0.7)
Requirement already satisfied: geopandas in /Users/peter/Library/Python/3.9/lib/python/site-packages (1.0.1)
Requirement already satisfied: pandas in /Users/peter/Library/Python/3.9/lib/python/site-packages (2.3.3)
Requirement already satisfied: requests>=2.27 in /Users/peter/Library/Python/3.9/lib/python/site-packages (from osmnx) (2.32.5)
Requirement already satisfied: numpy>=1.22 in /Users/peter/Library/Python/3.9/lib/python/site-packages (from osmnx) (2.0.2)
Requirement already satisfied: networkx>=2.5 in /Users/peter/Library/Python/3.9/lib/python/site-packages (from osmnx) (3.2.1)
Requirement already satisfied: shapely>=2.0 in /Users/peter/Library/Python/3.9/lib/python/site-packages (from osmnx) (2.0.7)
Requirement already satisfied: pyproj>=3.3.0 in /Users/peter/Library/Python/3.9/lib/python/site-packages (from geopandas) (3.6.1)
Requirement already satisfied: pyogrio>=0.7.2 in /Users/peter/Library/Python/3.9/lib/python/site-packages (from geopandas) (0.11.1)
Requirement already satisfied: packaging in /Users/peter/Library/Python/3.9/lib/python/site-packages (from geopandas) (25.0)
Requirement already satisfied: pytz>=2020.1 in /Users/peter/Library/Python/3.9/lib/python/site-packages (from pandas) (2025.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /Users/peter/Library/Python/3.9/lib/python/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata>=2022.7 in /Users/peter/Library/Python/3.9/lib/python/site-packages (from pandas) (2025.3)
Requirement already satisfied: certifi in /Users/peter/Library/Python/3.9/lib/python/site-packages (from pyogrio>=0.7.2->geopandas) (2026.1.4)
Requirement already satisfied: six>=1.5 in /Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/site-packages (from python-dateutil>=2.8.2->pandas) (1.15.0)
Requirement already satisfied: idna<4,>=2.5 in /Users/peter/Library/Python/3.9/lib/python/site-packages (from requests>=2.27->osmnx) (3.11)
Requirement already satisfied: charset_normalizer<4,>=2 in /Users/peter/Library/Python/3.9/lib/python/site-packages (from requests>=2.27->osmnx) (3.4.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in /Users/peter/Library/Python/3.9/lib/python/site-packages (from requests>=2.27->osmnx) (2.6.3)
WARNING: You are using pip version 21.2.4; however, version 26.0 is available.
You should consider upgrading via the '/Library/Developer/CommandLineTools/usr/bin/python3 -m pip install --upgrade pip' command.
Note: you may need to restart the kernel to use updated packages.
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: psycopg2-binary in /Users/peter/Library/Python/3.9/lib/python/site-packages (2.9.11)
WARNING: You are using pip version 21.2.4; however, version 26.0 is available.
You should consider upgrading via the '/Library/Developer/CommandLineTools/usr/bin/python3 -m pip install --upgrade pip' command.
Note: you may need to restart the kernel to use updated packages.
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: sqlalchemy in /Users/peter/Library/Python/3.9/lib/python/site-packages (2.0.46)
Requirement already satisfied: typing-extensions>=4.6.0 in /Users/peter/Library/Python/3.9/lib/python/site-packages (from sqlalchemy) (4.15.0)
WARNING: You are using pip version 21.2.4; however, version 26.0 is available.
You should consider upgrading via the '/Library/Developer/CommandLineTools/usr/bin/python3 -m pip install --upgrade pip' command.
Note: you may need to restart the kernel to use updated packages.

In [2]:
import psycopg2
import pandas as pd
from sqlalchemy import create_engine, text
import warnings

warnings.filterwarnings("ignore")

# Conection
host = 'localhost'
port = '5433'
database = 'layereddb'
schema='berlin_source_data'
user_name='-------'
password='++++++++++'

#connection to db after you opened tunnel
engine = create_engine(f'postgresql+psycopg2://{user_name}:{password}@{host}:{port}/{database}')

In [3]:
# Conection
host = 'localhost'
port = '5433'
database = 'layereddb'
schema='berlin_source_data'
user_name='peter_finger'
password='tY3uG1hM8vD6fP5sL'

#connection to db after you opened tunnel
engine = create_engine(f'postgresql+psycopg2://{user_name}:{password}@{host}:{port}/{database}')

In [4]:
# import libraries
import osmnx as ox
import geopandas as gpd
import pandas as pd

In [5]:
##let's query test data!
query = f"""
SELECT * from berlin_source_data.districts
"""

# Execute the query
with engine.connect() as conn:
    df= pd.read_sql(text(query), conn)
    conn.commit()  # commit the transaction
df

,district_id,district,geometry
0,11001001,Mitte,0106000020E610000001000000010300000001000000F3...
1,11002002,Friedrichshain-Kreuzberg,0106000020E610000001000000010300000001000000C5...
2,11003003,Pankow,0106000020E61000000400000001030000000100000012...
3,11004004,Charlottenburg-Wilmersdorf,0106000020E6100000010000000103000000010000000D...
4,11005005,Spandau,0106000020E6100000010000000103000000010000001D...
5,11009009,Treptow-Köpenick,0106000020E610000001000000010300000001000000E9...
6,11006006,Steglitz-Zehlendorf,0106000020E6100000010000000103000000010000008A...
7,11007007,Tempelhof-Schöneberg,0106000020E61000000100000001030000000100000057...
8,11010010,Marzahn-Hellersdorf,0106000020E6100000010000000103000000010000005A...
9,11008008,Neukölln,0106000020E610000001000000010300000001000000BF...
10,11011011,Lichtenberg,0106000020E61000000100000001030000000100000038...
11,11012012,Reinickendorf,0106000020E61000000100000001030000000100000084...

In [6]:
tags = {"amenity": "atm"}

In [7]:
# ✅ Enables caching: Speeds up repeated queries
# 🖥 Logs details to the console (helpful for debugging)
ox.settings.use_cache = True
ox.settings.log_console = True

In [8]:
# Fetch Atms from Berlin from OSM using the tag "amenity=atm"
atm = ox.features.features_from_place("Berlin, Germany", tags=tags)

In [9]:
# Display basic info

print(f"Number of atms entries fetched: {len(atm)}")
atm.head(10)

Number of atms entries fetched: 1062

                                    geometry amenity               brand  \
element id
node    60852951   POINT (13.46562 52.52467)     atm  Berliner Volksbank
        78252154   POINT (13.39863 52.52374)     atm                 NaN
        87036263   POINT (13.38428 52.53299)     atm  Sparda-Bank Berlin
        213106623  POINT (13.44114 52.54217)     atm                 NaN
        239694634   POINT (13.52164 52.4975)     atm  Berliner Volksbank
        253624651  POINT (13.45327 52.51221)     atm                 NaN
        266622701  POINT (13.61195 52.51232)     atm            Cashzone
        269111123   POINT (13.24074 52.6181)     atm  Berliner Volksbank
        269478773  POINT (13.53549 52.43319)     atm                 NaN
        280543616  POINT (13.35151 52.43963)     atm                 ING

                  brand:wikidata               brand:wikipedia cash_in  \
element id
node    60852951         Q821855         de:Berliner Volksbank      no
        78252154             NaN                           NaN      no
        87036263        Q1656189  de:Sparda-Bank (Deutschland)     yes
        213106623            NaN                           NaN     yes
        239694634        Q821855         de:Berliner Volksbank      no
        253624651            NaN                           NaN      no
        266622701     Q110738461                           NaN      no
        269111123        Q821855                           NaN      no
        269478773            NaN                           NaN     yes
        280543616        Q645708                  en:ING Group      no

                   check_date indoor opening_hours                   operator  \
element id
node    60852951   2025-01-08     no          24/7         Berliner Volksbank
        78252154   2024-02-22    NaN           NaN  Bank für Sozialwirtschaft
        87036263   2025-07-27    yes   06:00-23:00         Sparda-Bank Berlin
        213106623  2025-11-08    yes           NaN                  Sparkasse
        239694634  2023-12-20    NaN           NaN         Berliner Volksbank
        253624651  2025-11-19    yes          24/7         Berliner Sparkasse
        266622701  2024-12-21    yes          24/7                  Cardpoint
        269111123         NaN    yes          24/7         Berliner Volksbank
        269478773  2025-05-23    yes           NaN         Berliner Sparkasse
        280543616         NaN     no           NaN                        ING

                   ... wikidata comment stamps vending  url self_service  \
element id         ...
node    60852951   ...      NaN     NaN    NaN     NaN  NaN          NaN
        78252154   ...      NaN     NaN    NaN     NaN  NaN          NaN
        87036263   ...      NaN     NaN    NaN     NaN  NaN          NaN
        213106623  ...      NaN     NaN    NaN     NaN  NaN          NaN
        239694634  ...      NaN     NaN    NaN     NaN  NaN          NaN
        253624651  ...      NaN     NaN    NaN     NaN  NaN          NaN
        266622701  ...      NaN     NaN    NaN     NaN  NaN          NaN
        269111123  ...      NaN     NaN    NaN     NaN  NaN          NaN
        269478773  ...      NaN     NaN    NaN     NaN  NaN          NaN
        280543616  ...      NaN     NaN    NaN     NaN  NaN          NaN

                  manufacturer image description:de room
element id
node    60852951           NaN   NaN            NaN  NaN
        78252154           NaN   NaN            NaN  NaN
        87036263           NaN   NaN            NaN  NaN
        213106623          NaN   NaN            NaN  NaN
        239694634          NaN   NaN            NaN  NaN
        253624651          NaN   NaN            NaN  NaN
        266622701          NaN   NaN            NaN  NaN
        269111123          NaN   NaN            NaN  NaN
        269478773          NaN   NaN            NaN  NaN
        280543616          NaN   NaN            NaN  NaN

[10 rows x 78 columns]

In [10]:
atm.info()

<class 'geopandas.geodataframe.GeoDataFrame'>
MultiIndex: 1062 entries, ('node', np.int64(60852951)) to ('way', np.int64(502703971))
Data columns (total 78 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   geometry                  1062 non-null   geometry
 1   amenity                   1062 non-null   object
 2   brand                     632 non-null    object
 3   brand:wikidata            578 non-null    object
 4   brand:wikipedia           388 non-null    object
 5   cash_in                   783 non-null    object
 6   check_date                729 non-null    object
 7   indoor                    474 non-null    object
 8   opening_hours             349 non-null    object
 9   operator                  968 non-null    object
 10  operator:wikidata         578 non-null    object
 11  wheelchair                521 non-null    object
 12  addr:city                 63 non-null     object
 13  addr:country              52 non-null     object
 14  addr:housenumber          109 non-null    object
 15  addr:postcode             60 non-null     object
 16  addr:street               113 non-null    object
 17  addr:suburb               39 non-null     object
 18  name                      447 non-null    object
 19  drive_through             188 non-null    object
 20  operator:wikipedia        390 non-null    object
 21  description               20 non-null     object
 22  surveillance              6 non-null      object
 23  atm                       1 non-null      object
 24  bic                       2 non-null      object
 25  level                     189 non-null    object
 26  addr:inclusion            1 non-null      object
 27  fee                       30 non-null     object
 28  currency:EUR              144 non-null    object
 29  website                   9 non-null      object
 30  branch                    3 non-null      object
 31  wheelchair:description    7 non-null      object
 32  source                    83 non-null     object
 33  addr:floor                38 non-null     object
 34  network                   82 non-null     object
 35  note                      21 non-null     object
 36  ref                       48 non-null     object
 37  support                   37 non-null     object
 38  network:wikidata          8 non-null      object
 39  fixme                     4 non-null      object
 40  automatic_door            1 non-null      object
 41  door                      1 non-null      object
 42  toilets:wheelchair        8 non-null      object
 43  covered                   74 non-null     object
 44  layer                     9 non-null      object
 45  contact:website           7 non-null      object
 46  name:ja                   3 non-null      object
 47  finance                   4 non-null      object
 48  lit                       23 non-null     object
 49  created_by                1 non-null      object
 50  contact:phone             4 non-null      object
 51  changing_table            1 non-null      object
 52  check_date:opening_hours  2 non-null      object
 53  opening_hours:signed      1 non-null      object
 54  organic                   1 non-null      object
 55  shop                      1 non-null      object
 56  location                  2 non-null      object
 57  phone                     4 non-null      object
 58  name:fa                   1 non-null      object
 59  atm:operator              1 non-null      object
 60  notice                    2 non-null      object
 61  colour                    1 non-null      object
 62  capacity                  1 non-null      object
 63  operator:signed           1 non-null      object
 64  currency:others           1 non-null      object
 65  mapillary                 1 non-null      object
 66  speech_output             1 non-null      object
 67  speech_output:de          1 non-null      object
 68  wikidata                  1 non-null      object
 69  comment                   1 non-null      object
 70  stamps                    1 non-null      object
 71  vending                   1 non-null      object
 72  url                       1 non-null      object
 73  self_service              1 non-null      object
 74  manufacturer              1 non-null      object
 75  image                     1 non-null      object
 76  description:de            1 non-null      object
 77  room                      1 non-null      object
dtypes: geometry(1), object(77)
memory usage: 691.3+ KB

In [11]:
print("Unique values in column:")
print(atm['operator'].value_counts(dropna=False).head(20))

Unique values in column:
operator
Euronet                  423
NaN                       94
Berliner Sparkasse        91
Berliner Volksbank        65
Postbank                  38
Sparkasse                 27
Euronet Worldwide         22
Bankhaus August Lenz      21
Cashzone                  20
Reisebank                 18
IC Cash Services GmbH     16
ING                       14
ICCash Services           14
ICCash                    13
Berliner Volksbank eG     11
cashzone                  10
Bankhaus Lenz              8
Deutsche Bank              7
Sparda-Bank Berlin         6
Cardpoint                  6
Name: count, dtype: int64

In [12]:
print("Unique values in column:")
print(atm['brand'].value_counts(dropna=False).head(20))

Unique values in column:
brand
NaN                   430
Euronet               412
Berliner Volksbank     65
Postbank               36
Reisebank              17
ING                    14
Berliner Sparkasse     11
Volksbank              10
Cashzone                9
Sparkasse               9
Deutsche Bank           6
Sparda-Bank Berlin      6
Commerzbank             5
Cash Zone               3
ICCash                  2
cash zone               2
IC Cash                 2
ec cash                 2
NCR                     2
HypoVereinsbank         2
Name: count, dtype: int64

In [13]:
print("Unique values in column:")
print(atm['name'].value_counts(dropna=False).head(20))

Unique values in column:
name
NaN                              615
Euronet                          278
Berliner Volksbank                47
Postbank                          24
Reisebank                         14
Sparkasse                         13
Berliner Sparkasse                 9
Cashzone                           5
Commerzbank                        5
ING                                4
Bankhaus August Lenz               3
Sparda-Bank                        3
EC Automat                         2
Sparkasse Berlin                   2
S SB-Service                       2
CashZone                           2
Berliner Sparkasse SB-Service      2
Sparkasse SB Service               2
Santander                          2
Sparkasse SB-Service               2
Name: count, dtype: int64

In [14]:
# filter columns that relevant to project
columns = [
    "Id", "name", "operator","addr:street", "addr:housenumber", "addr:postcode",
    "addr:city", "drive_through","indoor","opening_hours","fee", "brand", "type","geometry", "wheelchair","contact:email"

]
atm_table = atm[[col for col in columns if col in atm.columns]].copy()

In [15]:
# Extract Latitude and Longitude
atm_table['geometry'] = atm_table['geometry'].apply(lambda geom: geom if geom.geom_type == 'Point' else geom.representative_point())
#Extract latitude and longitude

atm_table["latitude"] = atm.geometry.centroid.y
atm_table["longitude"] = atm.geometry.centroid.x

In [16]:
atm_table=atm_table.reset_index()

In [17]:
atm_table.info()

<class 'geopandas.geodataframe.GeoDataFrame'>
RangeIndex: 1062 entries, 0 to 1061
Data columns (total 17 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   element           1062 non-null   object
 1   id                1062 non-null   int64
 2   name              447 non-null    object
 3   operator          968 non-null    object
 4   addr:street       113 non-null    object
 5   addr:housenumber  109 non-null    object
 6   addr:postcode     60 non-null     object
 7   addr:city         63 non-null     object
 8   drive_through     188 non-null    object
 9   indoor            474 non-null    object
 10  opening_hours     349 non-null    object
 11  fee               30 non-null     object
 12  brand             632 non-null    object
 13  geometry          1062 non-null   geometry
 14  wheelchair        521 non-null    object
 15  latitude          1062 non-null   float64
 16  longitude         1062 non-null   float64
dtypes: float64(2), geometry(1), int64(1), object(13)
memory usage: 141.2+ KB

In [18]:
atm_table = atm_table.rename(columns={
    "addr:street": "street",
    "addr:housenumber": "housenumber",
    "addr:postcode": "postcode",
    "addr:city": "city"
    })

In [19]:
atm_table.info()

<class 'geopandas.geodataframe.GeoDataFrame'>
RangeIndex: 1062 entries, 0 to 1061
Data columns (total 17 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   element        1062 non-null   object
 1   id             1062 non-null   int64
 2   name           447 non-null    object
 3   operator       968 non-null    object
 4   street         113 non-null    object
 5   housenumber    109 non-null    object
 6   postcode       60 non-null     object
 7   city           63 non-null     object
 8   drive_through  188 non-null    object
 9   indoor         474 non-null    object
 10  opening_hours  349 non-null    object
 11  fee            30 non-null     object
 12  brand          632 non-null    object
 13  geometry       1062 non-null   geometry
 14  wheelchair     521 non-null    object
 15  latitude       1062 non-null   float64
 16  longitude      1062 non-null   float64
dtypes: float64(2), geometry(1), int64(1), object(13)
memory usage: 141.2+ KB

In [20]:
atm['support'].value_counts()

support
wall      27
ground    10
Name: count, dtype: int64

In [21]:
# Create 'atm_type' based on 'drive_through' and 'indoor'
atm_table['atm_type'] = 'standalone'

# Check if 'drive_through' column exists before using it
if 'drive_through' in atm_table.columns:
    atm_table.loc[atm_table['drive_through'] == 'yes', 'atm_type'] = 'drive-through'
else:
    print("Warning: 'drive_through' column not found in atm_table. Cannot assign 'drive-through' ATM types.")

# Check if 'indoor' column exists before using it
if 'indoor' in atm_table.columns:
    atm_table.loc[atm_table['indoor'] == 'yes', 'atm_type'] = 'indoor'
else:
    print("Warning: 'indoor' column not found in atm_table. Cannot assign 'indoor' ATM types.")


# Display the value counts for the new 'atm_type' column
print("Value counts for 'atm_type' column:")
print(atm_table['atm_type'].value_counts())

# Drop the original 'drive_through' and 'indoor' columns if they exist
if 'drive_through' in atm_table.columns:
    atm_table = atm_table.drop(columns=['drive_through'])
if 'indoor' in atm_table.columns:
    atm_table = atm_table.drop(columns=['indoor'])

# Display the first few rows and info of the updated DataFrame
atm_table.head()

Value counts for 'atm_type' column:
atm_type
standalone    879
indoor        183
Name: count, dtype: int64

,element,id,name,operator,street,housenumber,postcode,city,opening_hours,fee,brand,geometry,wheelchair,latitude,longitude,atm_type
0,node,60852951,NaN,Berliner Volksbank,NaN,NaN,NaN,NaN,24/7,NaN,Berliner Volksbank,POINT (13.46562 52.52467),yes,52.524670,13.465618,standalone
1,node,78252154,Bank für Sozialwirtschaft,Bank für Sozialwirtschaft,Oranienburger Straße,13,10178,Berlin,NaN,NaN,NaN,POINT (13.39863 52.52374),yes,52.523744,13.398627,standalone
2,node,87036263,Sparda-Bank,Sparda-Bank Berlin,NaN,NaN,NaN,NaN,06:00-23:00,NaN,Sparda-Bank Berlin,POINT (13.38428 52.53299),yes,52.532985,13.384282,indoor
3,node,213106623,NaN,Sparkasse,Greifswalder Straße,87-88,NaN,NaN,NaN,NaN,NaN,POINT (13.44114 52.54217),yes,52.542170,13.441137,indoor
4,node,239694634,Berliner Volksbank,Berliner Volksbank,NaN,NaN,NaN,NaN,NaN,NaN,Berliner Volksbank,POINT (13.52164 52.4975),yes,52.497501,13.521643,standalone

In [22]:
# Map 'wheelchair' values to a standardized 'accessibility' column
atm_table['accessibility'] = atm_table['wheelchair'].map({
    'yes': 'accessible',
    'no': 'not accessible',
    'limited': 'partially accessible'
})#.fillna('unknown') # Fill any NaN values with 'unknown'

# Drop the original 'wheelchair' column as it's been transformed
atm_table = atm_table.drop(columns=['wheelchair'])

print(atm_table['accessibility'].value_counts())

accessibility
accessible              290
not accessible          161
partially accessible     70
Name: count, dtype: int64

In [23]:
atm_table.info()

<class 'geopandas.geodataframe.GeoDataFrame'>
RangeIndex: 1062 entries, 0 to 1061
Data columns (total 16 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   element        1062 non-null   object
 1   id             1062 non-null   int64
 2   name           447 non-null    object
 3   operator       968 non-null    object
 4   street         113 non-null    object
 5   housenumber    109 non-null    object
 6   postcode       60 non-null     object
 7   city           63 non-null     object
 8   opening_hours  349 non-null    object
 9   fee            30 non-null     object
 10  brand          632 non-null    object
 11  geometry       1062 non-null   geometry
 12  latitude       1062 non-null   float64
 13  longitude      1062 non-null   float64
 14  atm_type       1062 non-null   object
 15  accessibility  521 non-null    object
dtypes: float64(2), geometry(1), int64(1), object(12)
memory usage: 132.9+ KB

In [24]:
print("Unique values in 'brand' column:")
print(atm_table['brand'].value_counts(dropna=False).head(20))

Unique values in 'brand' column:
brand
NaN                   430
Euronet               412
Berliner Volksbank     65
Postbank               36
Reisebank              17
ING                    14
Berliner Sparkasse     11
Volksbank              10
Cashzone                9
Sparkasse               9
Deutsche Bank           6
Sparda-Bank Berlin      6
Commerzbank             5
Cash Zone               3
ICCash                  2
cash zone               2
IC Cash                 2
ec cash                 2
NCR                     2
HypoVereinsbank         2
Name: count, dtype: int64

In [25]:
print("Unique values in 'operator' column:")
print(atm_table['operator'].value_counts(dropna=False).head(20))

Unique values in 'operator' column:
operator
Euronet                  423
NaN                       94
Berliner Sparkasse        91
Berliner Volksbank        65
Postbank                  38
Sparkasse                 27
Euronet Worldwide         22
Bankhaus August Lenz      21
Cashzone                  20
Reisebank                 18
IC Cash Services GmbH     16
ING                       14
ICCash Services           14
ICCash                    13
Berliner Volksbank eG     11
cashzone                  10
Bankhaus Lenz              8
Deutsche Bank              7
Sparda-Bank Berlin         6
Cardpoint                  6
Name: count, dtype: int64

In [26]:
atm_table.info()

<class 'geopandas.geodataframe.GeoDataFrame'>
RangeIndex: 1062 entries, 0 to 1061
Data columns (total 16 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   element        1062 non-null   object
 1   id             1062 non-null   int64
 2   name           447 non-null    object
 3   operator       968 non-null    object
 4   street         113 non-null    object
 5   housenumber    109 non-null    object
 6   postcode       60 non-null     object
 7   city           63 non-null     object
 8   opening_hours  349 non-null    object
 9   fee            30 non-null     object
 10  brand          632 non-null    object
 11  geometry       1062 non-null   geometry
 12  latitude       1062 non-null   float64
 13  longitude      1062 non-null   float64
 14  atm_type       1062 non-null   object
 15  accessibility  521 non-null    object
dtypes: float64(2), geometry(1), int64(1), object(12)
memory usage: 132.9+ KB

In [27]:
print(atm_table.columns.tolist())

['element', 'id', 'name', 'operator', 'street', 'housenumber', 'postcode', 'city', 'opening_hours', 'fee', 'brand', 'geometry', 'latitude', 'longitude', 'atm_type', 'accessibility']

In [28]:
atm_table.head(20)

,element,id,name,operator,street,housenumber,postcode,city,opening_hours,fee,brand,geometry,latitude,longitude,atm_type,accessibility
0,node,60852951,NaN,Berliner Volksbank,NaN,NaN,NaN,NaN,24/7,NaN,Berliner Volksbank,POINT (13.46562 52.52467),52.524670,13.465618,standalone,accessible
1,node,78252154,Bank für Sozialwirtschaft,Bank für Sozialwirtschaft,Oranienburger Straße,13,10178,Berlin,NaN,NaN,NaN,POINT (13.39863 52.52374),52.523744,13.398627,standalone,accessible
2,node,87036263,Sparda-Bank,Sparda-Bank Berlin,NaN,NaN,NaN,NaN,06:00-23:00,NaN,Sparda-Bank Berlin,POINT (13.38428 52.53299),52.532985,13.384282,indoor,accessible
3,node,213106623,NaN,Sparkasse,Greifswalder Straße,87-88,NaN,NaN,NaN,NaN,NaN,POINT (13.44114 52.54217),52.542170,13.441137,indoor,accessible
4,node,239694634,Berliner Volksbank,Berliner Volksbank,NaN,NaN,NaN,NaN,NaN,NaN,Berliner Volksbank,POINT (13.52164 52.4975),52.497501,13.521643,standalone,accessible
5,node,253624651,Berliner Sparkasse,Berliner Sparkasse,Grünberger Straße,34,10245,Berlin,24/7,NaN,NaN,POINT (13.45327 52.51221),52.512209,13.453270,indoor,not accessible
6,node,266622701,NaN,Cardpoint,NaN,NaN,NaN,NaN,24/7,yes,Cashzone,POINT (13.61195 52.51232),52.512321,13.611950,indoor,accessible
7,node,269111123,NaN,Berliner Volksbank,NaN,NaN,NaN,NaN,24/7,NaN,Berliner Volksbank,POINT (13.24074 52.6181),52.618099,13.240736,indoor,accessible
8,node,269478773,NaN,Berliner Sparkasse,NaN,NaN,NaN,NaN,NaN,NaN,NaN,POINT (13.53549 52.43319),52.433187,13.535490,indoor,NaN
9,node,280543616,NaN,ING,NaN,NaN,NaN,NaN,NaN,NaN,ING,POINT (13.35151 52.43963),52.439629,13.351512,standalone,NaN
10,node,282420329,Sparkasse,Berliner Sparkasse,NaN,NaN,NaN,NaN,NaN,NaN,NaN,POINT (13.45619 52.5104),52.510403,13.456186,standalone,partially accessible
11,node,283287153,Berliner Sparkasse,Berliner Sparkasse,NaN,NaN,NaN,NaN,NaN,NaN,NaN,POINT (13.28561 52.58467),52.584669,13.285612,indoor,accessible
12,node,287297011,Sparkasse,Landesbank Berlin,Stralauer Allee,18,10245,Berlin,24/7,NaN,NaN,POINT (13.46213 52.49836),52.498361,13.462131,indoor,accessible
13,node,287970705,NaN,Berliner Sparkasse,NaN,NaN,NaN,NaN,NaN,NaN,NaN,POINT (13.4446 52.56447),52.564474,13.444604,indoor,accessible
14,node,290670855,Berliner Sparkasse,Sparkasse Berlin,NaN,NaN,NaN,NaN,24/7,NaN,NaN,POINT (13.19928 52.53526),52.535258,13.199282,indoor,accessible
15,node,308019533,Berliner Sparkasse,Landesbank Berlin,Alfred-Kowalke-Straße,NaN,NaN,Berlin,24/7,NaN,NaN,POINT (13.51494 52.50541),52.505414,13.514936,standalone,partially accessible
16,node,313220249,NaN,Berliner Sparkasse,NaN,NaN,NaN,NaN,NaN,NaN,Berliner Sparkasse,POINT (13.32797 52.46498),52.464984,13.327969,standalone,accessible
17,node,318802659,NaN,Berliner Volksbank,Danziger Straße,4,NaN,NaN,24/7,NaN,Berliner Volksbank,POINT (13.413 52.54081),52.540805,13.413004,standalone,partially accessible
18,node,322565365,Berliner Volksbank,Berliner Volksbank,NaN,NaN,NaN,NaN,06:00-22:00,NaN,Berliner Volksbank,POINT (13.41087 52.52193),52.521926,13.410867,standalone,partially accessible
19,node,333445280,NaN,Berliner Volksbank eG,Hermannstraße,63,NaN,NaN,24/7,NaN,Volksbank,POINT (13.42675 52.47564),52.475643,13.426748,standalone,partially accessible

In [29]:
print('filtered dataset shape:', atm_table.shape)
atm_table.info()

filtered dataset shape: (1062, 16)
<class 'geopandas.geodataframe.GeoDataFrame'>
RangeIndex: 1062 entries, 0 to 1061
Data columns (total 16 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   element        1062 non-null   object
 1   id             1062 non-null   int64
 2   name           447 non-null    object
 3   operator       968 non-null    object
 4   street         113 non-null    object
 5   housenumber    109 non-null    object
 6   postcode       60 non-null     object
 7   city           63 non-null     object
 8   opening_hours  349 non-null    object
 9   fee            30 non-null     object
 10  brand          632 non-null    object
 11  geometry       1062 non-null   geometry
 12  latitude       1062 non-null   float64
 13  longitude      1062 non-null   float64
 14  atm_type       1062 non-null   object
 15  accessibility  521 non-null    object
dtypes: float64(2), geometry(1), int64(1), object(12)
memory usage: 132.9+ KB

In [30]:
atm_table['accessibility'].value_counts()

accessibility
accessible              290
not accessible          161
partially accessible     70
Name: count, dtype: int64

In [31]:
# Install geopy for reverse geocoding if not already installed
%pip install geopy

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: geopy in /Users/peter/Library/Python/3.9/lib/python/site-packages (2.4.1)
Requirement already satisfied: geographiclib<3,>=1.52 in /Users/peter/Library/Python/3.9/lib/python/site-packages (from geopy) (2.1)
WARNING: You are using pip version 21.2.4; however, version 26.0 is available.
You should consider upgrading via the '/Library/Developer/CommandLineTools/usr/bin/python3 -m pip install --upgrade pip' command.
Note: you may need to restart the kernel to use updated packages.

In [32]:
from geopy.geocoders import Nominatim
from geopy.exc import GeocoderTimedOut, GeocoderServiceError
import numpy as np
import time

geolocator = Nominatim(user_agent="geoapi_atm_locator",timeout=10)

def reverse_geocode_address(row):
    if pd.isna(row['street']) or pd.isna(row['housenumber']) or pd.isna(row['postcode']) or pd.isna(row['city']):
        try:
            location = geolocator.reverse((row['latitude'], row['longitude']), exactly_one=True)
            if location:
                address = location.raw.get('address', {})
                row['street'] = row['street'] if pd.notna(row['street']) else address.get('road')
                row['housenumber'] = row['housenumber'] if pd.notna(row['housenumber']) else address.get('house_number')
                row['postcode'] = row['postcode'] if pd.notna(row['postcode']) else address.get('postcode')
                row['city'] = row['city'] if pd.notna(row['city']) else address.get('city') or address.get('town') or address.get('village') or address.get('municipality')
        except (GeocoderTimedOut, GeocoderServiceError) as e:
            print(f"Error geocoding {row['latitude']}, {row['longitude']}: {e}")
            time.sleep(0.5) # Pause to respect rate limits or for service recovery
        except Exception as e:
            print(f"Unexpected error: {e}")
        time.sleep(0.5) # Pause to respect Nominatim usage policy
    return row

print("Starting reverse geocoding for missing address data...")
atm_table = atm_table.apply(reverse_geocode_address, axis=1)
print("Reverse geocoding complete.")

Starting reverse geocoding for missing address data...
Reverse geocoding complete.

In [33]:
atm_table.head()

,element,id,name,operator,street,housenumber,postcode,city,opening_hours,fee,brand,geometry,latitude,longitude,atm_type,accessibility
0,node,60852951,NaN,Berliner Volksbank,Storkower Bogen,None,10369,Berlin,24/7,NaN,Berliner Volksbank,POINT (13.46562 52.52467),52.524670,13.465618,standalone,accessible
1,node,78252154,Bank für Sozialwirtschaft,Bank für Sozialwirtschaft,Oranienburger Straße,13,10178,Berlin,NaN,NaN,NaN,POINT (13.39863 52.52374),52.523744,13.398627,standalone,accessible
2,node,87036263,Sparda-Bank,Sparda-Bank Berlin,Caroline-Michaelis-Straße,None,10115,Berlin,06:00-23:00,NaN,Sparda-Bank Berlin,POINT (13.38428 52.53299),52.532985,13.384282,indoor,accessible
3,node,213106623,NaN,Sparkasse,Greifswalder Straße,87-88,10409,Berlin,NaN,NaN,NaN,POINT (13.44114 52.54217),52.542170,13.441137,indoor,accessible
4,node,239694634,Berliner Volksbank,Berliner Volksbank,Otto-Schmirgal-Straße,3,10319,Berlin,NaN,NaN,Berliner Volksbank,POINT (13.52164 52.4975),52.497501,13.521643,standalone,accessible

In [34]:
import pandas as pd

def create_full_address(row):
    components = []
    # Ensure values are not NaN/None and are converted to string before joining
    # Also check against the literal string 'unknown'
    if pd.notna(row['street']) and str(row['street']).lower() != 'unknown':
        components.append(str(row['street']))
    if pd.notna(row['housenumber']) and str(row['housenumber']).lower() != 'unknown':
        components.append(str(row['housenumber']))
    if pd.notna(row['postcode']) and str(row['postcode']).lower() != 'unknown':
        components.append(str(row['postcode']))
    if pd.notna(row['city']) and str(row['city']).lower() != 'unknown': # city should already be cleaned to 'Berlin'
        components.append(str(row['city']))

    if not components:
        return 'unknown'
    return ', '.join(components)

atm_table['address'] = atm_table.apply(create_full_address, axis=1)

# Drop the original address components
atm_table = atm_table.drop(columns=['street', 'housenumber', 'postcode', 'city'])

print("Value counts for 'address' column (top 20):")
print(atm_table['address'].value_counts(dropna=False).head(20))

atm_table.head()

Value counts for 'address' column (top 20):
address
Hermannstraße, 12049, Berlin          12
Karl-Marx-Straße, 12043, Berlin        9
Sonnenallee, 12045, Berlin             8
Kottbusser Damm, 10967, Berlin         7
Hauptstraße, 10827, Berlin             7
Turmstraße, 10551, Berlin              6
Eingangsebene, 10557, Berlin           6
Leipziger Platz, 12, 10117, Berlin     6
Weserstraße, 12045, Berlin             6
Friedrichstraße, 10117, Berlin         6
Müllerstraße, 13353, Berlin            6
Torstraße, 10115, Berlin               5
Wiener Straße, 10999, Berlin           5
Bernauer Straße, 13355, Berlin         5
Leipziger Straße, 10117, Berlin        5
Tempelhofer Damm, 12099, Berlin        5
Kurfürstendamm, 10711, Berlin          5
Sonnenallee, 12059, Berlin             5
Bergmannstraße, 10961, Berlin          4
Grünberger Straße, 10245, Berlin       4
Name: count, dtype: int64

,element,id,name,operator,opening_hours,fee,brand,geometry,latitude,longitude,atm_type,accessibility,address
0,node,60852951,NaN,Berliner Volksbank,24/7,NaN,Berliner Volksbank,POINT (13.46562 52.52467),52.524670,13.465618,standalone,accessible,"Storkower Bogen, 10369, Berlin"
1,node,78252154,Bank für Sozialwirtschaft,Bank für Sozialwirtschaft,NaN,NaN,NaN,POINT (13.39863 52.52374),52.523744,13.398627,standalone,accessible,"Oranienburger Straße, 13, 10178, Berlin"
2,node,87036263,Sparda-Bank,Sparda-Bank Berlin,06:00-23:00,NaN,Sparda-Bank Berlin,POINT (13.38428 52.53299),52.532985,13.384282,indoor,accessible,"Caroline-Michaelis-Straße, 10115, Berlin"
3,node,213106623,NaN,Sparkasse,NaN,NaN,NaN,POINT (13.44114 52.54217),52.542170,13.441137,indoor,accessible,"Greifswalder Straße, 87-88, 10409, Berlin"
4,node,239694634,Berliner Volksbank,Berliner Volksbank,NaN,NaN,Berliner Volksbank,POINT (13.52164 52.4975),52.497501,13.521643,standalone,accessible,"Otto-Schmirgal-Straße, 3, 10319, Berlin"

In [35]:
# Function to clean  bank names
def clean_bank_name(name):
    if pd.isna(name): return name
    name = str(name).lower().strip()
    
    if 'cashzone' in name or 'cash zone' in name: return 'Cashzone'
    if 'ic cash services' in name or 'ic cash' in name: return 'IC Cash Services'
    if 'bankhaus august lenz' in name or 'bankhaus lenz' in name: return 'Bankhaus August Lenz'
    if 'isbank' in name or 'işbank' in name: return 'İşbank'
    return name.title().replace('Eg', 'eG').replace('Gmbh', 'GmbH') # Basic title case and fix common abbreviations

# Create 'bank_name' column, prioritizing 'brand' then 'operator'
atm_table['bank_name'] = atm_table['brand'].apply(clean_bank_name)
atm_table['bank_name'] = atm_table['bank_name'].fillna(atm_table['operator'].apply(clean_bank_name))
#atm_table['bank_name'] = atm_table['bank_name'].fillna(atm_table['bank'].apply(clean_bank_name))

# Handle remaining NaN values in 'bank_name' if any
atm_table['bank_name'] = atm_table['bank_name'].fillna('unknown_atm')

# Drop original 'brand' and 'operator' columns
atm_table = atm_table.drop(columns=['brand', 'operator'])

# Display value counts for the new 'bank_name' column
print("Value counts for 'bank_name' column:")
print(atm_table['bank_name'].value_counts(dropna=False).head(20))

# Display the first few rows and info of the updated DataFrame
atm_table.head()

Value counts for 'bank_name' column:
bank_name
Euronet                 424
Berliner Sparkasse       87
unknown_atm              84
Berliner Volksbank       65
Cashzone                 51
Postbank                 38
Sparkasse                34
Bankhaus August Lenz     31
IC Cash Services         28
Euronet Worldwide        22
Reisebank                18
Iccash                   15
Ing                      14
Iccash Services          14
Volksbank                10
Ing-Diba                  8
Deutsche Bank             7
Sparda-Bank Berlin        6
Ec                        5
Commerzbank               5
Name: count, dtype: int64

,element,id,name,opening_hours,fee,geometry,latitude,longitude,atm_type,accessibility,address,bank_name
0,node,60852951,NaN,24/7,NaN,POINT (13.46562 52.52467),52.524670,13.465618,standalone,accessible,"Storkower Bogen, 10369, Berlin",Berliner Volksbank
1,node,78252154,Bank für Sozialwirtschaft,NaN,NaN,POINT (13.39863 52.52374),52.523744,13.398627,standalone,accessible,"Oranienburger Straße, 13, 10178, Berlin",Bank Für Sozialwirtschaft
2,node,87036263,Sparda-Bank,06:00-23:00,NaN,POINT (13.38428 52.53299),52.532985,13.384282,indoor,accessible,"Caroline-Michaelis-Straße, 10115, Berlin",Sparda-Bank Berlin
3,node,213106623,NaN,NaN,NaN,POINT (13.44114 52.54217),52.542170,13.441137,indoor,accessible,"Greifswalder Straße, 87-88, 10409, Berlin",Sparkasse
4,node,239694634,Berliner Volksbank,NaN,NaN,POINT (13.52164 52.4975),52.497501,13.521643,standalone,accessible,"Otto-Schmirgal-Straße, 3, 10319, Berlin",Berliner Volksbank

In [36]:
atm_table.info()

<class 'geopandas.geodataframe.GeoDataFrame'>
RangeIndex: 1062 entries, 0 to 1061
Data columns (total 12 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   element        1062 non-null   object
 1   id             1062 non-null   int64
 2   name           447 non-null    object
 3   opening_hours  349 non-null    object
 4   fee            30 non-null     object
 5   geometry       1062 non-null   geometry
 6   latitude       1062 non-null   float64
 7   longitude      1062 non-null   float64
 8   atm_type       1062 non-null   object
 9   accessibility  521 non-null    object
 10  address        1062 non-null   object
 11  bank_name      1062 non-null   object
dtypes: float64(2), geometry(1), int64(1), object(8)
memory usage: 99.7+ KB

## Inspect opening_hours column

### Subtask:
Examine the unique values and their frequencies in the 'opening_hours' column to identify patterns for standardization.

**Reasoning**:
To understand the distribution and variety of 'opening_hours' values, I will display the unique values and their counts, including missing values.

In [37]:
print("Value counts for 'opening_hours' column:")
print(atm_table['opening_hours'].value_counts(dropna=False).head(20))

Value counts for 'opening_hours' column:
opening_hours
NaN                                             713
24/7                                            280
Mo-Fr 06:00-23:00; Sa-Su 08:00-23:00             15
Mo-Fr 06:00-23:00; Sa,Su 08:00-23:00              7
06:00-23:00                                       6
06:00-22:00                                       3
Mo-Sa 07:00-21:00                                 3
Mo-Sa 10:00-20:00                                 2
Mo-Su 06:00-22:00                                 2
Mo-Su 06:00-23:00                                 2
Mo-Su 05:00 - 22:00                               1
open; Mo-Su 23:00-06:00 off                       1
Mo-Fr 06:00-23:00 Sa-Su 08:00-23:00               1
05:00-22:00                                       1
Mo-Fr 08:00-20:00; Sa 10:00-18:00; PH closed      1
Mo-Su,PH 8:00-20:00                               1
Mo-Fr 06:00-24:00; Sa 06:00-23:30                 1
Mo-Sa 10:00-21:00; Su 13:00-18:00                 1
Mo-Sa 08:00-22:00; PH off                         1
07:00-22:00                                       1
Name: count, dtype: int64

## Standardize opening_hours

### Subtask:
Clean and normalize the 'opening_hours' values into a consistent format, handling different representations and missing data.

**Reasoning**:
I will define a function to clean and standardize the 'opening_hours' column according to the instructions, handling various formats and missing values. Then I will apply this function to the DataFrame and display the value counts to verify the cleaning process.

In [38]:
def clean_opening_hours(hours):
    

    hours = str(hours).strip().lower()

    # Standardize 24/7 patterns
    if '24/7' in hours or '00:00-24:00' in hours: # covers 'Mo-Su,PH 00:00-24:00'
        return '24/7'

    # Remove extra notes or dates (e.g., "\n2024 May 23-2024 Nov 21 off")
    if '\n' in hours:
        hours = hours.split('\n')[0].strip()

    # Standardize common weekday/weekend patterns
    # Example: 'Mo-Fr 06:00-23:00; Sa-Su 08:00-23:00'
    # Generalize 'Mo-Fr' and 'Mo-Sa' to 'weekdays' for simplification if times are consistent
    # Or combine consistent hours if possible

    # Simplified cleaning for specific common patterns based on inspection
    if 'mo-fr 06:00-23:00; sa-su 08:00-23:00' in hours:
        return 'Mo-Fr 06:00-23:00; Sa-Su 08:00-23:00'
    if 'mo-fr 06:00-23:00; sa,su 08:00-23:00' in hours:
        return 'Mo-Fr 06:00-23:00; Sa-Su 08:00-23:00'
    if '06:00-23:00' in hours and 'mo-fr' not in hours and 'sa-su' not in hours:
        return '06:00-23:00'
    if '06:00-22:00' in hours and 'mo-su' in hours:
        return 'Mo-Su 06:00-22:00'
    if '06:00-22:00' in hours:
        return '06:00-22:00'


    # Keep the original format if it's already relatively clean or specific, otherwise mark as variable
    if hours in ['mo-fr 09:00-18:00', 'mo-sa 07:00-21:00', 'mo-sa 09:00-20:00', 'mo-su 06:00-23:00', 'mo-sa 08:00-22:00', '05:00-24:00', 'mo-sa 07:00-22:00']:
        return hours.title()

    # Fallback for complex or unknown patterns
    #return 'NaN'

atm_table['opening_hours'] = atm_table['opening_hours'].apply(clean_opening_hours)

print("Value counts for cleaned 'opening_hours' column:")
print(atm_table['opening_hours'].value_counts(dropna=False).head(20))

Value counts for cleaned 'opening_hours' column:
opening_hours
None                                    736
24/7                                    282
Mo-Fr 06:00-23:00; Sa-Su 08:00-23:00     22
06:00-23:00                               8
06:00-22:00                               4
Mo-Sa 07:00-21:00                         3
Mo-Su 06:00-22:00                         2
Mo-Sa 09:00-20:00                         1
Mo-Fr 09:00-18:00                         1
05:00-24:00                               1
Mo-Sa 08:00-22:00                         1
Mo-Sa 07:00-22:00                         1
Name: count, dtype: int64

## Inspect fee column

### Subtask:
Examine the unique values and their frequencies in the 'fee' column to identify patterns for standardization.

**Reasoning**:
To understand the distribution and variety of 'fee' values, I will display the unique values and their counts, including missing values.

In [39]:
print("Value counts for 'fee' column:")
print(atm_table['fee'].value_counts(dropna=False).head(20))

Value counts for 'fee' column:
fee
NaN                 1032
varies                17
yes                   10
no                     2
Visa & Girocards       1
Name: count, dtype: int64

## Standardize fee column

### Subtask:
Clean and normalize the 'fee' values into a consistent format, handling different representations and missing data.

**Reasoning**:
I will define a function to clean and standardize the 'fee' column, apply it to the DataFrame, and then display the value counts to verify the cleaning process.

In [40]:
def clean_fee(fee_value):
    
    fee_value = str(fee_value).lower().strip()
    if fee_value == 'no' or 'free' in fee_value:
        return 'no fee'
    if fee_value == 'yes':
        return 'fee applies'
    if 'varies' in fee_value:
        return 'fee varies'

    # Catch specific cases or return as is if complex
    #return fee_value

atm_table['fee'] = atm_table['fee'].apply(clean_fee)

print("Value counts for cleaned 'fee' column:")
print(atm_table['fee'].value_counts(dropna=False).head(20))

Value counts for cleaned 'fee' column:
fee
None           1033
fee varies       17
fee applies      10
no fee            2
Name: count, dtype: int64

In [41]:
atm_table = atm_table.drop(columns=['name'])

print("DataFrame after removing 'name' column:")
display(atm_table.head())
atm_table.info()

DataFrame after removing 'name' column:

,element,id,opening_hours,fee,geometry,latitude,longitude,atm_type,accessibility,address,bank_name
0,node,60852951,24/7,None,POINT (13.46562 52.52467),52.524670,13.465618,standalone,accessible,"Storkower Bogen, 10369, Berlin",Berliner Volksbank
1,node,78252154,None,None,POINT (13.39863 52.52374),52.523744,13.398627,standalone,accessible,"Oranienburger Straße, 13, 10178, Berlin",Bank Für Sozialwirtschaft
2,node,87036263,06:00-23:00,None,POINT (13.38428 52.53299),52.532985,13.384282,indoor,accessible,"Caroline-Michaelis-Straße, 10115, Berlin",Sparda-Bank Berlin
3,node,213106623,None,None,POINT (13.44114 52.54217),52.542170,13.441137,indoor,accessible,"Greifswalder Straße, 87-88, 10409, Berlin",Sparkasse
4,node,239694634,None,None,POINT (13.52164 52.4975),52.497501,13.521643,standalone,accessible,"Otto-Schmirgal-Straße, 3, 10319, Berlin",Berliner Volksbank

<class 'geopandas.geodataframe.GeoDataFrame'>
RangeIndex: 1062 entries, 0 to 1061
Data columns (total 11 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   element        1062 non-null   object
 1   id             1062 non-null   int64
 2   opening_hours  326 non-null    object
 3   fee            29 non-null     object
 4   geometry       1062 non-null   geometry
 5   latitude       1062 non-null   float64
 6   longitude      1062 non-null   float64
 7   atm_type       1062 non-null   object
 8   accessibility  521 non-null    object
 9   address        1062 non-null   object
 10  bank_name      1062 non-null   object
dtypes: float64(2), geometry(1), int64(1), object(7)
memory usage: 91.4+ KB

In [42]:
atm_table = atm_table.drop(columns=['element'])

print("DataFrame after removing 'element' column:")
display(atm_table.head())
atm_table.info()

DataFrame after removing 'element' column:

,id,opening_hours,fee,geometry,latitude,longitude,atm_type,accessibility,address,bank_name
0,60852951,24/7,None,POINT (13.46562 52.52467),52.524670,13.465618,standalone,accessible,"Storkower Bogen, 10369, Berlin",Berliner Volksbank
1,78252154,None,None,POINT (13.39863 52.52374),52.523744,13.398627,standalone,accessible,"Oranienburger Straße, 13, 10178, Berlin",Bank Für Sozialwirtschaft
2,87036263,06:00-23:00,None,POINT (13.38428 52.53299),52.532985,13.384282,indoor,accessible,"Caroline-Michaelis-Straße, 10115, Berlin",Sparda-Bank Berlin
3,213106623,None,None,POINT (13.44114 52.54217),52.542170,13.441137,indoor,accessible,"Greifswalder Straße, 87-88, 10409, Berlin",Sparkasse
4,239694634,None,None,POINT (13.52164 52.4975),52.497501,13.521643,standalone,accessible,"Otto-Schmirgal-Straße, 3, 10319, Berlin",Berliner Volksbank

<class 'geopandas.geodataframe.GeoDataFrame'>
RangeIndex: 1062 entries, 0 to 1061
Data columns (total 10 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   id             1062 non-null   int64
 1   opening_hours  326 non-null    object
 2   fee            29 non-null     object
 3   geometry       1062 non-null   geometry
 4   latitude       1062 non-null   float64
 5   longitude      1062 non-null   float64
 6   atm_type       1062 non-null   object
 7   accessibility  521 non-null    object
 8   address        1062 non-null   object
 9   bank_name      1062 non-null   object
dtypes: float64(2), geometry(1), int64(1), object(6)
memory usage: 83.1+ KB

In [43]:
atm_table = atm_table.rename(columns={"bank_name": "name"})

In [44]:
atm_table.head()

,id,opening_hours,fee,geometry,latitude,longitude,atm_type,accessibility,address,name
0,60852951,24/7,None,POINT (13.46562 52.52467),52.524670,13.465618,standalone,accessible,"Storkower Bogen, 10369, Berlin",Berliner Volksbank
1,78252154,None,None,POINT (13.39863 52.52374),52.523744,13.398627,standalone,accessible,"Oranienburger Straße, 13, 10178, Berlin",Bank Für Sozialwirtschaft
2,87036263,06:00-23:00,None,POINT (13.38428 52.53299),52.532985,13.384282,indoor,accessible,"Caroline-Michaelis-Straße, 10115, Berlin",Sparda-Bank Berlin
3,213106623,None,None,POINT (13.44114 52.54217),52.542170,13.441137,indoor,accessible,"Greifswalder Straße, 87-88, 10409, Berlin",Sparkasse
4,239694634,None,None,POINT (13.52164 52.4975),52.497501,13.521643,standalone,accessible,"Otto-Schmirgal-Straße, 3, 10319, Berlin",Berliner Volksbank

In [45]:
# Load official Berlin districts GeoDataFrame from lor_ortsteile.geojson
berlin_districts_gdf = gpd.read_file("../mapping/lor_ortsteile.geojson")

In [46]:
# Spatial join: matching your atms with district and neighborhoods
atms_with_districts = gpd.sjoin(
    atm_table,
    berlin_districts_gdf[["BEZIRK", "spatial_name", "OTEIL","geometry"]],
    how="left",
    predicate="within"
)
atms_with_districts.head()

,id,opening_hours,fee,geometry,latitude,longitude,atm_type,accessibility,address,name,index_right,BEZIRK,spatial_name,OTEIL
0,60852951,24/7,None,POINT (13.46562 52.52467),52.524670,13.465618,standalone,accessible,"Storkower Bogen, 10369, Berlin",Berliner Volksbank,83,Lichtenberg,1111,Fennpfuhl
1,78252154,None,None,POINT (13.39863 52.52374),52.523744,13.398627,standalone,accessible,"Oranienburger Straße, 13, 10178, Berlin",Bank Für Sozialwirtschaft,0,Mitte,0101,Mitte
2,87036263,06:00-23:00,None,POINT (13.38428 52.53299),52.532985,13.384282,indoor,accessible,"Caroline-Michaelis-Straße, 10115, Berlin",Sparda-Bank Berlin,0,Mitte,0101,Mitte
3,213106623,None,None,POINT (13.44114 52.54217),52.542170,13.441137,indoor,accessible,"Greifswalder Straße, 87-88, 10409, Berlin",Sparkasse,8,Pankow,0301,Prenzlauer Berg
4,239694634,None,None,POINT (13.52164 52.4975),52.497501,13.521643,standalone,accessible,"Otto-Schmirgal-Straße, 3, 10319, Berlin",Berliner Volksbank,75,Lichtenberg,1101,Friedrichsfelde

In [47]:
##just renaming columns for proper schema
atms_with_districts = atms_with_districts.rename(columns={
    "BEZIRK": "district",
    "OTEIL": "neighborhood",
    "spatial_name": "neighborhood_id"
}).drop(columns=["index_right"])  # drop district_number if not needed
atms_with_districts.head()

,id,opening_hours,fee,geometry,latitude,longitude,atm_type,accessibility,address,name,district,neighborhood_id,neighborhood
0,60852951,24/7,None,POINT (13.46562 52.52467),52.524670,13.465618,standalone,accessible,"Storkower Bogen, 10369, Berlin",Berliner Volksbank,Lichtenberg,1111,Fennpfuhl
1,78252154,None,None,POINT (13.39863 52.52374),52.523744,13.398627,standalone,accessible,"Oranienburger Straße, 13, 10178, Berlin",Bank Für Sozialwirtschaft,Mitte,0101,Mitte
2,87036263,06:00-23:00,None,POINT (13.38428 52.53299),52.532985,13.384282,indoor,accessible,"Caroline-Michaelis-Straße, 10115, Berlin",Sparda-Bank Berlin,Mitte,0101,Mitte
3,213106623,None,None,POINT (13.44114 52.54217),52.542170,13.441137,indoor,accessible,"Greifswalder Straße, 87-88, 10409, Berlin",Sparkasse,Pankow,0301,Prenzlauer Berg
4,239694634,None,None,POINT (13.52164 52.4975),52.497501,13.521643,standalone,accessible,"Otto-Schmirgal-Straße, 3, 10319, Berlin",Berliner Volksbank,Lichtenberg,1101,Friedrichsfelde

In [51]:
# District mapping (official codes as strings)
district_mapping = {
    'Mitte': '11001001',
    'Friedrichshain-Kreuzberg': '11002002',
    'Pankow': '11003003',
    'Charlottenburg-Wilmersdorf': '11004004',
    'Spandau': '11005005',
    'Steglitz-Zehlendorf': '11006006',
    'Tempelhof-Schöneberg': '11007007',
    'Neukölln': '11008008',
    'Treptow-Köpenick': '11009009',
    'Marzahn-Hellersdorf': '11010010',
    'Lichtenberg': '11011011',
    'Reinickendorf': '11012012'
}

# Apply mapping to create district_id column (string)
atms_with_districts['district_id'] = atms_with_districts['district'].map(district_mapping).astype(str)

# (Optional) Check if some districts were not mapped
#unmapped = df[~df['district'].isin(district_mapping.keys())]['district'].unique()
#if len(unmapped) > 0:
    #print("⚠️ Unmapped districts found:", unmapped)
atms_with_districts.head()

,id,opening_hours,fee,geometry,latitude,longitude,atm_type,accessibility,address,name,district,neighborhood_id,neighborhood,district_id
0,60852951,24/7,None,POINT (13.46562 52.52467),52.524670,13.465618,standalone,accessible,"Storkower Bogen, 10369, Berlin",Berliner Volksbank,Lichtenberg,1111,Fennpfuhl,11011011
1,78252154,None,None,POINT (13.39863 52.52374),52.523744,13.398627,standalone,accessible,"Oranienburger Straße, 13, 10178, Berlin",Bank Für Sozialwirtschaft,Mitte,0101,Mitte,11001001
2,87036263,06:00-23:00,None,POINT (13.38428 52.53299),52.532985,13.384282,indoor,accessible,"Caroline-Michaelis-Straße, 10115, Berlin",Sparda-Bank Berlin,Mitte,0101,Mitte,11001001
3,213106623,None,None,POINT (13.44114 52.54217),52.542170,13.441137,indoor,accessible,"Greifswalder Straße, 87-88, 10409, Berlin",Sparkasse,Pankow,0301,Prenzlauer Berg,11003003
4,239694634,None,None,POINT (13.52164 52.4975),52.497501,13.521643,standalone,accessible,"Otto-Schmirgal-Straße, 3, 10319, Berlin",Berliner Volksbank,Lichtenberg,1101,Friedrichsfelde,11011011

In [52]:
atms_with_districts.info()

<class 'geopandas.geodataframe.GeoDataFrame'>
Index: 1062 entries, 0 to 1061
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   id               1062 non-null   int64
 1   opening_hours    326 non-null    object
 2   fee              29 non-null     object
 3   geometry         1062 non-null   geometry
 4   latitude         1062 non-null   float64
 5   longitude        1062 non-null   float64
 6   atm_type         1062 non-null   object
 7   accessibility    521 non-null    object
 8   address          1062 non-null   object
 9   name             1062 non-null   object
 10  district         1062 non-null   object
 11  neighborhood_id  1062 non-null   object
 12  neighborhood     1062 non-null   object
 13  district_id      1062 non-null   object
dtypes: float64(2), geometry(1), int64(1), object(10)
memory usage: 124.5+ KB

In [53]:
atms_with_districts.to_csv('atm_cleaned.csv', index=False)
print('atms_with_districts saved to atm_cleaned.csv')

atms_with_districts saved to atm_cleaned.csv