**📍 Fetch data about coworking-spaces in Berlin from OpenStreetMap (OSM)**

In [2]:
#%pip install osmnx geopandas pandas
#%pip install geopy

In [20]:
%pip install geoalchemy2

Collecting geoalchemy2
  Downloading geoalchemy2-0.18.1-py3-none-any.whl.metadata (2.3 kB)
Requirement already satisfied: SQLAlchemy>=1.4 in /opt/anaconda3/lib/python3.13/site-packages (from geoalchemy2) (2.0.39)
Requirement already satisfied: packaging in /opt/anaconda3/lib/python3.13/site-packages (from geoalchemy2) (24.2)
Requirement already satisfied: typing-extensions>=4.6.0 in /opt/anaconda3/lib/python3.13/site-packages (from SQLAlchemy>=1.4->geoalchemy2) (4.12.2)
Downloading geoalchemy2-0.18.1-py3-none-any.whl (81 kB)
Installing collected packages: geoalchemy2
Successfully installed geoalchemy2-0.18.1
Note: you may need to restart the kernel to use updated packages.

In [3]:
import pandas as pd
import numpy as np
import osmnx as ox
import geopandas as gpd
import geopy
from geopy.geocoders import Nominatim
from geopy.extra.rate_limiter import RateLimiter

In [4]:
tags = {"office": "coworking"}

ox.settings.use_cache = True
ox.settings.log_console = True

gdf = ox.features.features_from_place("Berlin, Germany", tags=tags)

In [5]:
# filter columns that relevant to project
columns = [
    "name","addr:street","addr:housenumber","addr:postcode",
    "addr:city","addr:country","addr:suburb","opening_hours",
    "internet_access","wheelchair","contact:phone",
    "contact:email","contact:website","geometry"
]
gdf_coworking_spaces = gdf[[col for col in columns if col in gdf.columns]].copy()

# Extract Latitude and Longitude
gdf_coworking_spaces['geometry'] = gdf_coworking_spaces['geometry'].apply(lambda geom: geom if geom.geom_type == 'Point' else geom.representative_point())

gdf_coworking_spaces["latitude"] = gdf.geometry.centroid.y
gdf_coworking_spaces["longitude"] = gdf.geometry.centroid.x

# cleaning columnnames for better understanding
gdf_coworking_spaces = gdf_coworking_spaces.rename(
    columns=lambda c: c.replace("addr:", "").replace("contact:", "")
)

/var/folders/tg/38ly2d5x39d3gfjppq_39pcc0000gn/T/ipykernel_8569/3325745849.py:13: UserWarning: Geometry is in a geographic CRS. Results from 'centroid' are likely incorrect. Use 'GeoSeries.to_crs()' to re-project geometries to a projected CRS before this operation.

  gdf_coworking_spaces["latitude"] = gdf.geometry.centroid.y
/var/folders/tg/38ly2d5x39d3gfjppq_39pcc0000gn/T/ipykernel_8569/3325745849.py:14: UserWarning: Geometry is in a geographic CRS. Results from 'centroid' are likely incorrect. Use 'GeoSeries.to_crs()' to re-project geometries to a projected CRS before this operation.

  gdf_coworking_spaces["longitude"] = gdf.geometry.centroid.x

In [6]:
# Geocoder starten
geolocator = Nominatim(user_agent="coworking_reverse_geocoder")
reverse = RateLimiter(geolocator.reverse, min_delay_seconds=1)

# Mapping: Nominatim → Deine Spaltennamen
mapping = {
    "road": "street",
    "house_number": "housenumber",
    "postcode": "postcode",
    "city": "city",
    "suburb": "suburb"
}

def reverse_geocode(lat, lon):
    try:
        location = reverse((lat, lon), language="de")
        if location is None:
            return {}
        return location.raw.get("address", {})
    except:
        return {}

# Durch alle Zeilen iterieren
for idx, row in gdf_coworking_spaces.iterrows():
    
    # Prüfen, ob überhaupt ein Feld fehlt
    needs_geocoding = any(
        field not in row or row[field] in ["unknown", None, ""] or pd.isna(row[field])
        for field in mapping.values()
    )
    
    if not needs_geocoding:
        continue  # alles vorhanden → überspringen
    
    lat, lon = row["latitude"], row["longitude"]
    address = reverse_geocode(lat, lon)
    
    # Werte eintragen
    for osm_key, df_key in mapping.items():
        
        # Nur eintragen, wenn bisher leer
        if df_key not in row or row[df_key] in ["unknown", None, ""] or pd.isna(row[df_key]):
            value = address.get(osm_key, "")
            gdf_coworking_spaces.at[idx, df_key] = value

In [7]:
gdf_coworking_spaces_districts = gpd.read_file("lor_ortsteile.geojson")

# Spatial join: matching your cinemas with district and neighborhoods
gdf_coworking_spaces = gpd.sjoin(
    gdf_coworking_spaces,
    gdf_coworking_spaces_districts[["BEZIRK", "spatial_name", "OTEIL","geometry"]],
    how="left",
    predicate="within"
)
gdf_coworking_spaces.head()

                                         name              street housenumber  \
element id
node    330264334                St. Oberholz  Rosenthaler Straße          72
        459659033                         NaN     Ella-Kay-Straße          38
        1776155022  Pulsraum Coworking Berlin     Kottbusser Damm          25
        1827346141                       Fora    Unter den Linden          40
        2181178532           Hauptstadt Räume          Kochstraße

                   postcode    city country           suburb  \
element id
node    330264334     10119  Berlin      DE            Mitte
        459659033     10405  Berlin     NaN  Prenzlauer Berg
        1776155022    10967  Berlin      DE        Kreuzberg
        1827346141    10117  Berlin      DE            Mitte
        2181178532    10969  Berlin     NaN        Kreuzberg

                                                        opening_hours  \
element id
node    330264334   Mo-Th 08:00-24:00, Fr 08:00-03:00, Sa 09:00-03...
        459659033                                                 NaN
        1776155022                  Mo-Fr 07:00-21:00; Sa 10:00-19:00
        1827346141                                                NaN
        2181178532                                                NaN

                   internet_access wheelchair            phone  \
element id
node    330264334             wlan    limited  +49 30 24085586
        459659033              NaN        NaN              NaN
        1776155022            wlan        NaN              NaN
        1827346141             NaN        NaN              NaN
        2181178532             NaN        NaN              NaN

                                    email  \
element id
node    330264334   info@sanktoberholz.de
        459659033                     NaN
        1776155022                    NaN
        1827346141                    NaN
        2181178532                    NaN

                                                            website  \
element id
node    330264334   https://sanktoberholz.de/standorte/rosenthaler/
        459659033                                               NaN
        1776155022                                              NaN
        1827346141                                              NaN
        2181178532                                              NaN

                                     geometry   latitude  longitude  \
element id
node    330264334   POINT (13.40178 52.52953)  52.529530  13.401782
        459659033    POINT (13.4328 52.54017)  52.540165  13.432801
        1776155022  POINT (13.42387 52.48963)  52.489635  13.423870
        1827346141  POINT (13.38644 52.51716)  52.517159  13.386443
        2181178532  POINT (13.38708 52.50659)  52.506594  13.387084

                    index_right                    BEZIRK spatial_name  \
element id
node    330264334             0                     Mitte         0101
        459659033             8                    Pankow         0301
        1776155022            7  Friedrichshain-Kreuzberg         0202
        1827346141            0                     Mitte         0101
        2181178532            7  Friedrichshain-Kreuzberg         0202

                              OTEIL
element id
node    330264334             Mitte
        459659033   Prenzlauer Berg
        1776155022        Kreuzberg
        1827346141            Mitte
        2181178532        Kreuzberg

In [8]:
##just renaming columns for proper schema
gdf_coworking_spaces = gdf_coworking_spaces.rename(columns={
    "BEZIRK": "district",
    "OTEIL": "neighborhood",
    "spatial_name": "neighborhood_id"
}).drop(columns=["index_right"])  # drop district_number if not needed
gdf_coworking_spaces.head()

                                         name              street housenumber  \
element id
node    330264334                St. Oberholz  Rosenthaler Straße          72
        459659033                         NaN     Ella-Kay-Straße          38
        1776155022  Pulsraum Coworking Berlin     Kottbusser Damm          25
        1827346141                       Fora    Unter den Linden          40
        2181178532           Hauptstadt Räume          Kochstraße

                   postcode    city country           suburb  \
element id
node    330264334     10119  Berlin      DE            Mitte
        459659033     10405  Berlin     NaN  Prenzlauer Berg
        1776155022    10967  Berlin      DE        Kreuzberg
        1827346141    10117  Berlin      DE            Mitte
        2181178532    10969  Berlin     NaN        Kreuzberg

                                                        opening_hours  \
element id
node    330264334   Mo-Th 08:00-24:00, Fr 08:00-03:00, Sa 09:00-03...
        459659033                                                 NaN
        1776155022                  Mo-Fr 07:00-21:00; Sa 10:00-19:00
        1827346141                                                NaN
        2181178532                                                NaN

                   internet_access wheelchair            phone  \
element id
node    330264334             wlan    limited  +49 30 24085586
        459659033              NaN        NaN              NaN
        1776155022            wlan        NaN              NaN
        1827346141             NaN        NaN              NaN
        2181178532             NaN        NaN              NaN

                                    email  \
element id
node    330264334   info@sanktoberholz.de
        459659033                     NaN
        1776155022                    NaN
        1827346141                    NaN
        2181178532                    NaN

                                                            website  \
element id
node    330264334   https://sanktoberholz.de/standorte/rosenthaler/
        459659033                                               NaN
        1776155022                                              NaN
        1827346141                                              NaN
        2181178532                                              NaN

                                     geometry   latitude  longitude  \
element id
node    330264334   POINT (13.40178 52.52953)  52.529530  13.401782
        459659033    POINT (13.4328 52.54017)  52.540165  13.432801
        1776155022  POINT (13.42387 52.48963)  52.489635  13.423870
        1827346141  POINT (13.38644 52.51716)  52.517159  13.386443
        2181178532  POINT (13.38708 52.50659)  52.506594  13.387084

                                    district neighborhood_id     neighborhood
element id
node    330264334                      Mitte            0101            Mitte
        459659033                     Pankow            0301  Prenzlauer Berg
        1776155022  Friedrichshain-Kreuzberg            0202        Kreuzberg
        1827346141                     Mitte            0101            Mitte
        2181178532  Friedrichshain-Kreuzberg            0202        Kreuzberg

In [9]:
# District mapping (official codes as strings)
district_mapping = {
    'Mitte': '11001001',
    'Friedrichshain-Kreuzberg': '11002002',
    'Pankow': '11003003',
    'Charlottenburg-Wilmersdorf': '11004004',
    'Spandau': '11005005',
    'Steglitz-Zehlendorf': '11006006',
    'Tempelhof-Schöneberg': '11007007',
    'Neukölln': '11008008',
    'Treptow-Köpenick': '11009009',
    'Marzahn-Hellersdorf': '11010010',
    'Lichtenberg': '11011011',
    'Reinickendorf': '11012012'
}

# Apply mapping to create district_id column (string)
gdf_coworking_spaces['district_id'] = gdf_coworking_spaces['district'].map(district_mapping).astype(str)

gdf_coworking_spaces.head()

                                         name              street housenumber  \
element id
node    330264334                St. Oberholz  Rosenthaler Straße          72
        459659033                         NaN     Ella-Kay-Straße          38
        1776155022  Pulsraum Coworking Berlin     Kottbusser Damm          25
        1827346141                       Fora    Unter den Linden          40
        2181178532           Hauptstadt Räume          Kochstraße

                   postcode    city country           suburb  \
element id
node    330264334     10119  Berlin      DE            Mitte
        459659033     10405  Berlin     NaN  Prenzlauer Berg
        1776155022    10967  Berlin      DE        Kreuzberg
        1827346141    10117  Berlin      DE            Mitte
        2181178532    10969  Berlin     NaN        Kreuzberg

                                                        opening_hours  \
element id
node    330264334   Mo-Th 08:00-24:00, Fr 08:00-03:00, Sa 09:00-03...
        459659033                                                 NaN
        1776155022                  Mo-Fr 07:00-21:00; Sa 10:00-19:00
        1827346141                                                NaN
        2181178532                                                NaN

                   internet_access wheelchair            phone  \
element id
node    330264334             wlan    limited  +49 30 24085586
        459659033              NaN        NaN              NaN
        1776155022            wlan        NaN              NaN
        1827346141             NaN        NaN              NaN
        2181178532             NaN        NaN              NaN

                                    email  \
element id
node    330264334   info@sanktoberholz.de
        459659033                     NaN
        1776155022                    NaN
        1827346141                    NaN
        2181178532                    NaN

                                                            website  \
element id
node    330264334   https://sanktoberholz.de/standorte/rosenthaler/
        459659033                                               NaN
        1776155022                                              NaN
        1827346141                                              NaN
        2181178532                                              NaN

                                     geometry   latitude  longitude  \
element id
node    330264334   POINT (13.40178 52.52953)  52.529530  13.401782
        459659033    POINT (13.4328 52.54017)  52.540165  13.432801
        1776155022  POINT (13.42387 52.48963)  52.489635  13.423870
        1827346141  POINT (13.38644 52.51716)  52.517159  13.386443
        2181178532  POINT (13.38708 52.50659)  52.506594  13.387084

                                    district neighborhood_id     neighborhood  \
element id
node    330264334                      Mitte            0101            Mitte
        459659033                     Pankow            0301  Prenzlauer Berg
        1776155022  Friedrichshain-Kreuzberg            0202        Kreuzberg
        1827346141                     Mitte            0101            Mitte
        2181178532  Friedrichshain-Kreuzberg            0202        Kreuzberg

                   district_id
element id
node    330264334     11001001
        459659033     11003003
        1776155022    11002002
        1827346141    11001001
        2181178532    11002002

In [10]:
cols = ["street", "housenumber", "postcode", "city"]

gdf_coworking_spaces["address"] = (
    gdf_coworking_spaces[cols].fillna("").astype(str).agg(" ".join, axis=1).str.replace(r"\s+", " ", regex=True).str.strip()                          
)

In [11]:
# Convert certain columns to correct type

# Convert columns to specific types
df_transformed = gdf_coworking_spaces.copy()

# String columns (ensure consistent text type)
string_columns = [
    "name","street","housenumber","postcode",
    "city","country","suburb","address","opening_hours",
    "internet_access","wheelchair","phone",
    "email","website","district","district_id",
    "neighborhood","neighborhood_id"
]
df_transformed[string_columns] = df_transformed[string_columns].apply(lambda col: col.astype("string").str.strip().str.lower()) # ensure text type

# Preview the updated dtypes
print(df_transformed.dtypes)

name               string[python]
street             string[python]
housenumber        string[python]
postcode           string[python]
city               string[python]
country            string[python]
suburb             string[python]
opening_hours      string[python]
internet_access    string[python]
wheelchair         string[python]
phone              string[python]
email              string[python]
website            string[python]
geometry                 geometry
latitude                  float64
longitude                 float64
district           string[python]
neighborhood_id    string[python]
neighborhood       string[python]
district_id        string[python]
address            string[python]
dtype: object

In [12]:
# Reset index to move 'element' and 'id' into columns
df_transformed = df_transformed.reset_index()

# Drop the 'element' column and rename 'id' to 'store_id'
df_transformed = df_transformed.drop(columns=["element"]).rename(columns={"id": "coworking_center_id"})
df_transformed["coworking_center_id"] = df_transformed["coworking_center_id"].astype("string")

In [13]:
# Save as GeoJSON (keeps geometry) and CSV

raw_geojson_path = "/Users/ramzi.gossing/Webeet Project Folder/Webeet.io internship documentaion/layered-populate-data-pool-da/coworking_centers/sources_coworking_spaces/coworking_centers.geojson"
raw_csv_path = "/Users/ramzi.gossing/Webeet Project Folder/Webeet.io internship documentaion/layered-populate-data-pool-da/coworking_centers/sources_coworking_spaces/coworking_centers.csv"


gdf_coworking_spaces.to_file(raw_geojson_path, driver="GeoJSON")
gdf_coworking_spaces.drop(columns="geometry").to_csv(raw_csv_path, index=False)

print(f"Raw data saved to: {raw_geojson_path} and {raw_csv_path}")

Raw data saved to: /Users/ramzi.gossing/Webeet Project Folder/Webeet.io internship documentaion/layered-populate-data-pool-da/coworking_centers/sources_coworking_spaces/coworking_centers.geojson and /Users/ramzi.gossing/Webeet Project Folder/Webeet.io internship documentaion/layered-populate-data-pool-da/coworking_centers/sources_coworking_spaces/coworking_centers.csv

In [14]:
df_final = df_transformed

In [15]:
#we need to specify the model used for geodata

if df_final.crs is None:
    df_final.set_crs(epsg=4326, inplace=True)

In [22]:
from sqlalchemy import create_engine, text
import warnings

warnings.filterwarnings("ignore")

# Step 1: Neon DB connection string
DATABASE_URL = (
    "postgresql+psycopg2://neondb_owner:a9Am7Yy5r9_T7h4OF2GN@ep-falling-glitter-a5m0j5gk-pooler.us-east-2.aws.neon.tech:5432/neondb?sslmode=require"
)

# Step 2: Create engine
engine = create_engine(DATABASE_URL)

# Step 3: Drop old table if needed (be careful)
drop_sql = "DROP TABLE IF EXISTS test_berlin_data.coworking_centers_berlin;"
create_sql = """
CREATE TABLE test_berlin_data.coworking_centers_berlin (
    coworking_center_id TEXT PRIMARY KEY,
    name TEXT,
    street TEXT,
    housenumber TEXT,
    postcode TEXT,
    city TEXT,
    country TEXT,
    suburb TEXT,
    adress TEXT,
    opening_hours TEXT,
    internet_access TEXT,
    wheelchair TEXT,
    phone TEXT,
    email TEXT,
    website TEXT,
    district TEXT,
    district_id TEXT,
    neighborhood TEXT,
    neighborhood_id TEXT,
    geometry GEOMETRY (Geometry, 4326),   -- here we need to specify the model as well
    latitude DOUBLE PRECISION,
    longitude DOUBLE PRECISION
);
"""
# in the part below we were missing that "conn.commit()"
with engine.connect() as conn:
    conn.execute(text(drop_sql))
    conn.execute(text(create_sql))
    conn.commit()
    print("✅ Table recreated successfully with PK.")

✅ Table recreated successfully with PK.

In [24]:
from sqlalchemy import text

with engine.begin() as conn:
    conn.execute(text("""
        ALTER TABLE test_berlin_data.coworking_centers_berlin
        ADD COLUMN IF NOT EXISTS address TEXT;
    """))

In [25]:
df_final.to_postgis(
    name="coworking_centers_berlin",
    con=engine,
    schema="test_berlin_data",
    if_exists="append",   # now safe to append
    index=False
)
print(f"✅ Inserted {len(df_final)} rows into DB.")

✅ Inserted 100 rows into DB.

In [26]:
df_final.info()

<class 'geopandas.geodataframe.GeoDataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 22 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   coworking_center_id  100 non-null    string
 1   name                 97 non-null     string
 2   street               100 non-null    string
 3   housenumber          100 non-null    string
 4   postcode             100 non-null    string
 5   city                 100 non-null    string
 6   country              51 non-null     string
 7   suburb               100 non-null    string
 8   opening_hours        31 non-null     string
 9   internet_access      27 non-null     string
 10  wheelchair           21 non-null     string
 11  phone                12 non-null     string
 12  email                12 non-null     string
 13  website              22 non-null     string
 14  geometry             100 non-null    geometry
 15  latitude             100 non-null    float64
 16  longitude            100 non-null    float64
 17  district             100 non-null    string
 18  neighborhood_id      100 non-null    string
 19  neighborhood         100 non-null    string
 20  district_id          100 non-null    string
 21  address              100 non-null    string
dtypes: float64(2), geometry(1), string(19)
memory usage: 17.3 KB

In [31]:
# Check if data was inserted
with engine.connect() as conn:
    count = conn.execute(text("SELECT COUNT(*) FROM test_berlin_data.coworking_centers_berlin")).scalar()
    print(f"✅ {count} rows in the DB.")

✅ 100 rows in the DB.