# Berlin Gas Stations – Data Transformation

## Step 2: Geospatial Data Transformation.

This notebook performs the transformation of raw Berlin gas station data into a clean, production-ready dataset.

### 🎯 Objective
Create a clean dataset that:

- Enriches gas stations with neighborhood and district information (via spatial join)
- Uses `spatial_alias` as `neighborhood_id`
- Adds `district_id` using official Berlin mapping (01–12)
- Builds a proper `address` column
- Reverse-geocodes missing addresses using Nominatim
- Keeps null values (no "unknown")
- Ensures an `id` column exists
- Deduplicates records
- Exports:
  - `gas_stations_transformed.geojson`
  - `gas_stations_transformed.csv`

The notebook runs top → bottom without errors after kernel restart.

## 1️⃣ Import Required Libraries

We import only the necessary libraries to ensure a clean and production-safe pipeline.

In [51]:
import json
import time
from pathlib import Path

import pandas as pd
import geopandas as gpd
import requests
import osmnx as ox
import numpy as np

In [2]:
ox.settings.use_cache = True
ox.settings.log_console = True

In [3]:
tags_fuel = {"amenity": "fuel"}
gdf_fuel = ox.features.features_from_place("Berlin, Germany", tags=tags_fuel)

print("Fuel stations fetched:", len(gdf_fuel))
gdf_fuel.head(3)

Fuel stations fetched: 289

                                   geometry amenity brand brand:wikidata  \
element id
node    16541597   POINT (13.3456 52.54631)    fuel  Aral        Q565734
        26756830  POINT (13.32822 52.53069)    fuel  Aral        Q565734
        26867411   POINT (13.2945 52.50197)    fuel   NaN            NaN

                 brand:wikipedia compressed_air fuel:HGV_diesel fuel:diesel  \
element id
node    16541597      en:Aral AG            yes          retail         yes
        26756830         de:Aral            yes             NaN         yes
        26867411             NaN            yes             NaN         yes

                 fuel:e10 fuel:octane_102  ... landuse  \
element id                                 ...
node    16541597      yes          retail  ...     NaN
        26756830      yes             yes  ...     NaN
        26867411      yes             NaN  ...     NaN

                 service:vehicle:car_repair service:vehicle:inspection  \
element id
node    16541597                        NaN                        NaN
        26756830                        NaN                        NaN
        26867411                        NaN                        NaN

                 fuel:octane_92 height wikimedia_commons payment:H2_Delivery  \
element id
node    16541597            NaN    NaN               NaN                 NaN
        26756830            NaN    NaN               NaN                 NaN
        26867411            NaN    NaN               NaN                 NaN

                 payment:HyLane payment:ryd_pay start_date:fuel:h35
element id
node    16541597            NaN             NaN                 NaN
        26756830            NaN             NaN                 NaN
        26867411            NaN             NaN                 NaN

[3 rows x 145 columns]

In [49]:
tags_ev = {"amenity": "charging_station"}
gdf_ev = ox.features.features_from_place("Berlin, Germany", tags=tags_ev)

print("Charging stations fetched:", len(gdf_ev))
gdf_ev.head(3)

Charging stations fetched: 1563

                                    geometry           amenity amperage  \
element id
node    425089052   POINT (13.3227 52.51369)  charging_station       32
        429740871  POINT (13.38087 52.52366)  charging_station       32
        429951629  POINT (13.32903 52.49941)  charging_station       32

                  authentication:short_message bicycle capacity  \
element id
node    425089052                          yes      no        2
        429740871                          yes     NaN        2
        429951629                          yes     NaN        2

                        operator                    ref socket:type2  \
element id
node    425089052  RWE-Effizienz  BA-0602-4 / BA-0603-0            2
        429740871           E.ON  BA-0500-2 / BA-0501-9            2
        429951629         Innogy  BA-0798-1 / BA-0707-5            2

                                         source source:delivery_date voltage  \
element id
node    425089052  RWE Effizienz GmbH, Dortmund           2011/01/17     400
        429740871                        survey                  NaN     400
        429951629  RWE Effizienz GmbH, Dortmund           2011/01/17     400

                  access addr:floor       brand brand:wikidata  \
element id
node    425089052    NaN        NaN         NaN            NaN
        429740871    yes          0  e.on drive       Q2124721
        429951629    NaN        NaN      Innogy       Q2124721

                  brand:wikipedia covered  fee level  \
element id
node    425089052             NaN     NaN  NaN   NaN
        429740871       de:Innogy      no  yes     0
        429951629       de:Innogy     NaN  NaN   NaN

                                              name opening_hours  \
element id
node    425089052                              NaN           NaN
        429740871                           Innogy          24/7
        429951629  RWE Stromtankstelle E-Mobillity           NaN

                  operator:wikidata operator:wikipedia payment:mastercard  \
element id
node    425089052               NaN                NaN                NaN
        429740871           Q270223          de:Innogy                yes
        429951629          Q2124721          de:Innogy                NaN

                  payment:visa  \
element id
node    425089052          NaN
        429740871          yes
        429951629          NaN

                                                            note:de  \
element id
node    425089052                                               NaN
        429740871                                               NaN
        429951629  Vor Schaperstraße 17 neben Eckhaus Meinekestraße

                  authentication:membership_card payment:account_cards  \
element id
node    425089052                            NaN                   NaN
        429740871                            NaN                   NaN
        429951629                            NaN                   NaN

                  addr:housenumber addr:street authentication:app  \
element id
node    425089052              NaN         NaN                NaN
        429740871              NaN         NaN                NaN
        429951629              NaN         NaN                NaN

                  authentication:nfc contact:phone contact:website motorcar  \
element id
node    425089052                NaN           NaN             NaN      NaN
        429740871                NaN           NaN             NaN      NaN
        429951629                NaN           NaN             NaN      NaN

                  parking:fee socket:type2:output check_date addr:suburb  \
element id
node    425089052         NaN                 NaN        NaN         NaN
        429740871         NaN                 NaN        NaN         NaN
        429951629         NaN                 NaN        NaN         NaN

                  wheelchair socket:type2:current socket:type2:voltage  \
element id
node    425089052        NaN                  NaN                  NaN
        429740871        NaN                  NaN                  NaN
        429951629        NaN                  NaN                  NaN

                  wikimedia_commons survey:date description  bus  hgv  \
element id
node    425089052               NaN         NaN         NaN  NaN  NaN
        429740871               NaN         NaN         NaN  NaN  NaN
        429951629               NaN         NaN         NaN  NaN  NaN

                  maxstay:conditional network payment:paypal scooter colour  \
element id
node    425089052                 NaN     NaN            NaN     NaN    NaN
        429740871                 NaN     NaN            NaN     NaN    NaN
        429951629                 NaN     NaN            NaN     NaN    NaN

                  location authentication:phone_call layer socket:schuko  \
element id
node    425089052      NaN                       NaN   NaN           NaN
        429740871      NaN                       NaN   NaN           NaN
        429951629      NaN                       NaN   NaN           NaN

                  short_name website charge payment:american_express  \
element id
node    425089052        NaN     NaN    NaN                      NaN
        429740871        NaN     NaN    NaN                      NaN
        429951629        NaN     NaN    NaN                      NaN

                  payment:sepa payment:vpay authentication:none comment  \
element id
node    425089052          NaN          NaN                 NaN     NaN
        429740871          NaN          NaN                 NaN     NaN
        429951629          NaN          NaN                 NaN     NaN

                  maxstay socket:chademo socket:type2_combo  \
element id
node    425089052     NaN            NaN                NaN
        429740871     NaN            NaN                NaN
        429951629     NaN            NaN                NaN

                  socket:chademo:output socket:type2_combo:output truck  \
element id
node    425089052                   NaN                       NaN   NaN
        429740871                   NaN                       NaN   NaN
        429951629                   NaN                       NaN   NaN

                  camera:direction camera:mount camera:type highway man_made  \
element id
node    425089052              NaN          NaN         NaN     NaN      NaN
        429740871              NaN          NaN         NaN     NaN      NaN
        429951629              NaN          NaN         NaN     NaN      NaN

                  surveillance surveillance:type surveillance:zone  \
element id
node    425089052          NaN               NaN               NaN
        429740871          NaN               NaN               NaN
        429951629          NaN               NaN               NaN

                  ref:EU:EVSE note payment:credit_cards addr:city  \
element id
node    425089052         NaN  NaN                  NaN       NaN
        429740871         NaN  NaN                  NaN       NaN
        429951629         NaN  NaN                  NaN       NaN

                  addr:postcode addr:country noname output  \
element id
node    425089052           NaN          NaN    NaN    NaN
        429740871           NaN          NaN    NaN    NaN
        429951629           NaN          NaN    NaN    NaN

                  charging_station:output phone description:de socket:usb  \
element id
node    425089052                     NaN   NaN            NaN        NaN
        429740871                     NaN   NaN            NaN        NaN
        429951629                     NaN   NaN            NaN        NaN

                  mapillary socket:tesla_supercharger_ccs start_date  \
element id
node    425089052       NaN                           NaN        NaN
        429740871       NaN                           NaN        NaN
        429951629       NaN                           NaN        NaN

                  socket:type2_cable  lit support fixme payment:maestro  \
element id
node    425089052                NaN  NaN     NaN   NaN             NaN
        429740871                NaN  NaN     NaN   NaN             NaN
        429951629                NaN  NaN     NaN   NaN             NaN

                  payment:mea object:city object:country object:housenumber  \
element id
node    425089052         NaN         NaN            NaN                NaN
        429740871         NaN         NaN            NaN                NaN
        429951629         NaN         NaN            NaN                NaN

                  object:postcode object:street payment:app payment:cards  \
element id
node    425089052             NaN           NaN         NaN           NaN
        429740871             NaN           NaN         NaN           NaN
        429951629             NaN           NaN         NaN           NaN

                  payment:cash payment:membership_card payment:qr_code  \
element id
node    425089052          NaN                     NaN             NaN
        429740871          NaN                     NaN             NaN
        429951629          NaN                     NaN             NaN

                  capacity:motorcar toilets:wheelchair payment:bank_transfer  \
element id
node    425089052               NaN                NaN                   NaN
        429740871               NaN                NaN                   NaN
        429951629               NaN                NaN                   NaN

                  socket:tesla_supercharger_ccs:output  \
element id
node    425089052                                  NaN
        429740871                                  NaN
        429951629                                  NaN

                  socket:type2_cable:output payment:Giro-e payment:Ladekarte  \
element id
node    425089052                       NaN            NaN               NaN
        429740871                       NaN            NaN               NaN
        429951629                       NaN            NaN               NaN

                  direction lamp_mount lamp_type access:conditional  \
element id
node    425089052       NaN        NaN       NaN                NaN
        429740871       NaN        NaN       NaN                NaN
        429951629       NaN        NaN       NaN                NaN

                  payment:contactless small_electric_vehicle motor_vehicle  \
element id
node    425089052                 NaN                    NaN           NaN
        429740871                 NaN                    NaN           NaN
        429951629                 NaN                    NaN           NaN

                  contact:email parking:left parking:left:fee  \
element id
node    425089052           NaN          NaN              NaN
        429740871           NaN          NaN              NaN
        429951629           NaN          NaN              NaN

                  parking:left:maxstay parking:left:orientation parking:right  \
element id
node    425089052                  NaN                      NaN           NaN
        429740871                  NaN                      NaN           NaN
        429951629                  NaN                      NaN           NaN

                  image manufacturer payment:nfc authentication:contactless  \
element id
node    425089052   NaN          NaN         NaN                        NaN
        429740871   NaN          NaN         NaN                        NaN
        429951629   NaN          NaN         NaN                        NaN

                  name:en socket:type2_combo:current  \
element id
node    425089052     NaN                        NaN
        429740871     NaN                        NaN
        429951629     NaN                        NaN

                  socket:type2_combo:voltage bicycle_parking  \
element id
node    425089052                        NaN             NaN
        429740871                        NaN             NaN
        429951629                        NaN             NaN

                  socket:device:USB-A socket:device:USB-C charge:conditional  \
element id
node    425089052                 NaN                 NaN                NaN
        429740871                 NaN                 NaN                NaN
        429951629                 NaN                 NaN                NaN

                  socket:type1:output email panoramax panoramax:0 panoramax:1  \
element id
node    425089052                 NaN   NaN       NaN         NaN         NaN
        429740871                 NaN   NaN       NaN         NaN         NaN
        429951629                 NaN   NaN       NaN         NaN         NaN

                  payment:apple_pay payment:google_pay payment:samsung_pay  \
element id
node    425089052               NaN                NaN                 NaN
        429740871               NaN                NaN                 NaN
        429951629               NaN                NaN                 NaN

                  orientation indoor operator:type not:operator:wikidata  \
element id
node    425089052         NaN    NaN           NaN                   NaN
        429740871         NaN    NaN           NaN                   NaN
        429951629         NaN    NaN           NaN                   NaN

                  payment:debit_cards payment:rfid_card  \
element id
node    425089052                 NaN               NaN
        429740871                 NaN               NaN
        429951629                 NaN               NaN

                  payment:online_payment payment:prepaid_cards  \
element id
node    425089052                    NaN                   NaN
        429740871                    NaN                   NaN
        429951629                    NaN                   NaN

                  obstacle:parking position serialnumber material  \
element id
node    425089052              NaN      NaN          NaN      NaN
        429740871              NaN      NaN          NaN      NaN
        429951629              NaN      NaN          NaN      NaN

                  construction motorcycle socket:type1 owner socket:j3105-1  \
element id
node    425089052          NaN        NaN          NaN   NaN            NaN
        429740871          NaN        NaN          NaN   NaN            NaN
        429951629          NaN        NaN          NaN   NaN            NaN

                  socket:j3105-1:output payment:girocard capacity:charging  \
element id
node    425089052                   NaN              NaN               NaN
        429740871                   NaN              NaN               NaN
        429951629                   NaN              NaN               NaN

                  capacity:bicycle payment:dkv taxi socket:unknown  \
element id
node    425089052              NaN         NaN  NaN            NaN
        429740871              NaN         NaN  NaN            NaN
        429951629              NaN         NaN  NaN            NaN

                  socket:unknown:output markings restriction street:name  \
element id
node    425089052                   NaN      NaN         NaN         NaN
        429740871                   NaN      NaN         NaN         NaN
        429951629                   NaN      NaN         NaN         NaN

                  capacity:disabled surface ref:goingelectric  \
element id
node    425089052               NaN     NaN               NaN
        429740871               NaN     NaN               NaN
        429951629               NaN     NaN               NaN

                  socket:chademo:current socket:chademo:voltage
element id
node    425089052                    NaN                    NaN
        429740871                    NaN                    NaN
        429951629                    NaN                    NaN

In [5]:
gdf_fuel["poi_type"] = "fuel_station"
gdf_ev["poi_type"] = "charging_station"

gdf = pd.concat([gdf_fuel, gdf_ev], axis=0)
gdf = gpd.GeoDataFrame(gdf, geometry="geometry", crs=gdf_fuel.crs)

print("Total POIs:", len(gdf))
gdf.head(3)

Total POIs: 1852

                                   geometry amenity brand brand:wikidata  \
element id
node    16541597   POINT (13.3456 52.54631)    fuel  Aral        Q565734
        26756830  POINT (13.32822 52.53069)    fuel  Aral        Q565734
        26867411   POINT (13.2945 52.50197)    fuel   NaN            NaN

                 brand:wikipedia compressed_air fuel:HGV_diesel fuel:diesel  \
element id
node    16541597      en:Aral AG            yes          retail         yes
        26756830         de:Aral            yes             NaN         yes
        26867411             NaN            yes             NaN         yes

                 fuel:e10 fuel:octane_102  ... taxi socket:unknown  \
element id                                 ...
node    16541597      yes          retail  ...  NaN            NaN
        26756830      yes             yes  ...  NaN            NaN
        26867411      yes             NaN  ...  NaN            NaN

                 socket:unknown:output markings restriction street:name  \
element id
node    16541597                   NaN      NaN         NaN         NaN
        26756830                   NaN      NaN         NaN         NaN
        26867411                   NaN      NaN         NaN         NaN

                 capacity:disabled ref:goingelectric socket:chademo:current  \
element id
node    16541597               NaN               NaN                    NaN
        26756830               NaN               NaN                    NaN
        26867411               NaN               NaN                    NaN

                 socket:chademo:voltage
element id
node    16541597                    NaN
        26756830                    NaN
        26867411                    NaN

[3 rows x 278 columns]

In [6]:
columns = [
    "name",
    "addr:street", "addr:housenumber", "addr:postcode", "addr:city",
    "opening_hours",
    "brand", "operator",
    "phone", "contact:email", "website",
    "geometry",
    "poi_type"
]

gdf_station = gdf[[c for c in columns if c in gdf.columns]].copy()
print("Filtered dataset shape:", gdf_station.shape)
gdf_station.head(3)

Filtered dataset shape: (1852, 13)

                            name         addr:street addr:housenumber  \
element id
node    16541597            Aral                 NaN              NaN
        26756830            Aral       Beusselstraße               55
        26867411  Bavaria petrol  Heilbronner Straße               14

                 addr:postcode addr:city                      opening_hours  \
element id
node    16541597           NaN       NaN                               24/7
        26756830         10553    Berlin                               24/7
        26867411         10711    Berlin  Mo-Fr 07:00-20:00; Sa 07:00-18:00

                 brand        operator           phone contact:email  \
element id
node    16541597  Aral             NaN             NaN           NaN
        26756830  Aral      Mike Seitz  +49 30 3914404           NaN
        26867411   NaN  Bavaria Petrol             NaN           NaN

                                                            website  \
element id
node    16541597                                                NaN
        26756830  https://tankstelle.aral.de/berlin/beusselstras...
        26867411                                                NaN

                                   geometry      poi_type
element id
node    16541597   POINT (13.3456 52.54631)  fuel_station
        26756830  POINT (13.32822 52.53069)  fuel_station
        26867411   POINT (13.2945 52.50197)  fuel_station

In [7]:
gdf_station["geometry"] = gdf_station["geometry"].apply(
    lambda geom: geom if geom.geom_type == "Point" else geom.representative_point()
)

# Extract latitude and longitude
gdf_station["latitude"] = gdf_station.geometry.y
gdf_station["longitude"] = gdf_station.geometry.x

In [8]:
gdf_station = gdf_station.rename(columns={
    "name": "station_name",
    "addr:street": "street",
    "addr:housenumber": "housenumber",
    "addr:postcode": "postcode",
    "addr:city": "city",
    "contact:email": "email"
})

gdf_station["data_source"] = "OSM"
gdf_station.head(3)

                    station_name              street housenumber postcode  \
element id
node    16541597            Aral                 NaN         NaN      NaN
        26756830            Aral       Beusselstraße          55    10553
        26867411  Bavaria petrol  Heilbronner Straße          14    10711

                    city                      opening_hours brand  \
element id
node    16541597     NaN                               24/7  Aral
        26756830  Berlin                               24/7  Aral
        26867411  Berlin  Mo-Fr 07:00-20:00; Sa 07:00-18:00   NaN

                        operator           phone email  \
element id
node    16541597             NaN             NaN   NaN
        26756830      Mike Seitz  +49 30 3914404   NaN
        26867411  Bavaria Petrol             NaN   NaN

                                                            website  \
element id
node    16541597                                                NaN
        26756830  https://tankstelle.aral.de/berlin/beusselstras...
        26867411                                                NaN

                                   geometry      poi_type   latitude  \
element id
node    16541597   POINT (13.3456 52.54631)  fuel_station  52.546315
        26756830  POINT (13.32822 52.53069)  fuel_station  52.530694
        26867411   POINT (13.2945 52.50197)  fuel_station  52.501974

                  longitude data_source
element id
node    16541597  13.345599         OSM
        26756830  13.328225         OSM
        26867411  13.294496         OSM

In [9]:
print("gdf_fuel:", len(gdf_fuel))
print("gdf_ev:", len(gdf_ev))
print("gdf:", len(gdf))
print("gdf_station:", len(gdf_station))

gdf_fuel: 289
gdf_ev: 1563
gdf: 1852
gdf_station: 1852

In [10]:
from pathlib import Path

SOURCES_DIR = Path("./sources")
SOURCES_DIR.mkdir(parents=True, exist_ok=True)

raw_geojson_path = SOURCES_DIR / "gas_stations_raw.geojson"
raw_csv_path = SOURCES_DIR / "gas_stations_raw.csv"

gdf.to_file(raw_geojson_path, driver="GeoJSON")
gdf.drop(columns="geometry").to_csv(raw_csv_path, index=False)

print("✅ Saved:")
print(" -", raw_geojson_path)
print(" -", raw_csv_path)

✅ Saved:
 - sources/gas_stations_raw.geojson
 - sources/gas_stations_raw.csv

## 2️⃣ Define Paths and Output Locations

This section defines all input and output paths in one place.
We use assertions to ensure required files exist before proceeding.

In [12]:
from pathlib import Path

# --- Find project root by searching upward until we find sources/lor_ortsteile.geojson
cwd = Path.cwd().resolve()

BASE_DIR = None
for p in [cwd, *cwd.parents]:
    if (p / "sources" / "lor_ortsteile.geojson").exists():
        BASE_DIR = p
        break

if BASE_DIR is None:
    raise FileNotFoundError(
        "Could not find project root. Expected to find sources/lor_ortsteile.geojson in a parent directory."
    )

SOURCES_DIR = BASE_DIR / "sources"
OUTPUT_DIR  = SOURCES_DIR

RAW_GEOJSON = SOURCES_DIR / "gas_stations_raw.geojson"
LOR_GEOJSON = SOURCES_DIR / "lor_ortsteile.geojson"

OUT_GEOJSON = OUTPUT_DIR / "gas_stations_transformed.geojson"
OUT_CSV     = OUTPUT_DIR / "gas_stations_transformed.csv"

CACHE_DIR = OUTPUT_DIR / "cache"
CACHE_DIR.mkdir(parents=True, exist_ok=True)
REVERSE_CACHE = CACHE_DIR / "nominatim_reverse_cache.json"

assert RAW_GEOJSON.exists(), f"Missing: {RAW_GEOJSON}"
assert LOR_GEOJSON.exists(), f"Missing: {LOR_GEOJSON}"

print("BASE_DIR:", BASE_DIR)
print("RAW_GEOJSON:", RAW_GEOJSON)
print("LOR_GEOJSON:", LOR_GEOJSON)

BASE_DIR: /Users/kajetanhanausek/Desktop/cloned_repos/layered-populate-data-pool-da/gas-stations
RAW_GEOJSON: /Users/kajetanhanausek/Desktop/cloned_repos/layered-populate-data-pool-da/gas-stations/sources/gas_stations_raw.geojson
LOR_GEOJSON: /Users/kajetanhanausek/Desktop/cloned_repos/layered-populate-data-pool-da/gas-stations/sources/lor_ortsteile.geojson

## 3️⃣ Load Raw Gas Stations and LOR Neighborhood Data

We load:

- Raw gas station GeoJSON
- LOR (Berlin Ortsteile) GeoJSON

Both datasets are converted to a common CRS (EPSG:4326).

In [13]:
gdf_raw = gdf.copy()
gdf_lor = gpd.read_file(LOR_GEOJSON)

TARGET_CRS = "EPSG:4326"

if gdf_raw.crs is None:
    gdf_raw = gdf_raw.set_crs(TARGET_CRS)
else:
    gdf_raw = gdf_raw.to_crs(TARGET_CRS)

if gdf_lor.crs is None:
    gdf_lor = gdf_lor.set_crs(TARGET_CRS)
else:
    gdf_lor = gdf_lor.to_crs(TARGET_CRS)

## 3️⃣b Normalize Geometry to POINT (Centroids)

Reviewer requirement: all geometries must be POINT.
We convert any non-POINT geometries to centroid points before spatial join.

In [14]:
# Ensure raw gas station geometries are POINT (use centroid for non-POINT)
if "geometry" not in gdf_raw.columns:
    raise ValueError("gdf_raw has no geometry column")

# Convert non-POINT to centroid
non_point = gdf_raw.geometry.geom_type.ne("Point")
if non_point.any():
    gdf_raw.loc[non_point, "geometry"] = gdf_raw.loc[non_point, "geometry"].centroid

# Final safety check
assert gdf_raw.geometry.geom_type.eq("Point").all(), "Some raw geometries are still not POINT after centroid conversion"

/var/folders/tk/bx1zbkk52y3b84pwkrt4dz5c0000gn/T/ipykernel_30962/2448647510.py:8: UserWarning: Geometry is in a geographic CRS. Results from 'centroid' are likely incorrect. Use 'GeoSeries.to_crs()' to re-project geometries to a projected CRS before this operation.

  gdf_raw.loc[non_point, "geometry"] = gdf_raw.loc[non_point, "geometry"].centroid

## 4️⃣ Prepare LOR Data

Reviewer requirement:
- `neighborhood_id` must use the column `spatial_alias`.

We standardize column names to:

- `neighborhood`
- `neighborhood_id`
- `district`

In [15]:
# -----------------------
# Prepare LOR correctly
# -----------------------

# LOR subset (use BEZIRK as district as suggested by reviewer)
gdf_lor_small = gdf_lor[["spatial_name", "spatial_alias", "geometry", "BEZIRK"]].copy()

gdf_lor_small = gdf_lor_small.rename(columns={
    "spatial_name": "neighborhood",
    "spatial_alias": "neighborhood_id",
    "BEZIRK": "district",
})

# keep as strings
gdf_lor_small["neighborhood_id"] = gdf_lor_small["neighborhood_id"].astype(str)
gdf_lor_small["district"] = gdf_lor_small["district"].astype(str)

In [16]:
print("LOR rows:", len(gdf_lor_small))
print("LOR columns:", list(gdf_lor_small.columns))
gdf_lor_small.head(3)

LOR rows: 96
LOR columns: ['neighborhood', 'neighborhood_id', 'geometry', 'district']

,neighborhood,neighborhood_id,geometry,district
0,0101,Mitte,"POLYGON ((13.41649 52.52696, 13.41635 52.52702...",Mitte
1,0102,Moabit,"POLYGON ((13.33884 52.51974, 13.33884 52.51974...",Mitte
2,0103,Hansaviertel,"POLYGON ((13.34322 52.51557, 13.34323 52.51557...",Mitte

## 5️⃣ Spatial Join (Gas Stations → Neighborhoods)

We assign each gas station:

- neighborhood
- neighborhood_id (spatial_alias)
- district

Using a spatial `within` join.

In [17]:
gdf = gpd.sjoin(gdf_raw, gdf_lor_small, how="left", predicate="within")
gdf = gdf.drop(columns=[c for c in ["index_right"] if c in gdf.columns])
# Ensure joined output geometry is also POINT (DB requirement)
gdf["geometry"] = gdf.geometry.centroid
assert gdf.geometry.geom_type.eq("Point").all(), "Some joined geometries are not POINT after centroid conversion"

/var/folders/tk/bx1zbkk52y3b84pwkrt4dz5c0000gn/T/ipykernel_30962/648683279.py:4: UserWarning: Geometry is in a geographic CRS. Results from 'centroid' are likely incorrect. Use 'GeoSeries.to_crs()' to re-project geometries to a projected CRS before this operation.

  gdf["geometry"] = gdf.geometry.centroid

## QA: Ensure Geometry is POINT

All geometries must be POINT type (centroids) before proceeding.

In [18]:
print(gdf.geometry.geom_type.value_counts())

assert (gdf.geometry.geom_type == "Point").all(), \
    "Geometry still contains non-POINT types"

Point    1852
Name: count, dtype: int64

In [19]:
# --- Fix swapped neighborhood fields (ensure correct meaning)
# neighborhood should be the NAME, neighborhood_id should be the ID (spatial_alias)

# If they are swapped (id looks like words and name looks like numbers), swap them
sample_id = gdf["neighborhood_id"].dropna().astype(str).head(5).tolist()
sample_name = gdf["neighborhood"].dropna().astype(str).head(5).tolist()

def looks_numeric_list(vals):
    return all(v.replace(".", "").isdigit() for v in vals if v is not None)

def looks_text_list(vals):
    return any(any(ch.isalpha() for ch in v) for v in vals if v is not None)

if looks_text_list(sample_id) and looks_numeric_list(sample_name):
    gdf["neighborhood"], gdf["neighborhood_id"] = gdf["neighborhood_id"], gdf["neighborhood"]

## 6️⃣ Add District ID (01–12 Official Berlin Mapping)

We derive `district_id` from the first two digits of `neighborhood_id`
(e.g., `0105` → `01`) and map it to the official Berlin district name.

QA checks ensure that:
- All valid neighborhood IDs produce a district_id
- All district_id values exist in the official mapping

In [20]:
# ==========================================
# Add District ID (Official 8-digit Mapping)
# ==========================================

# Reviewer-required official district mapping
district_mapping = {
    "Mitte": "11001001",
    "Friedrichshain-Kreuzberg": "11002002",
    "Pankow": "11003003",
    "Charlottenburg-Wilmersdorf": "11004004",
    "Spandau": "11005005",
    "Steglitz-Zehlendorf": "11006006",
    "Tempelhof-Schöneberg": "11007007",
    "Neukölln": "11008008",
    "Treptow-Köpenick": "11009009",
    "Marzahn-Hellersdorf": "11010010",
    "Lichtenberg": "11011011",
    "Reinickendorf": "11012012",
}

# Map district_id directly from district (BEZIRK from LOR)
gdf["district_id"] = gdf["district"].map(district_mapping)

# -------------------------
# QA: Ensure mapping worked
# -------------------------
nulls = gdf["district_id"].isna().sum()
print("district_id nulls:", nulls)

if nulls > 0:
    print("Unmapped district values:")
    print(gdf.loc[gdf["district_id"].isna(), "district"].unique())
    raise ValueError("District mapping failed — check spelling vs mapping keys.")

# Show mapping preview
print(
    gdf[["district", "district_id"]]
    .drop_duplicates()
    .sort_values("district")
)

district_id nulls: 0
                                     district district_id
element id
node    26867411   Charlottenburg-Wilmersdorf    11004004
        68363395     Friedrichshain-Kreuzberg    11002002
        101387833                 Lichtenberg    11011011
        83502731          Marzahn-Hellersdorf    11010010
        16541597                        Mitte    11001001
        262318783                    Neukölln    11008008
        281775191                      Pankow    11003003
        60436247                Reinickendorf    11012012
        247687679                     Spandau    11005005
        27088369          Steglitz-Zehlendorf    11006006
        260753895        Tempelhof-Schöneberg    11007007
        260744445            Treptow-Köpenick    11009009

In [21]:
print("Rows:", len(gdf))
print("Columns include neighborhood_id:", "neighborhood_id" in gdf.columns)
print("neighborhood_id nulls:", gdf["neighborhood_id"].isna().sum() if "neighborhood_id" in gdf.columns else "N/A")
gdf.head(3)

Rows: 1852
Columns include neighborhood_id: True
neighborhood_id nulls: 0

                                   geometry amenity brand brand:wikidata  \
element id
node    16541597   POINT (13.3456 52.54631)    fuel  Aral        Q565734
        26756830  POINT (13.32822 52.53069)    fuel  Aral        Q565734
        26867411   POINT (13.2945 52.50197)    fuel   NaN            NaN

                 brand:wikipedia compressed_air fuel:HGV_diesel fuel:diesel  \
element id
node    16541597      en:Aral AG            yes          retail         yes
        26756830         de:Aral            yes             NaN         yes
        26867411             NaN            yes             NaN         yes

                 fuel:e10 fuel:octane_102  ... restriction street:name  \
element id                                 ...
node    16541597      yes          retail  ...         NaN         NaN
        26756830      yes             yes  ...         NaN         NaN
        26867411      yes             NaN  ...         NaN         NaN

                 capacity:disabled ref:goingelectric socket:chademo:current  \
element id
node    16541597               NaN               NaN                    NaN
        26756830               NaN               NaN                    NaN
        26867411               NaN               NaN                    NaN

                 socket:chademo:voltage neighborhood neighborhood_id  \
element id
node    16541597                    NaN      Wedding            0105
        26756830                    NaN       Moabit            0102
        26867411                    NaN     Halensee            0407

                                    district district_id
element id
node    16541597                       Mitte    11001001
        26756830                       Mitte    11001001
        26867411  Charlottenburg-Wilmersdorf    11004004

[3 rows x 282 columns]

In [39]:
for col in gdf.columns:
    print(col)

geometry
amenity
brand
brand_wikidata
brand_wikipedia
compressed_air
fuel_HGV_diesel
fuel_diesel
fuel_e10
fuel_octane_102
fuel_octane_95
man_made
name
opening_hours
surveillance
wheelchair
addr_city
addr_country
addr_housenumber
addr_postcode
addr_street
addr_suburb
check_date
fuel_ethanol
level
operator
payment_cash
payment_mastercard
payment_visa
phone
website
check_date_opening_hours
fuel_adblue
fuel_biodiesel
fuel_octane_98
shop
car_wash
contact_fax
contact_phone
contact_website
payment_american_express
payment_debit_cards
payment_diners_club
payment_dkv
payment_maestro
payment_uta
payment_v_pay
payment_westfalen_card
self_service
fuel_biogas
fuel_cng
fuel_lpg
kiosk
fuel_GTL_diesel
compressed_air_fee
fax
fuel_gts_diesel
fuel_octane_100
payment_cryptocurrencies
payment_girocard
payment_credit_cards
ref
source
toilets
toilets_wheelchair
changing_table
operator_wikidata
wheelchair_description
covered
fuel_1_50
note
currency_others
fuel_kerosene
payment_coins
payment_notes
currency_EUR
access
atm
fuel_e85
fuel_1_25
payment_routex
drink_club-mate
automated
postal_code
internet_access
internet_access_fee
smoking
description
source_opening_hours
name_de
name_en
post_office
post_office_brand
post_office_brand_wikidata
addr_inclusion
layer
car_repair
branch
roof_levels
roof_shape
check_date_compressed_air
contact_email
fuel_heating_oil
start_date
building
fuel_hvo100
payment_esso_card
payment_euroshell
payment_shell_clubsmart
official_name
ref_vatin
fuel_adblue_canister
name_signed
fuel_h35
fuel_h70
payment_h2_mobility_card
source_website
start_date_fuel_h70
lottery
valves
truck_wash
vacuum_cleaner
tenant
opening_hours_signed
building_levels
building_min_level
fuel_LH2
bus
minibus
cash_withdrawal
payment_apple_pay
payment_google_pay
surface
atm_operator
owner
landuse
service_vehicle_car_repair
service_vehicle_inspection
fuel_octane_92
height
wikimedia_commons
payment_H2_Delivery
payment_HyLane
payment_ryd_pay
start_date_fuel_h35
poi_type
amperage
authentication_short_message
bicycle
capacity
socket_type2
source_delivery_date
voltage
addr_floor
fee
operator_wikipedia
note_de
authentication_membership_card
payment_account_cards
authentication_app
authentication_nfc
motorcar
parking_fee
socket_type2_output
socket_type2_current
socket_type2_voltage
survey_date
hgv
maxstay_conditional
network
payment_paypal
scooter
colour
location
authentication_phone_call
socket_schuko
short_name
charge
payment_sepa
payment_vpay
authentication_none
comment
maxstay
socket_chademo
socket_type2_combo
socket_chademo_output
socket_type2_combo_output
truck
camera_direction
camera_mount
camera_type
highway
surveillance_type
surveillance_zone
ref_EU_EVSE
noname
output
charging_station_output
description_de
socket_usb
mapillary
socket_tesla_supercharger_ccs
socket_type2_cable
lit
support
fixme
payment_mea
object_city
object_country
object_housenumber
object_postcode
object_street
payment_app
payment_cards
payment_membership_card
payment_qr_code
capacity_motorcar
payment_bank_transfer
socket_tesla_supercharger_ccs_output
socket_type2_cable_output
payment_Giro-e
payment_Ladekarte
direction
lamp_mount
lamp_type
access_conditional
payment_contactless
small_electric_vehicle
motor_vehicle
parking_left
parking_left_fee
parking_left_maxstay
parking_left_orientation
parking_right
image
manufacturer
payment_nfc
authentication_contactless
socket_type2_combo_current
socket_type2_combo_voltage
bicycle_parking
socket_device_USB-A
socket_device_USB-C
charge_conditional
socket_type1_output
email
panoramax
panoramax_0
panoramax_1
payment_samsung_pay
orientation
indoor
operator_type
not_operator_wikidata
payment_rfid_card
payment_online_payment
payment_prepaid_cards
obstacle_parking
position
serialnumber
material
construction
motorcycle
socket_type1
socket_j3105-1
socket_j3105-1_output
capacity_charging
capacity_bicycle
taxi
socket_unknown
socket_unknown_output
markings
restriction
street_name
capacity_disabled
ref_goingelectric
socket_chademo_current
socket_chademo_voltage
neighborhood
neighborhood_id
district
district_id
latitude
longitude
address
id

## 7️⃣ Build Address Column (keep nulls)

We create a single `address` field from available components (`street`, `housenumber`, `postcode`, `city`).
Missing addresses remain `null` (no `"unknown"` values).
We also create `latitude` and `longitude` from geometry for later reverse geocoding.

In [22]:
import pandas as pd

# --- Ensure we have point geometry (needed for lat/lon and reverse geocoding)
# If your data is already points, this is fine.
centroids = gdf.geometry.centroid
gdf["latitude"] = centroids.y
gdf["longitude"] = centroids.x


def _clean_str(x):
    if x is None or pd.isna(x):
        return None
    s = str(x).strip()
    return s if s != "" else None


def build_address(row):
    # Try common address parts if they exist in the dataset
    street = _clean_str(row.get("street")) if "street" in row else None
    housenumber = _clean_str(row.get("housenumber")) if "housenumber" in row else None
    postcode = _clean_str(row.get("postcode")) if "postcode" in row else None
    city = _clean_str(row.get("city")) if "city" in row else None

    parts = []

    # street + housenumber together
    if street and housenumber:
        parts.append(f"{street} {housenumber}")
    elif street:
        parts.append(street)
    elif housenumber:
        parts.append(housenumber)

    # postcode + city together
    if postcode and city:
        parts.append(f"{postcode} {city}")
    elif postcode:
        parts.append(postcode)
    elif city:
        parts.append(city)

    if not parts:
        return None  # keep NULL (reviewer request)

    return ", ".join(parts)


# Create address column
gdf["address"] = gdf.apply(build_address, axis=1)

# Quick sanity check (optional but helpful)
print("address nulls:", gdf["address"].isna().sum())

address nulls: 1852

/var/folders/tk/bx1zbkk52y3b84pwkrt4dz5c0000gn/T/ipykernel_30962/2569310983.py:5: UserWarning: Geometry is in a geographic CRS. Results from 'centroid' are likely incorrect. Use 'GeoSeries.to_crs()' to re-project geometries to a projected CRS before this operation.

  centroids = gdf.geometry.centroid

## 8️⃣ Ensure `id` Column (required)

The final dataset must include an `id`.  
We use an existing identifier if available, otherwise create a deterministic fallback.

In [23]:
# Prefer existing stable IDs if present
if "id" in gdf.columns:
    gdf["id"] = gdf["id"].astype("string")
elif "osm_id" in gdf.columns:
    gdf["id"] = gdf["osm_id"].astype("string")
else:
    # Deterministic fallback from coordinates
    gdf["id"] = (
        "gs_" +
        gdf["latitude"].round(6).astype("string") + "_" +
        gdf["longitude"].round(6).astype("string")
    )

# QA checks
assert gdf["id"].isna().sum() == 0, "id contains nulls"

## 9️⃣ Reverse Geocode Missing Addresses (Nominatim)

For rows where `address` is null, we use Nominatim reverse geocoding to fetch an address.
Results are cached locally to avoid repeated API calls.
If no address is found, values remain `null` (no `"unknown"`).

In [24]:
import json
import time
import requests
import pandas as pd

# -----------------------
# Settings
# -----------------------
RUN_REVERSE_GEOCODING = True          # switch off for fast runs
MAX_REQUESTS = gdf["address"].isna().sum()                 
SLEEP_SECONDS = 1.1                  # polite rate limit

# Requires from your paths cell:
# REVERSE_CACHE (Path), CACHE_DIR exists

# -----------------------
# Load cache
# -----------------------
if REVERSE_CACHE.exists():
    cache = json.loads(REVERSE_CACHE.read_text())
else:
    cache = {}

def _cache_key(lat, lon):
    return f"{lat:.6f},{lon:.6f}"

def reverse_geocode(lat, lon):
    key = _cache_key(lat, lon)
    if key in cache:
        return cache[key]

    url = "https://nominatim.openstreetmap.org/reverse"
    params = {
        "format": "jsonv2",
        "lat": lat,
        "lon": lon,
        "zoom": 18,
        "addressdetails": 1,
    }
    headers = {"User-Agent": "berlin-gas-stations-transformation/1.0"}

    try:
        r = requests.get(url, params=params, headers=headers, timeout=20)
        if r.status_code != 200:
            cache[key] = None
            return None
        data = r.json()
        display = data.get("display_name")
        cache[key] = display if display else None
        return cache[key]
    except Exception:
        cache[key] = None
        return None

# -----------------------
# Run reverse geocoding only for missing addresses
# -----------------------
missing_mask = gdf["address"].isna()

total_missing = int(missing_mask.sum())
print("Missing addresses before:", total_missing)

if RUN_REVERSE_GEOCODING and total_missing > 0:
    idx_all = gdf.loc[missing_mask].index.tolist()

    # Limit runtime
    idx = idx_all[:MAX_REQUESTS]
    print(f"Reverse geocoding {len(idx)} of {total_missing} missing addresses (MAX_REQUESTS={MAX_REQUESTS})")

    for i, row_idx in enumerate(idx, start=1):
        lat = gdf.at[row_idx, "latitude"]
        lon = gdf.at[row_idx, "longitude"]

        # If lat/lon missing, skip
        if pd.isna(lat) or pd.isna(lon):
            continue

        gdf.at[row_idx, "address"] = reverse_geocode(float(lat), float(lon))

        if i % 20 == 0:
            print(f"  progress: {i}/{len(idx)}")

        time.sleep(SLEEP_SECONDS)

    # Save cache
    REVERSE_CACHE.write_text(json.dumps(cache))
    print("Cache saved to:", REVERSE_CACHE)

print("Missing addresses after:", int(gdf["address"].isna().sum()))
print(f"Note: Reverse geocoding is limited to MAX_REQUESTS={MAX_REQUESTS} to keep notebook runtime reasonable. Cache will fill progressively.")

Missing addresses before: 1852
Reverse geocoding 1852 of 1852 missing addresses (MAX_REQUESTS=1852)
  progress: 20/1852
  progress: 40/1852
  progress: 60/1852
  progress: 80/1852
  progress: 100/1852
  progress: 120/1852
  progress: 140/1852
  progress: 160/1852
  progress: 180/1852
  progress: 200/1852
  progress: 220/1852
  progress: 240/1852
  progress: 260/1852
  progress: 280/1852
  progress: 300/1852
  progress: 320/1852
  progress: 340/1852
  progress: 360/1852
  progress: 380/1852
  progress: 400/1852
  progress: 420/1852
  progress: 440/1852
  progress: 460/1852
  progress: 480/1852
  progress: 500/1852
  progress: 520/1852
  progress: 540/1852
  progress: 560/1852
  progress: 580/1852
  progress: 600/1852
  progress: 620/1852
  progress: 640/1852
  progress: 660/1852
  progress: 680/1852
  progress: 700/1852
  progress: 720/1852
  progress: 740/1852
  progress: 760/1852
  progress: 780/1852
  progress: 800/1852
  progress: 820/1852
  progress: 840/1852
  progress: 860/1852
  progress: 880/1852
  progress: 900/1852
  progress: 920/1852
  progress: 940/1852
  progress: 960/1852
  progress: 980/1852
  progress: 1000/1852
  progress: 1020/1852
  progress: 1040/1852
  progress: 1060/1852
  progress: 1080/1852
  progress: 1100/1852
  progress: 1120/1852
  progress: 1140/1852
  progress: 1160/1852
  progress: 1180/1852
  progress: 1200/1852
  progress: 1220/1852
  progress: 1240/1852
  progress: 1260/1852
  progress: 1280/1852
  progress: 1300/1852
  progress: 1320/1852
  progress: 1340/1852
  progress: 1360/1852
  progress: 1380/1852
  progress: 1400/1852
  progress: 1420/1852
  progress: 1440/1852
  progress: 1460/1852
  progress: 1480/1852
  progress: 1500/1852
  progress: 1520/1852
  progress: 1540/1852
  progress: 1560/1852
  progress: 1580/1852
  progress: 1600/1852
  progress: 1620/1852
  progress: 1640/1852
  progress: 1660/1852
  progress: 1680/1852
  progress: 1700/1852
  progress: 1720/1852
  progress: 1740/1852
  progress: 1760/1852
  progress: 1780/1852
  progress: 1800/1852
  progress: 1820/1852
  progress: 1840/1852
Cache saved to: /Users/kajetanhanausek/Desktop/cloned_repos/layered-populate-data-pool-da/gas-stations/sources/cache/nominatim_reverse_cache.json
Missing addresses after: 0
Note: Reverse geocoding is limited to MAX_REQUESTS=1852 to keep notebook runtime reasonable. Cache will fill progressively.

geometry              0
amenity               0
brand              1283
brand_wikidata     1407
brand_wikipedia    1634
                   ...
district_id           0
latitude              0
longitude             0
address               0
id                    0
Length: 286, dtype: int64

## 🔟 Deduplicate Records

We remove duplicates using `id` as the primary key.

In [25]:
before = len(gdf)
gdf = gdf.drop_duplicates(subset=["id"]).copy()
after = len(gdf)

print("Rows before:", before)
print("Rows after :", after)

assert gdf["id"].duplicated().sum() == 0, "Duplicate IDs remain"

Rows before: 1852
Rows after : 1852

In [27]:
# ==========================================
# Clean Name Column (Reviewer Requirement)
# ==========================================

gdf["name"] = gdf["name"].fillna("").astype(str).str.strip()
gdf.loc[gdf["name"] == "", "name"] = "unknown gas station"

print("Null name count after fix:", gdf["name"].isna().sum())
print("Unknown name count:", (gdf["name"] == "unknown gas station").sum())

Null name count after fix: 0
Unknown name count: 1337

## 1️⃣1️⃣ Final Dataset Schema (reviewer-required fields)

We keep only the required production columns, including:
`district`, `district_id`, `neighborhood`, `neighborhood_id`, and `address`.

In [40]:
for col in gdf.columns:
    print(col)

geometry
amenity
brand
brand_wikidata
brand_wikipedia
compressed_air
fuel_HGV_diesel
fuel_diesel
fuel_e10
fuel_octane_102
fuel_octane_95
man_made
name
opening_hours
surveillance
wheelchair
addr_city
addr_country
addr_housenumber
addr_postcode
addr_street
addr_suburb
check_date
fuel_ethanol
level
operator
payment_cash
payment_mastercard
payment_visa
phone
website
check_date_opening_hours
fuel_adblue
fuel_biodiesel
fuel_octane_98
shop
car_wash
contact_fax
contact_phone
contact_website
payment_american_express
payment_debit_cards
payment_diners_club
payment_dkv
payment_maestro
payment_uta
payment_v_pay
payment_westfalen_card
self_service
fuel_biogas
fuel_cng
fuel_lpg
kiosk
fuel_GTL_diesel
compressed_air_fee
fax
fuel_gts_diesel
fuel_octane_100
payment_cryptocurrencies
payment_girocard
payment_credit_cards
ref
source
toilets
toilets_wheelchair
changing_table
operator_wikidata
wheelchair_description
covered
fuel_1_50
note
currency_others
fuel_kerosene
payment_coins
payment_notes
currency_EUR
access
atm
fuel_e85
fuel_1_25
payment_routex
drink_club-mate
automated
postal_code
internet_access
internet_access_fee
smoking
description
source_opening_hours
name_de
name_en
post_office
post_office_brand
post_office_brand_wikidata
addr_inclusion
layer
car_repair
branch
roof_levels
roof_shape
check_date_compressed_air
contact_email
fuel_heating_oil
start_date
building
fuel_hvo100
payment_esso_card
payment_euroshell
payment_shell_clubsmart
official_name
ref_vatin
fuel_adblue_canister
name_signed
fuel_h35
fuel_h70
payment_h2_mobility_card
source_website
start_date_fuel_h70
lottery
valves
truck_wash
vacuum_cleaner
tenant
opening_hours_signed
building_levels
building_min_level
fuel_LH2
bus
minibus
cash_withdrawal
payment_apple_pay
payment_google_pay
surface
atm_operator
owner
landuse
service_vehicle_car_repair
service_vehicle_inspection
fuel_octane_92
height
wikimedia_commons
payment_H2_Delivery
payment_HyLane
payment_ryd_pay
start_date_fuel_h35
poi_type
amperage
authentication_short_message
bicycle
capacity
socket_type2
source_delivery_date
voltage
addr_floor
fee
operator_wikipedia
note_de
authentication_membership_card
payment_account_cards
authentication_app
authentication_nfc
motorcar
parking_fee
socket_type2_output
socket_type2_current
socket_type2_voltage
survey_date
hgv
maxstay_conditional
network
payment_paypal
scooter
colour
location
authentication_phone_call
socket_schuko
short_name
charge
payment_sepa
payment_vpay
authentication_none
comment
maxstay
socket_chademo
socket_type2_combo
socket_chademo_output
socket_type2_combo_output
truck
camera_direction
camera_mount
camera_type
highway
surveillance_type
surveillance_zone
ref_EU_EVSE
noname
output
charging_station_output
description_de
socket_usb
mapillary
socket_tesla_supercharger_ccs
socket_type2_cable
lit
support
fixme
payment_mea
object_city
object_country
object_housenumber
object_postcode
object_street
payment_app
payment_cards
payment_membership_card
payment_qr_code
capacity_motorcar
payment_bank_transfer
socket_tesla_supercharger_ccs_output
socket_type2_cable_output
payment_Giro-e
payment_Ladekarte
direction
lamp_mount
lamp_type
access_conditional
payment_contactless
small_electric_vehicle
motor_vehicle
parking_left
parking_left_fee
parking_left_maxstay
parking_left_orientation
parking_right
image
manufacturer
payment_nfc
authentication_contactless
socket_type2_combo_current
socket_type2_combo_voltage
bicycle_parking
socket_device_USB-A
socket_device_USB-C
charge_conditional
socket_type1_output
email
panoramax
panoramax_0
panoramax_1
payment_samsung_pay
orientation
indoor
operator_type
not_operator_wikidata
payment_rfid_card
payment_online_payment
payment_prepaid_cards
obstacle_parking
position
serialnumber
material
construction
motorcycle
socket_type1
socket_j3105-1
socket_j3105-1_output
capacity_charging
capacity_bicycle
taxi
socket_unknown
socket_unknown_output
markings
restriction
street_name
capacity_disabled
ref_goingelectric
socket_chademo_current
socket_chademo_voltage
neighborhood
neighborhood_id
district
district_id
latitude
longitude
address
id

In [53]:
gdf['fuel_electricity'] = None  # Or np.nan

# 2. Assign 'yes' only where the condition is met
gdf.loc[gdf['amenity'] == 'charging_station', 'fuel_electricity'] = 'yes'

In [54]:
gdf

                                     geometry           amenity       brand  \
element id
node    16541597     POINT (13.3456 52.54631)              fuel        Aral
        26756830    POINT (13.32822 52.53069)              fuel        Aral
        26867411     POINT (13.2945 52.50197)              fuel         NaN
        26882421    POINT (13.32067 52.48427)              fuel        Aral
        27088369     POINT (13.1917 52.43464)              fuel        Esso
...                                       ...               ...         ...
way     1393215147  POINT (13.26074 52.48717)  charging_station         NaN
        1412581198  POINT (13.43757 52.57307)  charging_station         NaN
        1425766408  POINT (13.52289 52.54486)  charging_station  Elpro GmbH
        1430235489  POINT (13.57874 52.45697)  charging_station         NaN
        1446480594  POINT (13.36134 52.48164)  charging_station         NaN

                   brand_wikidata brand_wikipedia compressed_air  \
element id
node    16541597          Q565734      en:Aral AG            yes
        26756830          Q565734         de:Aral            yes
        26867411              NaN             NaN            yes
        26882421          Q565734         de:Aral            yes
        27088369          Q867662             NaN            yes
...                           ...             ...            ...
way     1393215147            NaN             NaN            NaN
        1412581198            NaN             NaN            NaN
        1425766408            NaN             NaN            NaN
        1430235489            NaN             NaN            NaN
        1446480594            NaN             NaN            NaN

                   fuel_HGV_diesel fuel_diesel fuel_e10 fuel_octane_102  \
element id
node    16541597            retail         yes      yes          retail
        26756830               NaN         yes      yes             yes
        26867411               NaN         yes      yes             NaN
        26882421               NaN         yes      yes             NaN
        27088369               NaN         yes      yes             NaN
...                            ...         ...      ...             ...
way     1393215147             NaN         NaN      NaN             NaN
        1412581198             NaN         NaN      NaN             NaN
        1425766408             NaN         NaN      NaN             NaN
        1430235489             NaN         NaN      NaN             NaN
        1446480594             NaN         NaN      NaN             NaN

                   fuel_octane_95      man_made                 name  \
element id
node    16541597           retail  surveillance                 Aral
        26756830              yes           NaN                 Aral
        26867411              yes           NaN       Bavaria petrol
        26882421              yes           NaN                 Aral
        27088369              yes           NaN                 Esso
...                           ...           ...                  ...
way     1393215147            NaN           NaN  unknown gas station
        1412581198            NaN           NaN  unknown gas station
        1425766408            NaN           NaN  unknown gas station
        1430235489            NaN           NaN  unknown gas station
        1446480594            NaN           NaN  unknown gas station

                                        opening_hours surveillance wheelchair  \
element id
node    16541597                                 24/7      outdoor         no
        26756830                                 24/7          NaN        yes
        26867411    Mo-Fr 07:00-20:00; Sa 07:00-18:00          NaN         no
        26882421                                 24/7          NaN        yes
        27088369                 PH,Mo-Su 00:00-24:00          NaN        yes
...                                               ...          ...        ...
way     1393215147                               24/7          NaN        NaN
        1412581198                                NaN          NaN        NaN
        1425766408                                NaN          NaN        NaN
        1430235489                                NaN          NaN        NaN
        1446480594                                NaN          NaN        NaN

                   addr_city addr_country addr_housenumber addr_postcode  \
element id
node    16541597         NaN          NaN              NaN           NaN
        26756830      Berlin           DE               55         10553
        26867411      Berlin           DE               14         10711
        26882421         NaN          NaN              NaN           NaN
        27088369      Berlin           DE              120         14129
...                      ...          ...              ...           ...
way     1393215147       NaN          NaN              NaN           NaN
        1412581198       NaN          NaN              NaN           NaN
        1425766408       NaN          NaN              NaN           NaN
        1430235489       NaN          NaN              NaN           NaN
        1446480594       NaN          NaN              NaN           NaN

                             addr_street addr_suburb  check_date fuel_ethanol  \
element id
node    16541597                     NaN         NaN         NaN          NaN
        26756830           Beusselstraße      Moabit  2023-10-10          yes
        26867411      Heilbronner Straße    Halensee         NaN          NaN
        26882421                     NaN         NaN         NaN          NaN
        27088369    Kronprinzessinnenweg  Nikolassee         NaN          NaN
...                                  ...         ...         ...          ...
way     1393215147                   NaN         NaN         NaN          NaN
        1412581198                   NaN         NaN         NaN          NaN
        1425766408                   NaN         NaN         NaN          NaN
        1430235489                   NaN         NaN         NaN          NaN
        1446480594                   NaN         NaN         NaN          NaN

                   level        operator payment_cash payment_mastercard  \
element id
node    16541597     NaN             NaN          NaN                NaN
        26756830       0      Mike Seitz          yes                yes
        26867411     NaN  Bavaria Petrol          NaN                NaN
        26882421     NaN             NaN          yes                yes
        27088369     NaN             NaN          NaN                NaN
...                  ...             ...          ...                ...
way     1393215147   NaN  Shell Recharge          NaN                NaN
        1412581198   NaN             NaN          NaN                NaN
        1425766408   NaN      Elpro GmbH          NaN                NaN
        1430235489   NaN             NaN          NaN                NaN
        1446480594   NaN          Qwello          NaN                NaN

                   payment_visa           phone  \
element id
node    16541597            NaN             NaN
        26756830            yes  +49 30 3914404
        26867411            NaN             NaN
        26882421            yes             NaN
        27088369            NaN             NaN
...                         ...             ...
way     1393215147          NaN             NaN
        1412581198          NaN             NaN
        1425766408          NaN             NaN
        1430235489          NaN             NaN
        1446480594          NaN             NaN

                                                              website  \
element id
node    16541597                                                  NaN
        26756830    https://tankstelle.aral.de/berlin/beusselstras...
        26867411                                                  NaN
        26882421                                                  NaN
        27088369                                                  NaN
...                                                               ...
way     1393215147                                                NaN
        1412581198                                                NaN
        1425766408                                                NaN
        1430235489                                                NaN
        1446480594                                                NaN

                   check_date_opening_hours fuel_adblue fuel_biodiesel  \
element id
node    16541597                        NaN         NaN            NaN
        26756830                        NaN         NaN            NaN
        26867411                 2026-01-05         yes            yes
        26882421                        NaN         NaN            NaN
        27088369                        NaN         NaN            NaN
...                                     ...         ...            ...
way     1393215147                      NaN         NaN            NaN
        1412581198                      NaN         NaN            NaN
        1425766408                      NaN         NaN            NaN
        1430235489                      NaN         NaN            NaN
        1446480594                      NaN         NaN            NaN

                   fuel_octane_98   shop car_wash      contact_fax  \
element id
node    16541597              NaN    NaN      NaN              NaN
        26756830              NaN    NaN      NaN              NaN
        26867411              yes  kiosk      NaN              NaN
        26882421              yes    NaN      yes  +49 30 84315141
        27088369              yes    NaN      NaN              NaN
...                           ...    ...      ...              ...
way     1393215147            NaN    NaN      NaN              NaN
        1412581198            NaN    NaN      NaN              NaN
        1425766408            NaN    NaN      NaN              NaN
        1430235489            NaN    NaN      NaN              NaN
        1446480594            NaN    NaN      NaN              NaN

                     contact_phone  \
element id
node    16541597               NaN
        26756830               NaN
        26867411               NaN
        26882421    +49 30 8738323
        27088369               NaN
...                            ...
way     1393215147             NaN
        1412581198             NaN
        1425766408             NaN
        1430235489             NaN
        1446480594             NaN

                                                      contact_website  \
element id
node    16541597                                                  NaN
        26756830                                                  NaN
        26867411                                                  NaN
        26882421    https://tankstelle.aral.de/berlin/blissestrass...
        27088369                                                  NaN
...                                                               ...
way     1393215147                                                NaN
        1412581198                                                NaN
        1425766408                                                NaN
        1430235489                                                NaN
        1446480594                                                NaN

                   payment_american_express payment_debit_cards  \
element id
node    16541597                        NaN                 NaN
        26756830                        NaN                 NaN
        26867411                        NaN                 NaN
        26882421                        yes                 yes
        27088369                        NaN                 NaN
...                                     ...                 ...
way     1393215147                      NaN                 NaN
        1412581198                      NaN                 NaN
        1425766408                      NaN                 NaN
        1430235489                      NaN                 NaN
        1446480594                      NaN                 NaN

                   payment_diners_club payment_dkv payment_maestro  \
element id
node    16541597                   NaN         NaN             NaN
        26756830                   NaN         NaN             NaN
        26867411                   NaN         NaN             NaN
        26882421                   yes         yes             yes
        27088369                   NaN         NaN             NaN
...                                ...         ...             ...
way     1393215147                 NaN         NaN             NaN
        1412581198                 NaN         NaN             NaN
        1425766408                 NaN         NaN             NaN
        1430235489                 NaN         NaN             NaN
        1446480594                 NaN         NaN             NaN

                   payment_uta payment_v_pay payment_westfalen_card  \
element id
node    16541597           NaN           NaN                    NaN
        26756830           NaN           NaN                    NaN
        26867411           NaN           NaN                    NaN
        26882421           yes           yes                    yes
        27088369           NaN           NaN                    NaN
...                        ...           ...                    ...
way     1393215147         NaN           NaN                    NaN
        1412581198         NaN           NaN                    NaN
        1425766408         NaN           NaN                    NaN
        1430235489         NaN           NaN                    NaN
        1446480594         NaN           NaN                    NaN

                   self_service fuel_biogas fuel_cng fuel_lpg kiosk  \
element id
node    16541597            NaN         NaN      NaN      NaN   NaN
        26756830            NaN         NaN      NaN      NaN   NaN
        26867411            NaN         NaN      NaN      NaN   NaN
        26882421            yes         NaN      NaN      NaN   NaN
        27088369            NaN         NaN      NaN      NaN   NaN
...                         ...         ...      ...      ...   ...
way     1393215147          NaN         NaN      NaN      NaN   NaN
        1412581198          NaN         NaN      NaN      NaN   NaN
        1425766408          NaN         NaN      NaN      NaN   NaN
        1430235489          NaN         NaN      NaN      NaN   NaN
        1446480594          NaN         NaN      NaN      NaN   NaN

                   fuel_GTL_diesel compressed_air_fee  fax fuel_gts_diesel  \
element id
node    16541597               NaN                NaN  NaN             NaN
        26756830               NaN                NaN  NaN             NaN
        26867411               NaN                NaN  NaN             NaN
        26882421               NaN                NaN  NaN             NaN
        27088369               NaN                NaN  NaN             NaN
...                            ...                ...  ...             ...
way     1393215147             NaN                NaN  NaN             NaN
        1412581198             NaN                NaN  NaN             NaN
        1425766408             NaN                NaN  NaN             NaN
        1430235489             NaN                NaN  NaN             NaN
        1446480594             NaN                NaN  NaN             NaN

                   fuel_octane_100 payment_cryptocurrencies payment_girocard  \
element id
node    16541597               NaN                      NaN              NaN
        26756830               NaN                      NaN              NaN
        26867411               NaN                      NaN              NaN
        26882421               NaN                      NaN              NaN
        27088369               NaN                      NaN              NaN
...                            ...                      ...              ...
way     1393215147             NaN                      NaN              NaN
        1412581198             NaN                      NaN              NaN
        1425766408             NaN                      NaN              NaN
        1430235489             NaN                      NaN              NaN
        1446480594             NaN                      NaN              NaN

                   payment_credit_cards  ref source toilets  \
element id
node    16541597                    NaN  NaN    NaN     NaN
        26756830                    NaN  NaN    NaN     NaN
        26867411                    NaN  NaN    NaN     NaN
        26882421                    NaN  NaN    NaN     NaN
        27088369                    NaN  NaN    NaN     NaN
...                                 ...  ...    ...     ...
way     1393215147                  NaN  NaN    NaN     NaN
        1412581198                  NaN  NaN    NaN     NaN
        1425766408                  NaN  NaN    NaN     NaN
        1430235489                  NaN  NaN    NaN     NaN
        1446480594                  NaN  NaN    NaN     NaN

                   toilets_wheelchair changing_table operator_wikidata  \
element id
node    16541597                  NaN            NaN               NaN
        26756830                  NaN            NaN               NaN
        26867411                  NaN            NaN               NaN
        26882421                  NaN            NaN               NaN
        27088369                  NaN            NaN               NaN
...                               ...            ...               ...
way     1393215147                NaN            NaN        Q105883058
        1412581198                NaN            NaN               NaN
        1425766408                NaN            NaN               NaN
        1430235489                NaN            NaN               NaN
        1446480594                NaN            NaN               NaN

                   wheelchair_description covered fuel_1_50 note  \
element id
node    16541597                      NaN     NaN       NaN  NaN
        26756830                      NaN     NaN       NaN  NaN
        26867411                      NaN     NaN       NaN  NaN
        26882421                      NaN     NaN       NaN  NaN
        27088369                      NaN     NaN       NaN  NaN
...                                   ...     ...       ...  ...
way     1393215147                    NaN     NaN       NaN  NaN
        1412581198                    NaN     NaN       NaN  NaN
        1425766408                    NaN     NaN       NaN  NaN
        1430235489                    NaN     NaN       NaN  NaN
        1446480594                    NaN     NaN       NaN  NaN

                   currency_others fuel_kerosene payment_coins payment_notes  \
element id
node    16541597               NaN           NaN           NaN           NaN
        26756830               NaN           NaN           NaN           NaN
        26867411               NaN           NaN           NaN           NaN
        26882421               NaN           NaN           NaN           NaN
        27088369               NaN           NaN           NaN           NaN
...                            ...           ...           ...           ...
way     1393215147             NaN           NaN           NaN           NaN
        1412581198             NaN           NaN           NaN           NaN
        1425766408             NaN           NaN           NaN           NaN
        1430235489             NaN           NaN           NaN           NaN

In [62]:
# ==========================================
# Make column names SQL-safe (replace ":" with "_")
# ==========================================
gdf.columns = [c.replace(":", "_") for c in gdf.columns]

# ==========================================
# Final export schema.
# ==========================================
FINAL_COLS = [
    "id",
    "name",
    "brand",
    "operator",
    "address",
    "latitude",
    "longitude",
    "district",
    "district_id",
    "neighborhood",
    "neighborhood_id",
    "opening_hours",
    "payment_paypal",
    "payment_cards",
    "car_wash",
    "compressed_air",
    "wheelchair",
    "fuel_diesel",
    "fuel_octane_95",
    "fuel_electricity",
    "geometry",
]

# Keep only columns that exist
FINAL_COLS = [c for c in FINAL_COLS if c in gdf.columns]

# Safety check
missing = [c for c in ["id","name","district","district_id","neighborhood","neighborhood_id","geometry"] if c not in FINAL_COLS]
assert not missing, f"Missing critical columns: {missing}"

gdf_final = gdf[FINAL_COLS].copy()

print("Final export dataframe = gdf_final")
print("Rows:", len(gdf_final), "| Cols:", len(gdf_final.columns))
gdf_final.head(3)

Final export dataframe = gdf_final
Rows: 1852 | Cols: 21

                                      id            name brand  \
element id
node    16541597  gs_52.546315_13.345599            Aral  Aral
        26756830  gs_52.530694_13.328225            Aral  Aral
        26867411  gs_52.501974_13.294496  Bavaria petrol   NaN

                        operator  \
element id
node    16541597             NaN
        26756830      Mike Seitz
        26867411  Bavaria Petrol

                                                            address  \
element id
node    16541597  Aral, Seestraße, Brüsseler Kiez, Wedding, Mitt...
        26756830  Aral, 55, Beusselstraße, Beusselkiez, Moabit, ...
        26867411  Bavaria petrol, 14, Heilbronner Straße, Witzle...

                   latitude  longitude                    district  \
element id
node    16541597  52.546315  13.345599                       Mitte
        26756830  52.530694  13.328225                       Mitte
        26867411  52.501974  13.294496  Charlottenburg-Wilmersdorf

                 district_id neighborhood neighborhood_id  \
element id
node    16541597    11001001      Wedding            0105
        26756830    11001001       Moabit            0102
        26867411    11004004     Halensee            0407

                                      opening_hours payment_paypal  \
element id
node    16541597                               24/7            NaN
        26756830                               24/7            NaN
        26867411  Mo-Fr 07:00-20:00; Sa 07:00-18:00            NaN

                 payment_cards car_wash compressed_air wheelchair fuel_diesel  \
element id
node    16541597           NaN      NaN            yes         no         yes
        26756830           NaN      NaN            yes        yes         yes
        26867411           NaN      NaN            yes         no         yes

                 fuel_octane_95 fuel_electricity                   geometry
element id
node    16541597         retail             None   POINT (13.3456 52.54631)
        26756830            yes             None  POINT (13.32822 52.53069)
        26867411            yes             None   POINT (13.2945 52.50197)

## 1️⃣2️⃣ Export Outputs

We export the final dataset as:
- GeoJSON (geospatial)
- CSV (geometry stored as WKT)

In [63]:
# --- Final QA (reviewer-safe)
required = ["id", "name", "address", "district", "district_id", "neighborhood", "neighborhood_id", "geometry"]
missing = [c for c in required if c not in gdf_final.columns]
assert not missing, f"Missing required columns in gdf_final: {missing}"

assert gdf_final["id"].isna().sum() == 0, "id has nulls"
assert gdf_final["id"].duplicated().sum() == 0, "id has duplicates"

# reviewer requirement: neighborhood_id must come from spatial_alias (4-digit like 0105)
print("Sample neighborhood_id:", gdf_final["neighborhood_id"].dropna().astype(str).head(5).tolist())
print("Nulls -> address:", int(gdf_final["address"].isna().sum()))
print("Nulls -> district_id:", int(gdf_final["district_id"].isna().sum()))
print("Rows:", len(gdf_final))

# ensure no 'unknown' in address
assert not gdf_final["address"].astype(str).str.lower().eq("unknown").any(), "Found 'unknown' in address"

Sample neighborhood_id: ['0105', '0102', '0407', '0402', '0606']
Nulls -> address: 0
Nulls -> district_id: 0
Rows: 1852

In [43]:
pd.set_option('display.max_columns', None)

In [64]:
gdf_final

                                        id                 name       brand  \
element id
node    16541597    gs_52.546315_13.345599                 Aral        Aral
        26756830    gs_52.530694_13.328225                 Aral        Aral
        26867411    gs_52.501974_13.294496       Bavaria petrol         NaN
        26882421    gs_52.484265_13.320669                 Aral        Aral
        27088369    gs_52.434641_13.191704                 Esso        Esso
...                                    ...                  ...         ...
way     1393215147  gs_52.487165_13.260739  unknown gas station         NaN
        1412581198   gs_52.57307_13.437571  unknown gas station         NaN
        1425766408  gs_52.544861_13.522889  unknown gas station  Elpro GmbH
        1430235489  gs_52.456973_13.578744  unknown gas station         NaN
        1446480594  gs_52.481644_13.361344  unknown gas station         NaN

                          operator  \
element id
node    16541597               NaN
        26756830        Mike Seitz
        26867411    Bavaria Petrol
        26882421               NaN
        27088369               NaN
...                            ...
way     1393215147  Shell Recharge
        1412581198             NaN
        1425766408      Elpro GmbH
        1430235489             NaN
        1446480594          Qwello

                                                              address  \
element id
node    16541597    Aral, Seestraße, Brüsseler Kiez, Wedding, Mitt...
        26756830    Aral, 55, Beusselstraße, Beusselkiez, Moabit, ...
        26867411    Bavaria petrol, 14, Heilbronner Straße, Witzle...
        26882421    Aral, Uhlandstraße, Wilhelmsaue, Güntzelkiez, ...
        27088369    Esso, 120, Kronprinzessinnenweg, Nikolassee, S...
...                                                               ...
way     1393215147  Auerbachstraße, Grunewald, Charlottenburg-Wilm...
        1412581198  Romain-Rolland-Straße, Alt-Heinersdorf, Heiner...
        1425766408  Elpro GmbH, Elpro, Wohnsiedlung Dingelstädter ...
        1430235489  Parrisiusstraße, Dammvorstadt, Köpenick, Trept...
        1446480594  Leberstraße, Rote Insel, Schöneberg, Tempelhof...

                     latitude  longitude                    district  \
element id
node    16541597    52.546315  13.345599                       Mitte
        26756830    52.530694  13.328225                       Mitte
        26867411    52.501974  13.294496  Charlottenburg-Wilmersdorf
        26882421    52.484265  13.320669  Charlottenburg-Wilmersdorf
        27088369    52.434641  13.191704         Steglitz-Zehlendorf
...                       ...        ...                         ...
way     1393215147  52.487165  13.260739  Charlottenburg-Wilmersdorf
        1412581198  52.573070  13.437571                      Pankow
        1425766408  52.544861  13.522889                 Lichtenberg
        1430235489  52.456973  13.578744            Treptow-Köpenick
        1446480594  52.481644  13.361344        Tempelhof-Schöneberg

                   district_id          neighborhood neighborhood_id  \
element id
node    16541597      11001001               Wedding            0105
        26756830      11001001                Moabit            0102
        26867411      11004004              Halensee            0407
        26882421      11004004           Wilmersdorf            0402
        27088369      11006006            Nikolassee            0606
...                        ...                   ...             ...
way     1393215147    11004004             Grunewald            0404
        1412581198    11003003           Heinersdorf            0304
        1425766408    11011011  Alt-Hohenschönhausen            1110
        1430235489    11009009              Köpenick            0910
        1446480594    11007007            Schöneberg            0701

                                        opening_hours payment_paypal  \
element id
node    16541597                                 24/7            NaN
        26756830                                 24/7            NaN
        26867411    Mo-Fr 07:00-20:00; Sa 07:00-18:00            NaN
        26882421                                 24/7            NaN
        27088369                 PH,Mo-Su 00:00-24:00            NaN
...                                               ...            ...
way     1393215147                               24/7            NaN
        1412581198                                NaN            NaN
        1425766408                                NaN            NaN
        1430235489                                NaN            NaN
        1446480594                                NaN            NaN

                   payment_cards car_wash compressed_air wheelchair  \
element id
node    16541597             NaN      NaN            yes         no
        26756830             NaN      NaN            yes        yes
        26867411             NaN      NaN            yes         no
        26882421             NaN      yes            yes        yes
        27088369             NaN      NaN            yes        yes
...                          ...      ...            ...        ...
way     1393215147           NaN      NaN            NaN        NaN
        1412581198           NaN      NaN            NaN        NaN
        1425766408           NaN      NaN            NaN        NaN
        1430235489           NaN      NaN            NaN        NaN
        1446480594           NaN      NaN            NaN        NaN

                   fuel_diesel fuel_octane_95 fuel_electricity  \
element id
node    16541597           yes         retail             None
        26756830           yes            yes             None
        26867411           yes            yes             None
        26882421           yes            yes             None
        27088369           yes            yes             None
...                        ...            ...              ...
way     1393215147         NaN            NaN              yes
        1412581198         NaN            NaN              yes
        1425766408         NaN            NaN              yes
        1430235489         NaN            NaN              yes
        1446480594         NaN            NaN              yes

                                     geometry
element id
node    16541597     POINT (13.3456 52.54631)
        26756830    POINT (13.32822 52.53069)
        26867411     POINT (13.2945 52.50197)
        26882421    POINT (13.32067 52.48427)
        27088369     POINT (13.1917 52.43464)
...                                       ...
way     1393215147  POINT (13.26074 52.48717)
        1412581198  POINT (13.43757 52.57307)
        1425766408  POINT (13.52289 52.54486)
        1430235489  POINT (13.57874 52.45697)
        1446480594  POINT (13.36134 52.48164)

[1852 rows x 21 columns]

In [82]:
gdf_final["geometry"] = gdf_final.geometry.to_wkt()

/var/folders/tk/bx1zbkk52y3b84pwkrt4dz5c0000gn/T/ipykernel_30962/1243302283.py:1: UserWarning: Geometry column does not contain geometry.
  gdf_final["geometry"] = gdf_final.geometry.to_wkt()

In [48]:
gdf_final['payment_cards'].unique()

array([nan, 'yes', 'no'], dtype=object)

In [83]:
gdf_final.info()

<class 'geopandas.geodataframe.GeoDataFrame'>
RangeIndex: 1852 entries, 0 to 1851
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   id                1852 non-null   object
 1   name              1852 non-null   object
 2   brand             569 non-null    object
 3   operator          1358 non-null   object
 4   address           1852 non-null   object
 5   latitude          1852 non-null   float64
 6   longitude         1852 non-null   float64
 7   district          1852 non-null   object
 8   district_id       1852 non-null   object
 9   neighborhood      1852 non-null   object
 10  neighborhood_id   1852 non-null   object
 11  opening_hours     510 non-null    object
 12  payment_paypal    27 non-null     object
 13  payment_cards     21 non-null     object
 14  car_wash          23 non-null     object
 15  compressed_air    268 non-null    object
 16  wheelchair        233 non-null    object
 17  fuel_diesel       243 non-null    object
 18  fuel_octane_95    246 non-null    object
 19  fuel_electricity  1563 non-null   object
 20  geometry          1852 non-null   object
dtypes: float64(2), object(19)
memory usage: 304.0+ KB

In [19]:
# --- Export Outputs (requires gdf_final)
assert "gdf_final" in globals(), "gdf_final not defined yet. Run the final schema cell before export."

# GeoJSON
gdf_final.to_file(OUT_GEOJSON, driver="GeoJSON")

# CSV: store geometry as WKT
df_csv = gdf_final.drop(columns="geometry").copy()
df_csv["geometry_wkt"] = gdf_final.geometry.to_wkt()
df_csv.to_csv(OUT_CSV, index=False)

print("Saved:", OUT_GEOJSON, "exists:", OUT_GEOJSON.exists())
print("Saved:", OUT_CSV, "exists:", OUT_CSV.exists())
print("Final rows:", len(gdf_final))

Saved: /Users/khizratariq/clone-repository/layered-populate-data-pool-da/gas-stations/sources/gas_stations_transformed.geojson exists: True
Saved: /Users/khizratariq/clone-repository/layered-populate-data-pool-da/gas-stations/sources/gas_stations_transformed.csv exists: True
Final rows: 1844

In [73]:
#gdf_final=gdf_final.drop(columns=['id'])
gdf_final=gdf_final.reset_index()
gdf_final

,element,id,name,brand,operator,address,latitude,longitude,district,district_id,neighborhood,neighborhood_id,opening_hours,payment_paypal,payment_cards,car_wash,compressed_air,wheelchair,fuel_diesel,fuel_octane_95,fuel_electricity,geometry
0,node,16541597,Aral,Aral,NaN,"Aral, Seestraße, Brüsseler Kiez, Wedding, Mitt...",52.546315,13.345599,Mitte,11001001,Wedding,0105,24/7,NaN,NaN,NaN,yes,no,yes,retail,None,POINT (13.3456 52.54631)
1,node,26756830,Aral,Aral,Mike Seitz,"Aral, 55, Beusselstraße, Beusselkiez, Moabit, ...",52.530694,13.328225,Mitte,11001001,Moabit,0102,24/7,NaN,NaN,NaN,yes,yes,yes,yes,None,POINT (13.32822 52.53069)
2,node,26867411,Bavaria petrol,NaN,Bavaria Petrol,"Bavaria petrol, 14, Heilbronner Straße, Witzle...",52.501974,13.294496,Charlottenburg-Wilmersdorf,11004004,Halensee,0407,Mo-Fr 07:00-20:00; Sa 07:00-18:00,NaN,NaN,NaN,yes,no,yes,yes,None,POINT (13.2945 52.50197)
3,node,26882421,Aral,Aral,NaN,"Aral, Uhlandstraße, Wilhelmsaue, Güntzelkiez, ...",52.484265,13.320669,Charlottenburg-Wilmersdorf,11004004,Wilmersdorf,0402,24/7,NaN,NaN,yes,yes,yes,yes,yes,None,POINT (13.32067 52.48427)
4,node,27088369,Esso,Esso,NaN,"Esso, 120, Kronprinzessinnenweg, Nikolassee, S...",52.434641,13.191704,Steglitz-Zehlendorf,11006006,Nikolassee,0606,"PH,Mo-Su 00:00-24:00",NaN,NaN,NaN,yes,yes,yes,yes,None,POINT (13.1917 52.43464)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1847,way,1393215147,unknown gas station,NaN,Shell Recharge,"Auerbachstraße, Grunewald, Charlottenburg-Wilm...",52.487165,13.260739,Charlottenburg-Wilmersdorf,11004004,Grunewald,0404,24/7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,yes,POINT (13.26074 52.48717)
1848,way,1412581198,unknown gas station,NaN,NaN,"Romain-Rolland-Straße, Alt-Heinersdorf, Heiner...",52.573070,13.437571,Pankow,11003003,Heinersdorf,0304,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,yes,POINT (13.43757 52.57307)
1849,way,1425766408,unknown gas station,Elpro GmbH,Elpro GmbH,"Elpro GmbH, Elpro, Wohnsiedlung Dingelstädter ...",52.544861,13.522889,Lichtenberg,11011011,Alt-Hohenschönhausen,1110,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,yes,POINT (13.52289 52.54486)
1850,way,1430235489,unknown gas station,NaN,NaN,"Parrisiusstraße, Dammvorstadt, Köpenick, Trept...",52.456973,13.578744,Treptow-Köpenick,11009009,Köpenick,0910,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,yes,POINT (13.57874 52.45697)
1851,way,1446480594,unknown gas station,NaN,Qwello,"Leberstraße, Rote Insel, Schöneberg, Tempelhof...",52.481644,13.361344,Tempelhof-Schöneberg,11007007,Schöneberg,0701,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,yes,POINT (13.36134 52.48164)

In [74]:
print(gdf_final.columns.tolist())

['element', 'id', 'name', 'brand', 'operator', 'address', 'latitude', 'longitude', 'district', 'district_id', 'neighborhood', 'neighborhood_id', 'opening_hours', 'payment_paypal', 'payment_cards', 'car_wash', 'compressed_air', 'wheelchair', 'fuel_diesel', 'fuel_octane_95', 'fuel_electricity', 'geometry']

In [75]:
# Ensure both are strings and handle potential nulls
gdf_final['id'] = gdf_final['element'].fillna('').astype(str) + gdf_final['id'].astype(str)

In [76]:
gdf_final=gdf_final.drop(columns=['element'])

In [77]:
gdf_final

,id,name,brand,operator,address,latitude,longitude,district,district_id,neighborhood,neighborhood_id,opening_hours,payment_paypal,payment_cards,car_wash,compressed_air,wheelchair,fuel_diesel,fuel_octane_95,fuel_electricity,geometry
0,node16541597,Aral,Aral,NaN,"Aral, Seestraße, Brüsseler Kiez, Wedding, Mitt...",52.546315,13.345599,Mitte,11001001,Wedding,0105,24/7,NaN,NaN,NaN,yes,no,yes,retail,None,POINT (13.3456 52.54631)
1,node26756830,Aral,Aral,Mike Seitz,"Aral, 55, Beusselstraße, Beusselkiez, Moabit, ...",52.530694,13.328225,Mitte,11001001,Moabit,0102,24/7,NaN,NaN,NaN,yes,yes,yes,yes,None,POINT (13.32822 52.53069)
2,node26867411,Bavaria petrol,NaN,Bavaria Petrol,"Bavaria petrol, 14, Heilbronner Straße, Witzle...",52.501974,13.294496,Charlottenburg-Wilmersdorf,11004004,Halensee,0407,Mo-Fr 07:00-20:00; Sa 07:00-18:00,NaN,NaN,NaN,yes,no,yes,yes,None,POINT (13.2945 52.50197)
3,node26882421,Aral,Aral,NaN,"Aral, Uhlandstraße, Wilhelmsaue, Güntzelkiez, ...",52.484265,13.320669,Charlottenburg-Wilmersdorf,11004004,Wilmersdorf,0402,24/7,NaN,NaN,yes,yes,yes,yes,yes,None,POINT (13.32067 52.48427)
4,node27088369,Esso,Esso,NaN,"Esso, 120, Kronprinzessinnenweg, Nikolassee, S...",52.434641,13.191704,Steglitz-Zehlendorf,11006006,Nikolassee,0606,"PH,Mo-Su 00:00-24:00",NaN,NaN,NaN,yes,yes,yes,yes,None,POINT (13.1917 52.43464)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1847,way1393215147,unknown gas station,NaN,Shell Recharge,"Auerbachstraße, Grunewald, Charlottenburg-Wilm...",52.487165,13.260739,Charlottenburg-Wilmersdorf,11004004,Grunewald,0404,24/7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,yes,POINT (13.26074 52.48717)
1848,way1412581198,unknown gas station,NaN,NaN,"Romain-Rolland-Straße, Alt-Heinersdorf, Heiner...",52.573070,13.437571,Pankow,11003003,Heinersdorf,0304,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,yes,POINT (13.43757 52.57307)
1849,way1425766408,unknown gas station,Elpro GmbH,Elpro GmbH,"Elpro GmbH, Elpro, Wohnsiedlung Dingelstädter ...",52.544861,13.522889,Lichtenberg,11011011,Alt-Hohenschönhausen,1110,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,yes,POINT (13.52289 52.54486)
1850,way1430235489,unknown gas station,NaN,NaN,"Parrisiusstraße, Dammvorstadt, Köpenick, Trept...",52.456973,13.578744,Treptow-Köpenick,11009009,Köpenick,0910,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,yes,POINT (13.57874 52.45697)
1851,way1446480594,unknown gas station,NaN,Qwello,"Leberstraße, Rote Insel, Schöneberg, Tempelhof...",52.481644,13.361344,Tempelhof-Schöneberg,11007007,Schöneberg,0701,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,yes,POINT (13.36134 52.48164)

In [78]:
print("gdf_final rows:", len(gdf_final))
print("gdf_final cols:", list(gdf_final.columns))

print(gdf_final[["district", "district_id"]].drop_duplicates().sort_values("district_id"))
print("Name nulls:", gdf_final["name"].isna().sum())

print("Will write to:", OUT_GEOJSON)
print("Will write to:", OUT_CSV)

gdf_final rows: 1852
gdf_final cols: ['id', 'name', 'brand', 'operator', 'address', 'latitude', 'longitude', 'district', 'district_id', 'neighborhood', 'neighborhood_id', 'opening_hours', 'payment_paypal', 'payment_cards', 'car_wash', 'compressed_air', 'wheelchair', 'fuel_diesel', 'fuel_octane_95', 'fuel_electricity', 'geometry']
                      district district_id
0                        Mitte    11001001
11    Friedrichshain-Kreuzberg    11002002
43                      Pankow    11003003
2   Charlottenburg-Wilmersdorf    11004004
18                     Spandau    11005005
4          Steglitz-Zehlendorf    11006006
25        Tempelhof-Schöneberg    11007007
26                    Neukölln    11008008
24            Treptow-Köpenick    11009009
12         Marzahn-Hellersdorf    11010010
13                 Lichtenberg    11011011
8                Reinickendorf    11012012
Name nulls: 0
Will write to: /Users/kajetanhanausek/Desktop/cloned_repos/layered-populate-data-pool-da/gas-stations/sources/gas_stations_transformed.geojson
Will write to: /Users/kajetanhanausek/Desktop/cloned_repos/layered-populate-data-pool-da/gas-stations/sources/gas_stations_transformed.csv

In [85]:
gdf_final.info()

<class 'geopandas.geodataframe.GeoDataFrame'>
RangeIndex: 1852 entries, 0 to 1851
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   id                1852 non-null   object
 1   name              1852 non-null   object
 2   brand             569 non-null    object
 3   operator          1358 non-null   object
 4   address           1852 non-null   object
 5   latitude          1852 non-null   float64
 6   longitude         1852 non-null   float64
 7   district          1852 non-null   object
 8   district_id       1852 non-null   object
 9   neighborhood      1852 non-null   object
 10  neighborhood_id   1852 non-null   object
 11  opening_hours     510 non-null    object
 12  payment_paypal    27 non-null     object
 13  payment_cards     21 non-null     object
 14  car_wash          23 non-null     object
 15  compressed_air    268 non-null    object
 16  wheelchair        233 non-null    object
 17  fuel_diesel       243 non-null    object
 18  fuel_octane_95    246 non-null    object
 19  fuel_electricity  1563 non-null   object
 20  geometry          1852 non-null   object
dtypes: float64(2), object(19)
memory usage: 304.0+ KB

In [79]:
import psycopg2
import pandas as pd
from sqlalchemy import create_engine, text
import warnings

In [ ]:
engine = create_engine('postgresql+psycopg2://USER_NAME:PASSWORD@localhost:5433/layereddb')

query_access=f"""
DROP TABLE IF EXISTS berlin_source_data.gas_stations;

CREATE TABLE berlin_source_data.gas_stations (
    id TEXT PRIMARY KEY,
    name TEXT,
    brand text,
    operator text,
    address text,
    latitude decimal(9,6),
    longitude decimal(9,6),
    district TEXT,
    district_id TEXT,
    neighborhood TEXT,
    neighborhood_id TEXT,
    payment_cards text,
    payment_paypal text,
    car_wash text,         
    compressed_air text,   
    wheelchair text,       
    fuel_diesel text,      
    fuel_octane_95 text,
    fuel_electricity text,
    opening_hours text,
    geometry text,
    CONSTRAINT district_id_fk FOREIGN KEY (district_id)
        REFERENCES berlin_source_data.districts(district_id)
        ON DELETE RESTRICT
        ON UPDATE CASCADE
);
"""
with engine.connect() as conn:
    conn.execute(text(query_access))
    conn.commit()

In [89]:
gdf_final.to_sql(
    "gas_stations",
    engine,
    schema="berlin_source_data",
    if_exists="append",   # append to existing
    index=False
)

852